== "C" 扩展：压缩指令，版本 2.0

本章描述了 RISC-V 标准压缩指令集扩展，称为 "C"，通过为常见操作添加简短的 16 位指令编码来减少静态和动态代码大小。C 扩展可以添加到任何基本 ISA（RV32、RV64、RV128），我们使用通用术语 "RVC" 来涵盖这些基础架构。通常，程序中 50%-60% 的 RISC-V 指令可以替换为 RVC 指令，从而实现减少 25%-30% 的代码量。

=== 概述

RVC 使用了一种简单的压缩方案，当满足以下条件时，提供常见 32 位 RISC-V 指令的简短 16 位版本：

* 立即数或地址偏移量较小
* 其中一个寄存器是零寄存器（`x0`）、ABI 链接寄存器（`x1`）或 ABI 堆栈指针（`x2`）
* 目标寄存器和第一个源寄存器相同
* 使用的寄存器是最常用的 8 个寄存器之一

C 扩展与所有其他标准指令扩展兼容。C 扩展允许 16 位指令与 32 位指令自由混合使用，且后者现在可以在任何 16 位边界上开始，即 IALIGN=16。随着 C 扩展的加入，不再有指令可以引发指令地址未对齐异常（instruction-address-misaligned exceptions）。

[NOTE]
====
取消对初始 32 位指令的 32 位对齐约束可以显著提高代码密度。
====

压缩指令编码在 RV32C、RV64C 和 RV128C 之间大多是通用的，但如 <<rvc-instr-table0, Table 34>> 所示，一些操作码根据基本 ISA 的不同而有不同的用途。例如，具有更宽地址空间的 RV64C 和 RV128C 变体需要额外的操作码来压缩 64 位整数值的加载和存储，而 RV32C 使用相同的操作码来压缩单精度浮点值的加载和存储。同样，RV128C 需要额外的操作码来处理 128 位整数值的加载和存储，而这些相同的操作码在 RV32C 和 RV64C 中用于加载和存储双精度浮点值。如果实现了 C 扩展，则必须在实现相关标准浮点扩展（F 和/或 D）时提供适当的压缩浮点加载和存储指令。此外，RV32C 包括一个压缩跳转和链接指令，用于压缩短距离子程序调用，而相同的操作码在 RV64C 和 RV128C 中用于压缩 ADDIW 指令。

[TIP]
====
双精度加载和存储是静态和动态指令的重要组成部分，因此有必要将它们包含于 RV32C 和 RV64C 编码中。

虽然单精度加载和存储指令在目前支持的 ABI 下编译的基准测试中不是静态或动态压缩的重要来源，但对于仅提供硬件单精度浮点单元并且具有仅支持单精度浮点数的 ABI 的微控制器而言，单精度加载和存储指令的使用频率将至少与双精度加载和存储指令相当。因此，有必要在 RV32C 中提供对这些指令的压缩支持。

短距离子程序调用在微控制器的小型二进制文件中更常见，因此有必要将它们包含于 RV32C 中。

尽管为不同的基础 ISA 重用操作码会增加一些文档的复杂性，但即使是支持多个基本 ISA 的设计，实施复杂性的影响也很小。压缩的浮点加载和存储变体与宽整数加载和存储指令使用相同的指令格式，并具有相同的寄存器指定符。
====

RVC 是在以下约束下设计的：每条 RVC 指令扩展为基础 ISA（RV32I/E、RV64I/E 或 RV128I）或存在的 F 和 D 标准扩展中的单个 32 位指令。采用这一约束有两个主要好处：

* 硬件设计可以在解码阶段简单地扩展 RVC 指令，从而简化验证并最小化对现有微架构的修改。

* 编译器可以对 RVC 扩展不知情，将代码压缩留给汇编器和链接器来处理，尽管具有压缩感知功能的编译器通常能够产生更好的结果。

[NOTE]
====
我们认为 C 和基础 IFD 指令之间简单的一对一映射所带来的多重复杂性减少，远远超过了仅在 C 扩展中支持的额外指令，或允许在一个 C 指令中编码多个 IFD 指令的稍微更密集编码的潜在收益。
====

需要注意的是，C 扩展并不是一个在设计上独立的 ISA，而是与基本 ISA 一起使用。

[TIP]
====
长期以来，可变长度指令集一直用于提高代码密度。例如，IBM Stretch cite:[stretch] 于 1950 年代后期开发具有 32 位和 64 位指令集，其中一些 32 位指令是完整 64 位指令的压缩版本。Stretch 还采用了限制某些较短指令格式中可寻址寄存器集的概念，使用短跳转指令，这些指令只能引用其中一个索引寄存器。后来的 IBM 360 架构 cite:[ibm360] 支持简单的可变长度指令编码，具有 16 位、32 位或 48 位指令格式。

1963 年，CDC 推出了 Cray 设计的 CDC 6600 cite:[cdc6600]，这是 RISC 架构的前身，引入了一个寄存器丰富的加载-存储架构，具有两种长度的指令，15 位和 30 位。后来的 Cray-1 设计使用了非常相似的指令格式，具有 16 位和 32 位指令长度。

1980 年代的初始 RISC ISA 都选择了性能优先于代码大小，这对于工作站环境是合理的，但对于嵌入式系统则不然。因此，ARM 和 MIPS 随后推出了版本，通过提供一种 16 位宽的替代指令集，而不是标准的 32 位宽指令，以实现更小的代码大小。这些压缩 RISC ISA 相对于其起点减少了大约 25%-30% 的代码大小，生成的代码显著小于 80x86。这一结果让一些人感到惊讶，因为他们的直觉是可变长度的 CISC ISA 应该比仅提供 16 位和 32 位格式的 RISC ISA 更小。

由于初始 RISC ISA 没有留下足够的操作码空间来包含这些未计划的压缩指令，因此它们被开发为完整的新 ISA。这意味着编译器需要为不同的压缩 ISA 编写不同的代码生成器。第一代压缩 RISC ISA 扩展（例如 ARM Thumb 和 MIPS16）仅使用固定的 16 位指令大小，这虽然很好的减少了静态代码的大小，但导致动态指令数的增加，从而导致性能低于初始固定宽度的 32 位指令大小。这导致了第二代压缩 RISC ISA 设计的发展，采用具有混合的 16 位和 32 位指令长度（例如 ARM Thumb2、microMIPS、PowerPC VLE），这样性能与纯 32 位指令相似，但显著地节省代码大小。不幸的是，这些不同代的压缩 ISA 彼此不兼容，也不兼容初始的未压缩 ISA，导致文档、实现和软件工具支持的复杂性显著增加。

在常用的 64 位 ISA 中，只有 PowerPC 和 microMIPS 目前支持压缩指令格式。令人惊讶的是，移动平台上最流行的 64 位 ISA（ARM v8）不包括压缩指令格式，尽管静态代码大小和动态指令获取带宽是重要的指标。虽然静态代码大小在较大的系统中不是主要关注点，但在运行商业工作负载的服务器中，指令获取带宽可能是一个主要瓶颈，这些服务器通常具有较大的指令工作集。

受益于 25 年后的视角，RISC-V 设计时支持压缩指令，从一开始就留下足够的操作码空间，使 RVC 可以作为简单扩展添加到基本 ISA 上（以及许多其他扩展）。RVC 的理念是减少嵌入式应用的代码大小，并通过减少指令缓存未命中次数来提高所有应用的性能和能效。Waterman 表明，RVC 获取的指令位数减少了 25%-30%，从而减少了 20%-25% 的指令缓存未命中，或大致相当于将指令缓存大小加倍的性能影响。cite:[waterman-ms]
====

=== 压缩指令格式
((((compressed, formats))))

<<rvc-form>> 显示了九种压缩指令格式。CR、CI 和 CSS 可以使用任何 32 个 RVI 寄存器，但 CIW、CL、CS、CA 和 CB 仅限于其中的 8 个。
<<registers>> 列出了这些常用寄存器，对应于寄存器 `x8` 到 `x15`。请注意，有一个单独的加载和存储指令版本使用堆栈指针作为基地址寄存器，因为保存到堆栈和从堆栈恢复非常普遍，并且它们使用 CI 和 CSS 格式以允许访问所有 32 个数据寄存器。CIW 为 ADDI4SPN 指令提供了一个 8 位立即数。

[NOTE]
====
RISC-V ABI 已更改，使得常用寄存器映射到寄存器 'x8-x15'。这通过使用一组连续自然对齐的寄存器编号来简化了解压缩解码器，并且与仅有 16 个整数寄存器的 RV32E 和 RV64E 基本 ISA 兼容。
====
基于压缩寄存器的浮点加载和存储也分别使用 CL 和 CS 格式，八个寄存器映射到 `f8` 到 `f15`。
((((calling convention, standard))))
[NOTE]
====
_标准 RISC-V 调用约定将最常用的浮点寄存器映射到寄存器 `f8` 到 `f15`，这允许与整数寄存器编号相同的寄存器解压缩解码。_
====
((((register source spcifiers, c-ext))))
这些格式的设计目的是在所有指令中将两个寄存器源说明符的位保持在相同位置，而目标寄存器字段可以移动。当存在完整的 5 位目标寄存器说明符时，它位于与 32 位 RISC-V 编码相同的位置。当立即数是符号扩展时，符号扩展始终来自第 12 位。立即数字段已被打乱，如基本规范中所述，以减少所需的立即数多路复用器数量。
[NOTE]
====
立即数字段在指令格式中被打乱而不是按顺序排列，以便尽可能多的位在每条指令中都处于相同位置，从而简化实现。
====

对于许多 RVC 指令，不允许零值立即数，并且 `x0` 不是有效的 5 位寄存器说明符。这些限制为其他需要较少操作数位的指令腾出编码空间。

//[[cr-register]]
//include::images/wavedrom/cr-register.adoc[]
//.压缩 16 位 RVC 指令
//(((compressed, 16-bit)))

[[rvc-form]]
.压缩 16 位 RVC 指令格式
//[%header]
[float="center",align="center",cols="1a, 2a",frame="none",grid="none"]
|===
|
[%autowidth,float="right",align="right",cols="^,^",frame="none",grid="none",options="noheader"]
!===
!格式 ! 含义
!CR ! 寄存器
!CI ! 立即数
!CSS ! 堆栈相关存储
!CIW ! 宽立即数
!CL ! 加载
!CS ! 存储
!CA ! 算术
!CB ! 分支/算术
!CJ ! 跳转
!===
|
[float="left",align="left",cols="1,1,1,1,1,1,1",options="noheader"]
!===
2+^!15 14 13 12 2+^!11 10 9 8 7 2+^!6 5 4 3 2 ^!1 0
2+^!funct4 2+^!rd/rs1 2+^!rs2 ^!  op
^!funct3 ^!imm 2+^!rd/rs1  2+^!imm ^!  op
^!funct3 3+^!imm  2+^!rs2 ^!  op
^!funct3 4+^!imm ^!rd&#x2032; ^! op
^!funct3 2+^!imm ^!rs1&#x2032; ^!imm ^!rd&#x2032; ^! op
^!funct3 2+^!imm ^!rs1&#x2032; ^! imm ^!rs2&#x2032; ^! op
3+^!funct6 ^!rd&#x2032;/rs1&#x2032; ^!funct2 ^!rs2&#x2032; ^! op
^!funct3 2+^!offset ^!rd&#x2032;/rs1&#x2032; 2+^!offset ^! op
^!funct3 5+^!jump target ^! op
!===
|===

[[registers]]
.CIW、CL、CS、CA 和 CB 格式的三位 _rs1_&#x2032;、_rs2_&#x2032; 和 _rd_&#x2032; 字段指定的寄存器。
//[cols="20%,10%,10%,10%,10%,10%,10%,10%,10%"]
[float="center",align="center",cols="1a, 1a",frame="none",grid="none"]
|===
|
[%autowidth,cols="<",frame="none",grid="none",options="noheader"]
!===
!RVC 寄存器编号
!整数寄存器编号
!整数寄存器 ABI 名称
!浮点寄存器编号
!浮点寄存器 ABI 名称
!===
|

[%autowidth,cols="^,^,^,^,^,^,^,^",options="noheader"]
!===
!`000` !`001` !`010` !`011` !`100` !`101` !`110` !`111`
!`x8` !`x9` !`x10` !`x11` !`x12` !`x13` !`x14`!`x15`
!`s0` !`s1` !`a0` !`a1` !`a2` !`a3` !`a4`!`a5`
!`f8` !`f9` !`f10` !`f11` !`f12` !`f13`!`f14` !`f15`
!`fs0` !`fs1` !`fa0` !`fa1` !`fa2`!`fa3` !`fa4` !`fa5`
!===
|===


=== 加载和存储指令

为了增加 16 位指令的覆盖范围，数据传输指令对以字节为单位的数据大小的零扩展立即数进行缩放：×4 用于字，×8 用于双字，×16 用于四字。

RVC 提供了两种加载和存储变体。一种使用 ABI 堆栈指针 `x2` 作为基地址，并且可以针对任何数据寄存器。另一种可以引用 8 个基地址寄存器之一和 8 个数据寄存器之一。

==== 基于堆栈指针的加载和存储

include::images/wavedrom/c-sp-load-store.adoc[]
[[c-sp-load-store]]
//.基于堆栈指针的加载和存储--这些指令使用 CI 格式。

这些指令使用 CI 格式。

C.LWSP 从内存加载一个 32 位值到寄存器 _rd_。它通过将乘 4 之后的零扩展偏移量与堆栈指针 `x2` 相加来计算有效地址。它扩展为 `lw rd, offset(x2)`。当 _rd_&#x2260;x0 时，C.LWSP 才有效，_rd_=x0 的代码点保留。

C.LDSP 是 RV64C/RV128C 专用指令，从内存加载一个 64 位值到寄存器 _rd_。它通过将乘 8 之后的零扩展偏移量与堆栈指针 `x2` 相加来计算有效地址。它扩展为 `ld rd, offset(x2)`。当 _rd_&#x2260;x0 时，C.LDSP 才有效，_rd_=x0 的代码点保留。

C.LQSP 是 RV128C 专用指令，从内存加载一个 128 位值到寄存器 _rd_。它通过乘 16 之后的零扩展偏移量与堆栈指针 `x2` 相加来计算有效地址。它扩展为 `lq rd, offset(x2)`。当 _rd_&#x2260;x0 时，C.LQSP 才有效，_rd_=x0 的代码点保留。

C.FLWSP 是 RV32FC 专用指令，从内存加载一个单精度浮点值到浮点寄存器 _rd_。它通过将乘 4 之后的零扩展偏移量与堆栈指针 `x2` 相加来计算有效地址。它扩展为 `flw rd, offset(x2)`。

C.FLDSP 是 RV32DC/RV64DC 专用指令，从内存加载一个双精度浮点值到浮点寄存器 _rd_。它通过将乘 8 之后的零扩展偏移量与堆栈指针 `x2` 相加来计算有效地址。它扩展为 `fld rd, offset(x2)`。

include::images/wavedrom/c-sp-load-store-css.adoc[]
[[c-sp-load-store-css]]
//.基于堆栈指针的加载和存储--这些指令使用 CSS 格式。

这些指令使用 CSS 格式。

C.SWSP 将寄存器 _rs2_ 中的 32 位值存储到内存中。它通过将乘 4 之后的零扩展偏移量与堆栈指针 `x2` 相加来计算有效地址。它扩展为 `sw rs2, offset(x2)`。

C.SDSP 是 RV64C/RV128C 专用指令，将寄存器 _rs2_ 中的 64 位值存储到内存中。它通过将乘 8 之后的零扩展偏移量与堆栈指针 `x2` 相加来计算有效地址。它扩展为 `sd rs2, offset(x2)`。

C.SQSP 是 RV128C 专用指令，将寄存器 _rs2_ 中的 128 位值存储到内存中。它通过将乘 16 之后的零扩展偏移量与堆栈指针 `x2` 相加来计算有效地址。它扩展为 `sq rs2, offset(x2)`。

C.FSWSP 是 RV32FC 专用指令，将浮点寄存器 _rs2_ 中的单精度浮点值存储到内存中。它通过将乘 4 之后的零扩展偏移量与堆栈指针 `x2` 相加来计算有效地址。它扩展为 `fsw rs2, offset(x2)`。

C.FSDSP 是 RV32DC/RV64DC 专用指令，将浮点寄存器 _rs2_ 中的双精度浮点值存储到内存中。它通过将乘 8 之后的零扩展偏移量与堆栈指针 `x2` 相加来计算有效地址。它扩展为 `fsd rs2, offset(x2)`。

[NOTE]
====
在函数入口/出口处，寄存器保存/恢复代码占静态代码大小的很大一部分。RVC 中基于堆栈指针的压缩加载和存储操作在减少保存/恢复静态代码大小方面非常有效，能够减少代码大小到原来的二分之一，同时通过减少动态指令带宽来提高性能。

其他 ISA 中常用的一种机制是并行加载指令和并行存储指令，以进一步减少保存/恢复代码大小。我们考虑过将这些指令用于 RISC-V，但注意到以下缺点：

* 这些指令使处理器实现复杂化。
* 对于虚拟内存系统，某些数据访问可能驻留在物理内存中，而某些则不在，这需要一种新的重启机制来处理部分执行的指令。
* 与 RVC 的其他指令不同，没有 IFD 等效的加载多个和存储多个指令。
* 与 RVC 的其他指令不同，编译器必须知道这些指令，以便生成指令并按顺序分配寄存器，以最大化它们被保存和存储的机会，因为它们将按顺序保存和恢复。
* 简单的微架构实现将限制其他指令如何在加载和存储多个指令周围调度，导致潜在的性能损失。
* 顺序寄存器分配的需求可能与 CIW、CL、CS、CA 和 CB 格式中选择的特征寄存器冲突。

此外，通过用子程序调用常见的序言和尾声代码替换序言和尾声代码，可以在软件中实现大部分收益，这种技术在 cite:[waterman-phd] 的第 5.6 节中描述。

虽然架构师完全有理由得出不同的结论，但我们决定省略并行加载指令和并行存储指令，而是使用调用保存/恢复微代码例程的软件方法，以实现最大化的代码尺寸缩减。
====

==== 基于寄存器的加载和存储

[[reg-based-ldnstr]]
include::images/wavedrom/reg-based-ldnstr.adoc[]
//.压缩的基于寄存器的加载和存储--这些指令使用 CL 格式。
(((compressed, register-based load and store)))
这些指令使用 CL 格式。

C.LW 从内存加载一个 32 位值到寄存器 `_rd′_`。它通过将乘 4 之后的零扩展偏移量与寄存器 `_rs1′_` 中的基地址相加来计算有效地址。它扩展为 `lw rd′, offset(rs1′)`。

C.LD 是 RV64C/RV128C 专用指令，从内存加载一个 64 位值到寄存器 `_rd′_`。它通过将乘 8 之后的零扩展偏移量与寄存器 `_rs1′_` 中的基地址相加来计算有效地址。它扩展为 `ld rd′, offset(rs1′)`。

C.LQ 是 RV128C 专用指令，从内存加载一个 128 位值到寄存器 `_rd′_`。它通过将乘 16 之后的零扩展偏移量与寄存器 `_rs1′_` 中的基地址相加来计算有效地址。它扩展为 `lq rd′, offset(rs1′)`。

C.FLW 是 RV32FC 专用指令，从内存加载一个单精度浮点值到浮点寄存器 `_rd′_`。它通过将乘 4 之后的零扩展偏移量与寄存器 `_rs1′_` 中的基地址相加来计算有效地址。它扩展为 `flw rd′, offset(rs1′)`。

C.FLD 是 RV32DC/RV64DC 专用指令，从内存加载一个双精度浮点值到浮点寄存器 `_rd′_`。它通过将乘 8 之后的零扩展偏移量与寄存器 `_rs1′_` 中的基地址相加来计算有效地址。它扩展为 `fld rd′, offset(rs1′)`。

[[c-cs-format-ls]]
include::images/wavedrom/c-cs-format-ls.adoc[]
//.压缩的 CS 格式加载和存储--这些指令使用 CS 格式。
(((compressed, cs-format load and store)))

这些指令使用 CS 格式。

C.SW 将寄存器 `_rs2′_` 中的 32 位值存储到内存中。它通过将乘 4 之后的零扩展偏移量与寄存器 `_rs1′_` 中的基地址相加来计算有效地址。它扩展为 `sw rs2′, offset(rs1′)`。

C.SD 是 RV64C/RV128C 专用指令，将寄存器 `_rs2′_` 中的 64 位值存储到内存中。它通过将乘 8 之后的零扩展偏移量与寄存器 `_rs1′_` 中的基地址相加来计算有效地址。它扩展为 `sd rs2′, offset(rs1′)`。

C.SQ 是 RV128C 专用指令，将寄存器 `_rs2′_` 中的 128 位值存储到内存中。它通过将乘 16 之后的零扩展偏移量与寄存器 `_rs1′_` 中的基地址相加来计算有效地址。它扩展为 `sq rs2′, offset(rs1′)`。

C.FSW 是 RV32FC 专用指令，将浮点寄存器 `_rs2′_` 中的单精度浮点值存储到内存中。它通过将乘 4 之后的零扩展偏移量与寄存器 `_rs1′_` 中的基地址相加来计算有效地址。它扩展为 `fsw rs2′, offset(rs1′)`。

C.FSD 是 RV32DC/RV64DC 专用指令，将浮点寄存器 `_rs2′_` 中的双精度浮点值存储到内存中。它通过将乘 8 之后的零扩展偏移量与寄存器 `_rs1′_` 中的基地址相加来计算有效地址。它扩展为 `fsd rs2′, offset(rs1′)`。

=== 控制转移指令

RVC 提供无条件跳转指令和条件分支指令。与基本 RVI 指令一样，所有 RVC 控制转移指令的偏移量都是 2 字节的倍数。

[[c-cj-format-ls]]
include::images/wavedrom/c-cj-format-ls.adoc[]
//.压缩的 CJ 格式加载和存储--这些指令使用 CJ 格式。
(((compressed, cj-format load and store)))

这些指令使用 CJ 格式。

C.J 执行无条件控制转移。偏移量是符号扩展的，并添加到 `pc` 以形成跳转目标地址。因此，C.J 可以定位 &#177;2 KiB 范围。C.J 扩展为 `jal x0, offset`。

C.JAL 是 RV32C 专用指令，执行与 C.J 相同的操作，但另外将跳转后指令的地址（`pc+2`）写入链接寄存器 `x1`。C.JAL 扩展为 `jal x1, offset`。

[[c-cr-format-ls]]
include::images/wavedrom/c-cr-format-ls.adoc[]
//.压缩的 CR 格式加载和存储--这些指令使用 CR 格式。
(((compressed, cr-format load and store)))

这些指令使用 CR 格式。

C.JR（跳转寄存器）执行无条件控制转移到寄存器 _rs1_ 中的地址。C.JR 扩展为 `jalr x0, 0(rs1)`。当 latexmath:[$\textit{rs1}{\neq}\texttt{x0}$] 时，C.JR 才有效；代码点 latexmath:[$\textit{rs1}{=}\texttt{x0}$] 保留。

C.JALR（跳转并链接寄存器）执行与 C.JR 相同的操作，但另外将跳转后指令的地址（`pc`+2）写入链接寄存器 `x1`。C.JALR 扩展为 `jalr x1, 0(rs1)`。当 latexmath:[$\textit{rs1}{\neq}\texttt{x0}$] 时，C.JALR 才有效；代码点 latexmath:[$\textit{rs1}{=}\texttt{x0}$] 对应于 C.EBREAK 指令。

[TIP]
====
严格来说，C.JALR 并不完全扩展为基本 RVI 指令，因为用于形成链接地址的 PC 增量值是 2 而不是基本 ISA 中的 4，但支持 2 和 4 字节的偏移量对基本微架构来说只是一个非常小的变化。
====

[[c-cb-format-ls]]
include::images/wavedrom/c-cb-format-ls.adoc[]
//.压缩的 CB 格式加载和存储--这些指令使用 CB 格式。
(((compressed, cb-format load and store)))

这些指令使用 CB 格式。

C.BEQZ 执行条件控制转移。偏移量是符号扩展的，并添加到 `pc` 以形成分支目标地址。因此，C.BEQZ 可以定位 &#177;256 B 范围。如果寄存器 _rs1′_ 中的值为零，则 C.BEQZ 进行分支。它扩展为 `beq rs1′, x0, offset`。

C.BNEZ 的定义类似，但如果 _rs1′_ 包含非零值，则进行分支。它扩展为 `bne rs1′, x0, offset`。

=== 整数计算指令

RVC 提供了几条用于整数算术和常量生成的指令。

==== 整数常量生成指令

这两条常量生成指令都使用 CI 指令格式，可以针对任何整数寄存器。

[[c-integer-const-gen]]
include::images/wavedrom/c-integer-const-gen.adoc[]
//.整数常量生成格式。
(((compressed, integer constant generation)))

C.LI 将符号扩展的 6 位立即数 _imm_ 加载到寄存器 _rd_ 中。C.LI 扩展为 `addi rd, x0, imm`。当 `_rd_≠x0` 时，C.LI 才有效；_rd_=x0 的代码点编码为 HINTs。

C.LUI 将非零 6 位立即数字段加载到目标寄存器的第 17-12 位，清除底部 12 位，并将第 17 位符号扩展到目标寄存器的所有更高位。C.LUI 扩展为 `lui rd, imm`。C.LUI 仅在 latexmath:[$\textit{rd}{\neq}{\left\{\texttt{x0},\texttt{x2}\right\}}$] 时有效，并且立即数不等于零。_imm_=0 的代码点保留；_rd_=`x0` 的剩余代码点为 HINTs；_rd_=`x2` 的剩余代码点对应于 C.ADDI16SP 指令。

==== 整数寄存器-立即数操作

这些整数寄存器-立即数操作在 CI 格式中编码，并对整数寄存器和 6 位立即数执行操作。

[[c-integer-register-immediate]]
include::images/wavedrom/c-int-reg-immed.adoc[]
//.整数寄存器-立即数格式。
(((compressed, integer register-immediate)))

C.ADDI 将非零符号扩展的 6 位立即数添加到寄存器 _rd_ 中的值，然后将结果写入 _rd_。C.ADDI 扩展为 `addi rd, rd, imm`。当 `_rd_≠x0` 且 `_imm_≠0` 时，C.ADDI 才有效。_rd_=x0 的代码点编码为 C.NOP 指令；_imm_=0 的剩余代码点编码为 HINTs。

C.ADDIW 是 RV64C/RV128C 专用指令，执行相同的计算，但生成 32 位结果，然后将结果符号扩展到 64 位。C.ADDIW 扩展为 `addiw rd, rd, imm`。对于 C.ADDIW，立即数可以为零，此时对应于 `sext.w rd`。C.ADDIW 仅在 `_rd_≠x0` 时有效；_rd_=x0 的代码点保留。

C.ADDI16SP 与 C.LUI 共享操作码，但目标字段为 `x2`。C.ADDI16SP 将非零符号扩展的 6 位立即数添加到堆栈指针（`sp=x2`）的值中，其中立即数按比例表示 (-512,496) 范围内的 16 的倍数。C.ADDI16SP 用于在过程序言和尾声中调整堆栈指针。它扩展为 `addi x2, x2, nzimm[9:4]`。当 _nzimm_≠0 时，C.ADDI16SP 才有效；_nzimm_=0 的代码点保留。

[NOTE]
====
在标准 RISC-V 调用约定中，堆栈指针 `sp` 始终是 16 字节对齐的。
====

[[c-ciw]]
include::images/wavedrom/c-ciw.adoc[]
//.CIW 格式。
(((compressed, CIW)))

C.ADDI4SPN 是 CIW 格式指令，将零扩展的非零立即数（按 4 缩放）与堆栈指针 `x2` 相加，并将结果写入 `rd′`。此指令用于生成指向堆栈分配变量的指针，并扩展为 `addi rd′, x2, nzuimm[9:2]`。当 _nzuimm_≠0 时，C.ADDI4SPN 才有效；_nzuimm_=0 的代码点保留。

[[c-ci]]
include::images/wavedrom/c-ci.adoc[]
//.CI 格式。
(((compressed, CI)))

C.SLLI 是 CI 格式指令，对寄存器 _rd_ 中的值执行逻辑左移，然后将结果写入 _rd_。移位量编码在 _shamt_ 字段中。对于 RV128C，移位量为零用于编码 64 的移位。C.SLLI 扩展为 `slli rd, rd, shamt[5:0]`，除了 RV128C 中 `shamt=0`，扩展为 `slli rd, rd, 64`。

对于 RV32C，_shamt[5]_ 必须为零；_shamt[5]_ =1 的代码点指定用于自定义扩展。对于 RV32C 和 RV64C，移位量必须为非零；_shamt_=0 的代码点为 HINTs。对于所有基本 ISA，_rd_=x0 的代码点为 HINTs，除了 RV32C 中 _shamt[5]_ =1 的代码点。

[[c-srli-srai]]
include::images/wavedrom/c-srli-srai.adoc[]
//.C-SRLI-SRAI 格式。
(((compressed, C.SRLI, C.SRAI)))

C.SRLI 是 CB 格式指令，对寄存器 _rd′_ 中的值执行逻辑右移，然后将结果写入 _rd′_。移位量编码在 _shamt_ 字段中。对于 RV128C，移位量为零用于编码 64 的移位。此外，移位量对于 RV128C 是符号扩展的，因此合法的移位量为 1-31、64 和 96-127。C.SRLI 扩展为 `srli rd′, rd′, shamt`，除了 RV128C 中 `shamt=0`，扩展为 `srli rd′, rd′, 64`。

对于 RV32C，_shamt[5]_ 必须为零；_shamt[5]_ =1 的代码点指定用于自定义扩展。对于 RV32C 和 RV64C，移位量必须为非零；_shamt_=0 的代码点为 HINTs。

C.SRAI 的定义类似于 C.SRLI，但执行算术右移。C.SRAI 扩展为 `srai rd′, rd′, shamt`。

[NOTE]
====
左移通常比右移更频繁，因为左移常用于缩放地址值。因此，右移分配了较少的编码空间，并放置在所有其他立即数符号扩展的编码象限中。对于 RV128，决定将 6 位移位量立即数也符号扩展。除了减少解码复杂性外，我们认为 96-127 的右移量比 64-95 更有用，以允许提取位于 128 位地址指针高位部分的标签。我们注意到 RV128C 不会与 RV32C 和 RV64C 同时冻结，以便评估 128 位地址空间代码的典型使用情况。
====

[[c-andi]]
include::images/wavedrom/c-andi.adoc[]
//.C.ANDI 格式
(((compressed, C.ANDI)))

C.ANDI 是 CB 格式指令，计算寄存器 _rd′_ 中的值与符号扩展的 6 位立即数的按位与，然后将结果写入 _rd′_。C.ANDI 扩展为 `andi rd′, rd′, imm`。

==== 整数寄存器-寄存器操作

[[c-cr]]
include::images/wavedrom/c-int-reg-to-reg-cr-format.adoc[]
//C.CR 格式
((((compressed. C.CR))))

这些指令使用 CR 格式。

C.MV 将寄存器 _rs2_ 中的值复制到寄存器 _rd_ 中。C.MV 扩展为 `add rd, x0, rs2`。当 `rs2≠x0` 时，C.MV 才有效；`rs2=x0` 的代码点对应于 C.JR 指令。`rs2≠x0` 且 `rd=x0` 的代码点为 HINTs。

[TIP]
====
_C.MV 扩展为与规范的 MV 伪指令不同的指令，后者使用 ADDI。处理 MV 特殊情况的实现，例如使用寄存器重命名硬件，可能会发现将 C.MV 扩展为 MV 而不是 ADD 更方便，尽管硬件成本略有增加。_
====

C.ADD 将寄存器 _rd_ 和 _rs2_ 中的值相加，并将结果写入寄存器 _rd_。C.ADD 扩展为 `add rd, rd, rs2`。当 `rs2≠x0` 时，C.ADD 才有效；`rs2=x0` 的代码点对应于 C.JALR 和 C.EBREAK 指令。`rs2≠x0` 且 rd=x0 的代码点为 HINTs。

[[c-ca]]
include::images/wavedrom/c-int-reg-to-reg-ca-format.adoc[]
//C.CA 格式
((((compressed. C.CA))))

这些指令使用 CA 格式。

`C.AND` 计算寄存器 _rd′_ 和 _rs2′_ 中值的按位与，然后将结果写入寄存器 _rd′_。`C.AND` 扩展为 *`_and rd′, rd′, rs2′_`*。

`C.OR` 计算寄存器 _rd′_ 和 _rs2′_ 中值的按位或，然后将结果写入寄存器 _rd′_。`C.OR` 扩展为 *`_or rd′, rd′, rs2′_`*。

`C.XOR` 计算寄存器 _rd′_ 和 _rs2′_ 中值的按位异或，然后将结果写入寄存器 _rd′_。`C.XOR` 扩展为 *`_xor rd′, rd′, rs2′_`*。

`C.SUB` 将寄存器 _rs2′_ 中的值从寄存器 _rd′_ 中的值中减去，然后将结果写入寄存器 _rd′_。`C.SUB` 扩展为 *`_sub rd′, rd′, rs2′_`*。

`C.ADDW` 是 RV64C/RV128C 专用指令，将寄存器 _rd′_ 和 _rs2′_ 中的值相加，然后将和的低 32 位符号扩展后写入寄存器 _rd′_。`C.ADDW` 扩展为 *`_addw rd′, rd′, rs2′_`*。

`C.SUBW` 是 RV64C/RV128C 专用指令，将寄存器 _rs2′_ 中的值从寄存器 _rd′_ 中的值中减去，然后将差的低 32 位符号扩展后写入寄存器 _rd′_。`C.SUBW` 扩展为 *`_subw rd′, rd′, rs2′_`*。

[NOTE]
====
这组六条指令单独提供的节省不大，但占用的编码空间不多，且实现简单，作为一个整体在静态和动态压缩方面提供了有价值的改进。
====

==== 定义的非法指令

[[c-def-illegal-inst]]
include::images/wavedrom/c-def-illegal-inst.adoc[]
((((compressed. C.DIINST))))

所有位都为零的 16 位指令永久保留为非法指令。

[NOTE]
====
我们保留所有全零指令作为非法指令，以帮助捕获尝试执行全零或不存在的内存空间部分的操作。全零值不应在任何非标准扩展中重新定义。同样，我们保留所有位都设置为 1 的指令（对应于 RISC-V 可变长度编码方案中的非常长的指令）作为非法指令，以捕获在不存在的内存区域中看到的另一种常见值。
====

==== NOP 指令

[[c-nop-instr]]
include::images/wavedrom/c-nop-instr.adoc[]
((((compressed. C.NOPINSTR))))

`C.NOP` 是一种 CI 格式指令，不会更改任何用户可见的状态，除了推进 `pc` 和增加任何适用的性能计数器。`C.NOP` 扩展为 `nop`。当 _imm_=0 时，`C.NOP` 才有效；_imm_≠0 的代码点编码为 HINTs。

==== 断点指令

[[c-breakpoint-instr]]
include::images/wavedrom/c-breakpoint-instr.adoc[]
((((compressed. C.BREAKPOINTINSTR))))

调试器可以使用 `C.EBREAK` 指令，该指令扩展为 `ebreak`，以使控制转移回调试环境。`C.EBREAK` 与 `C.ADD` 指令共享操作码，但 _rd_ 和 _rs2_ 都为零，因此也可以使用 `CR` 格式。

=== 在 LR/SC 序列中使用 C 指令

在支持 C 扩展的实现中，允许在受限 LR/SC 序列中使用描述在 <<sec:lrscseq>> 中的 I 指令的压缩形式。

[NOTE]
====
这意味着任何声称支持 A 和 C 扩展的实现必须确保包含有效 C 指令的 LR/SC 序列最终会完成。
====

[[rvc-hints]]
=== HINT 指令

RVC 编码空间的一部分保留用于微架构 HINTs。与 RV32I 基本 ISA 中的 HINTs 类似（见 <<rv32i-hints>>），这些指令不会修改任何架构状态，除了推进 `pc` 和增加任何适用的性能计数器。对于忽略它们的实现，HINTs 作为无操作执行。

RVC HINTs 编码为不修改架构状态的计算指令，因为 _rd_=`x0`（例如 `C.ADD _x0_, _t0_`），或因为 _rd_ 被覆盖为自身的副本（例如 `C.ADDI _t0_, 0`）。

[NOTE]
====
选择这种 HINT 编码是为了使简单的实现可以完全忽略 HINTs，而是将 HINT 作为常规计算指令执行，恰好不改变架构状态。
====

RVC HINTs 不一定扩展为其 RVI HINT 对应物。例如，`C.ADD` _x0_, _a0_ 可能不会编码为与 `ADD` _x0_, _x0_, _a0_ 相同的 HINT。

[NOTE]
====
不要求 RVC HINT 扩展为 RVI HINT 的主要原因是 HINT 不太可能以与基础计算指令相同的方式压缩。此外，解耦 RVC 和 RVI HINT 映射允许将稀缺的 RVC HINT 空间分配给最流行的 HINT，特别是那些适合宏操作融合的 HINT。
====

<<rvc-t-hints, Table 32>> 列出了所有 RVC HINT 代码点。对于 RV32C，78% 的 HINT 空间保留用于标准 HINTs。剩余的 HINT 空间指定用于自定义 HINTs；在此子空间中不会定义任何标准 HINTs。

[[rvc-t-hints]]
.RVC HINT 指令。
[cols="<,<,>,<",options="header",]
|===
|指令 |约束 |代码点 |用途

|C.NOP |_imm_≠0 |63 .6+.^|_指定用于未来标准使用_

|C.ADDI | _rd_≠`x0`, _imm_=0 |31

|C.LI | _rd_=`x0` |64

|C.LUI | _rd_=`x0`, _imm_≠0 |63

|C.MV | _rd_=`x0`, _rs2_≠`x0` |31

|C.ADD | _rd_=`x0`, _rs2_≠`x0`, _rs2_≠`x2-x5` | 27

|C.ADD | _rd_=`x0`, _rs2_≠`x2-x5` |4|(rs2=x2) C.NTL.P1 (rs2=x3) C.NTL.PALL (rs2=x4) C.NTL.S1 (rs2=x5) C.NTL.ALL

|C.SLLI |_rd_=`x0`, _imm_≠0 |31 (RV32), 63 (RV64/128)  .5+.^|_指定用于自定义使用_

|C.SLLI64 | _rd_=_x0_ |1

|C.SLLI64 | _rd_≠`x0`, RV32 和 RV64 仅 |31

|C.SRLI64 | RV32 和 RV64 仅 |8

|C.SRAI64 | RV32 和 RV64 仅 |8
|===

=== RVC 指令集列表

<<rvcopcodemap>> 显示了 RVC 的主操作码映射。表的每一行对应于编码空间的一个象限。最后一个象限具有两个最低有效位设置，对应于宽于 16 位的指令，包括基本 ISA 中的指令。某些指令仅对某些操作数有效；当无效时，它们标记为 _RES_，表示该操作码保留用于未来的标准扩展；_Custom_ 表示该操作码指定用于自定义扩展；或 _HINT_ 表示该操作码保留用于微架构提示（见 <<rvc-hints, 第 18.7 节>>）。

<<<

[[rvcopcodemap]]
.RVC 操作码映射指令。
[%autowidth,float="center",align="center",cols=">,^,^,^,^,^,^,^,^,^,<]
|===
2+>|inst[15:13] +
inst[1:0] ^.^s|000 ^.^s|001 ^.^s|010 ^.^s|011 ^.^s|100 ^.^s|101 ^.^s|110 ^.^s|111 |

2+>.^|00 .^|ADDI4SPN ^.^|FLD +
FLD +
LQ ^.^| LW ^.^| FLW +
LD +
LD ^.^| _保留_ ^.^| FSD +
FSD +
SQ ^.^| SW ^.^| FSW +
SD +
SD
^.^| RV32 +
RV64 +
RV128

2+>.^|01 ^.^|ADDI ^.^|JAL +
ADDIW +
ADDIW ^.^|LI ^.^|LUI/ADDI16SP ^.^|MISC-ALU ^.^|J ^.^|BEQZ ^.^|BNEZ ^.^|RV32 +
RV64 +
RV128

2+>.^|10 ^.^|SLLI ^.^|FLDSP +
FLDSP +
LQSP ^.^|LWSP ^.^|FLWSP +
LDSP +
LDSP ^.^|J[AL]R/MV/ADD ^.^|FSDSP +
FSDSP +
SQSP ^.^|SWSP ^.^|FSWSP +
SDSP +
SDSP ^.^|RV32 +
RV64 +
RV128

2+>.^|11 9+^|>16b
|===

<<rvc-instr-table0>>、<<rvc-instr-table1>> 和 <<rvc-instr-table2>> 列出了 RVC 指令。

[[rvc-instr-table0]]
.RVC 指令列表，象限 0
include::images/bytefield/rvc-instr-quad0.adoc[]
//include::images/bytefield/rvc-instr-quad0.png[]

[[rvc-instr-table1]]
.RVC 指令列表，象限 1
include::images/bytefield/rvc-instr-quad1.adoc[]
//include::images/bytefield/rvc-instr-quad1.png[]

[[rvc-instr-table2]]
.RVC 指令列表，象限 2
include::images/bytefield/rvc-instr-quad2.adoc[]
//include::images/bytefield/rvc-instr-quad2.png[]
