== "D" 扩展用于双精度浮点，版本 2.2

本章描述了标准的双精度浮点指令集扩展，称为 "D"，并添加了符合 IEEE 754-2008 算术标准的双精度浮点计算指令。D 扩展依赖于基本的单精度指令子集 F。
(((double-precision, floating point)))
(((floating point, double precision)))

=== D 寄存器状态

D 扩展将 32 个浮点寄存器 `f0-f31` 扩展到 64 位（<<fprs>> 中的 FLEN=64）。`f` 寄存器现在可以保存 32 位或 64 位浮点值，如下文 <<nanboxing>> 中所述。

[NOTE]
====
FLEN 可以是 32、64 或 128，具体取决于支持的 F、D 和 Q 扩展。可以支持多达四种不同的浮点精度，包括 H、F、D 和 Q。
====
(((floating-point, supported precisions)))

[[nanboxing]]
=== 较窄值的 NaN Boxing

当支持多种浮点精度时，较窄的 _n_ 位类型的有效值(_n_<FLEN)，通过被称为 NaN-boxing 的过程表示在 FLEN 位 NaN 值的低 _n_ 位中。有效 NaN-boxed 值的高位必须全为 1。有效的 NaN-boxed _n_ 位值因此在视为任何更宽的 _m_ 位值时显示为负静默 NaN（qNaN），_n_ < _m_ &#8804; FLEN。任何将较窄结果写入 'f' 寄存器的操作必须将所有 1 写入最上面的 FLEN-_n_ 位，以产生合法的 NaN-boxed 值。
(((floating-point, requirements)))

[NOTE]
====
软件可能不知道浮点寄存器中存储的数据的当前类型，但必须能够保存和恢复寄存器值，因此必须使用更宽的操作传输较窄值的结果。一个常见的情况是被调用者保存的寄存器，但这一标准约定对于包括可变参数、用户级线程库、虚拟机迁移和调试在内的功能也是可取的。
====

浮点 _n_ 位传输操作将以 IEEE 标准格式保存的外部值移入和移出 `f` 寄存器，包括浮点加载和存储（FL__n__/FS__n__）和浮点移动指令（FMV._n_.X/FMV.X._n_）。将较窄的 _n_ 位(_n_<FLEN)传输移入 `f` 寄存器将创建一个有效的 NaN-boxed 值。将较窄的 _n_ 位传输移出浮点寄存器将传输寄存器的低 _n_ 位，忽略高 FLEN-_n_ 位。

除了前一段描述的传输操作外，所有其他对较窄 __n__ 位操作的浮点操作(_n_<FLEN)都会检查输入操作数是否正确地进行了 NaN-boxing，即所有高位 FLEN-_n_ 位都是 1。如果是，则使用输入的 _n_ 个最低有效位作为输入值，否则输入值将被视为 _n_ 位的规范 NaN。

[TIP]
====
对于本文档的早期版本而言，除了要求较宽的保存和恢复会保留较窄操作数的值，将较窄或较宽操作数的结果输入操作的行为是未被定义的。新的定义消除了这种特定于实现的行为，同时仍然适应浮点单元的非再编码和再编码实现。新的定义还通过在值使用不正确时传播 NaN 来帮助捕捉软件错误。

非再编码实现会在每个浮点操作的输入和输出上将操作数解包和打包为 IEEE 标准格式。对于非再编码实现，NaN-boxing 的成本主要在于检查较窄操作的高位是否表示合法的 NaN-boxed 值，以及将所有 1 写入结果的高位。

再编码实现使用更方便的内部格式来表示浮点值，增加了一个指数位以允许所有值保持规范化。再编码实现的成本主要在于跟踪内部类型和符号位所需的额外标记，但这可以通过在指数字段中内部重新编码 NaN 来完成，而无需添加新的状态位。需要对用于传输值进出再编码格式的流水线进行小的修改，但数据路径和延迟成本是最小的。再编码过程必须处理宽操作数输入次正规值的移位，提取 NaN-boxed 值的过程类似于规范化，除了跳过前导 1 位而不是跳过前导 0 位，从而允许共享数据路径多路复用。
====

[[fld_fsd]]
=== 双精度加载和存储指令

FLD 指令从内存加载一个双精度浮点值到浮点寄存器 _rd_。FSD 将一个双精度值从浮点寄存器存储到内存。
(((floating point, load and store)))

[NOTE]
====
双精度值可能是 NaN-boxed 的单精度值。
====

include::images/wavedrom/double-ls.adoc[]
[[double-ls]]
//.双精度加载和存储

只有在有效地址自然对齐且 XLEN&#8805;64 时，FLD 和 FSD 才能保证原子执行。

FLD 和 FSD 不会修改正在传输的位；特别是，非规范 NaN 的有效负载会被保留。

=== 双精度浮点计算指令

双精度浮点计算指令的定义类似于其单精度对应指令，但操作于双精度操作数并产生双精度结果。

include::images/wavedrom/double-fl-compute.adoc[]
[[fl-compute]]
//.双精度浮点计算

=== 双精度浮点转换和移动指令

浮点到整数和整数到浮点的转换指令在 OP-FP 主操作码空间中编码。FCVT.W.D 或 FCVT.L.D 将浮点寄存器 _rs1_ 中的双精度浮点数分别转换为整数寄存器 _rd_ 中的有符号 32 位或 64 位整数。FCVT.D.W 或 FCVT.D.L 将整数寄存器 _rs1_ 中的 32 位或 64 位有符号整数分别转换为浮点寄存器 _rd_ 中的双精度浮点数。FCVT.WU.D、FCVT.LU.D、FCVT.D.WU 和 FCVT.D.LU 变体转换为或从无符号整数值转换。对于 RV64，FCVT.W[U].D 对 32 位结果进行符号扩展。FCVT.L[U].D 和 FCVT.D.L[U] 是 RV64 专用指令。FCVT._int_.D 的有效输入范围和无效输入的行为与 FCVT._int_.S 相同。
(((floating point, convert and move)))

所有浮点到整数和整数到浮点的转换指令都根据 _rm_ 字段进行舍入。注意 FCVT.D.W[U] 总是产生精确结果，不受舍入模式影响。

include::images/wavedrom/double-fl-convert-mv.adoc[]
[[fl-convert-mv]]
//.双精度浮点转换和移动

双精度到单精度和单精度到双精度的转换指令，FCVT.S.D 和 FCVT.D.S，在 OP-FP 主操作码空间中编码，源和目标都是浮点寄存器。_rs2_ 字段编码源的数据类型，_fmt_ 字段编码目标的数据类型。FCVT.S.D 根据 RM 字段进行舍入；FCVT.D.S 永远不会舍入。
(((double-precision, to single-precision)))
(((single-precision, to double-precision )))

include::images/wavedrom/fcvt-sd-ds.adoc[]
[[fcvt-sd-ds]]
//.双精度 FCVT.S.D 和 FCVT.D.S

浮点到浮点的符号注入指令，FSGNJ.D、FSGNJN.D 和 FSGNJX.D，定义类似于单精度符号注入指令。
//FSGNJ.D、FSGNJN.D 和 FSGNJX.D

include::images/wavedrom/fsjgnjnx-d.adoc[]
//.双精度符号注入

仅对于 XLEN&#8805;64，提供了在浮点寄存器和整数寄存器之间移动位模式的指令。FMV.X.D 将浮点寄存器 _rs1_ 中的双精度值移动到整数寄存器 _rd_ 中的 IEEE 754-2008 标准编码表示。FMV.D.X 将整数寄存器 _rs1_ 中的 IEEE 754-2008 标准编码表示的双精度值移动到浮点寄存器 _rd_ 中。

FMV.X.D 和 FMV.D.X 不会修改正在传输的位；特别地，非规范 NaN 的有效负载会被保留。

include::images/wavedrom/d-xwwx.adoc[]
[[fmvxddx]]
//.双精度浮点移动到 _rd_

[TIP]
====
早期版本的 RISC-V ISA 有一些额外的指令，允许 RV32 系统在 64 位浮点寄存器和整数寄存器的上半部分和下半部分之间进行传输。然而，只有这些指令具有部分寄存器写入功能，在具有重新编码浮点或寄存器重命名的实现中会增加复杂性，实现时需要一个流水线读-修改-写序列。如果要遵循这种模式，扩展到处理 RV32 和 RV64 的四倍精度也需要额外的指令。ISA 被定义为通过让转换和比较将结果写入适当的寄存器堆来减少显式整数-浮点寄存器移动的数量，因此我们预计这些指令的收益将低于其他 ISA。

我们注意到，对于实现 64 位浮点单元（包括融合乘加支持和 64 位浮点加载和存储）的系统，从 32 位到 64 位整数数据路径的边际硬件成本很低，并且可以使用支持 32 位宽地址空间和指针的软件 ABI 来避免静态数据和动态内存流量的增长。
====

=== 双精度浮点比较指令

双精度浮点比较指令的定义类似于其单精度对应指令，但操作于双精度操作数。
(((floating-point, compare)))

include::images/wavedrom/double-fl-compare.adoc[]
[[fl-compare]]
//.双精度浮点比较

=== 双精度浮点分类指令

双精度浮点分类指令 FCLASS.D 的定义类似于其单精度对应指令，但操作于双精度操作数。
(((floating-point, classify)))

include::images/wavedrom/double-fl-class.adoc[]
[[fl-class]]
//.双精度浮点分类
