:stem: latexmath

[[single-float]]
== "F" 扩展：单精度浮点，版本 2.2

本章描述了用于单精度浮点的标准指令集扩展，称为 "F"。该扩展增加了符合 IEEE 754-2008 算术标准的单精度浮点计算指令 cite:[ieee754-2008] 。F 扩展依赖于 "Zicsr" 扩展，用于访问控制状态寄存器。

=== F 寄存器状态

F 扩展新增了 32 个浮点寄存器（f0-f31），每个寄存器宽度为 32 位，并增加了一个浮点控制状态寄存器 fcsr，用于存储浮点单元的运行模式和异常状态。这些附加状态如<<fprs>>所示。我们使用术语 FLEN 来表示 RISC-V ISA 中浮点寄存器的位宽，对于 F 单精度浮点扩展，FLEN=32。大多数浮点指令在浮点寄存器中的数值上执行操作。浮点加载和存储指令用于在浮点寄存器与内存之间传输浮点值，同时也提供了用于在浮点寄存器与整数寄存器之间传输数据的指令。

[TIP]
====
我们曾考虑将整数和浮点数统一存储在同一个寄存器文件中，这样可以简化软件寄存器分配和调用约定，同时减少用户状态的总量。然而，采用分离的寄存器组织方式，能够在相同的指令宽度下增加可访问的寄存器数量，简化宽超标量执行（superscalar issue）所需的寄存器端口设计，支持解耦的浮点单元架构，并且简化内部浮点编码技术的使用。对于分离式寄存器文件架构，编译器支持和调用约定已经非常成熟。此外，在浮点寄存器文件上使用脏位（dirty bits），可以降低上下文切换的开销。
====

[[fprs]]
.RISC-V 标准 F 扩展单精度浮点状态
[cols="<,^,>",options="header",width="50%",align="center",grid="rows"]
|===
| [.small]#FLEN-1#| >| [.small]#0#
3+^| [.small]#f0#
3+^| [.small]#f1#
3+^| [.small]#f2#
3+^| [.small]#f3#
3+^| [.small]#f4#
3+^| [.small]#f5#
3+^| [.small]#f6#
3+^| [.small]#f7#
3+^| [.small]#f8#
3+^| [.small]#f9#
3+^| [.small]#f10#
3+^| [.small]#f11#
3+^| [.small]#f12#
3+^| [.small]#f13#
3+^| [.small]#f14#
3+^| [.small]#f15#
3+^| [.small]#f16#
3+^| [.small]#f17#
3+^| [.small]#f18#
3+^| [.small]#f19#
3+^| [.small]#f20#
3+^| [.small]#f21#
3+^| [.small]#f22#
3+^| [.small]#f23#
3+^| [.small]#f24#
3+^| [.small]#f25#
3+^| [.small]#f26#
3+^| [.small]#f27#
3+^| [.small]#f28#
3+^| [.small]#f29#
3+^| [.small]#f30#
3+^| [.small]#f31#
3+^| [.small]#FLEN#
| [.small]#31#| >| [.small]#0#
3+^|  [.small]#fcsr#
3+^| [.small]#32#
|===

=== 浮点控制状态寄存器

浮点控制和状态寄存器 `fcsr` 是 RISC-V 的控制和状态寄存器（CSR）。它是一个 32 位的可读写寄存器，用于选择浮点算术运算的动态舍入模式，并存储累积的异常标志，如<<fcsr>>所示。

[[fcsr, 浮点控制状态寄存器]]
.浮点控制状态寄存器
include::images/wavedrom/float-csr.adoc[]

`fcsr` 寄存器可以通过 FRCSR 和 FSCSR 指令进行读写，这些指令是基于底层 CSR 访问指令的汇编伪指令。FRCSR 通过将 `fcsr` 复制到整数寄存器 _rd_ 来读取 `fcsr`。FSCSR 通过将 `fcsr` 的原始值复制到整数寄存器 _rd_，然后将从整数寄存器 _rs1_ 获取的新值写入 `fcsr`，从而交换 `fcsr` 的值。

`fcsr` 内的各个字段也可以通过不同的 CSR 地址单独访问，并且为这些访问定义了单独的汇编伪指令。FRRM 指令读取舍入模式字段 `frm`（`fcsr` 的第 7 至 5 位），并将其复制到整数寄存器 _rd_ 的最低三位，其他位填充为零。FSRM 交换 `frm` 的值，它先将 `frm` 的原始值复制到整数寄存器 _rd_，然后将整数寄存器 _rs1_ 的最低三位写入 `frm`。FRFLAGS 和 FSFLAGS 的定义方式与累积异常标志字段 `fflags`（`fcsr` 的第 4 至 0 位）类似。

`fcsr` 的第 31 至 8 位保留用于其他标准扩展。如果这些扩展不存在，实现应忽略对这些位的写入，并在读取时返回零值。标准软件应当保留这些位的内容。

浮点运算可以使用指令中编码的静态舍入模式，或存储在 `frm` 中的动态舍入模式。舍入模式的编码方式如 <<rm>> 所示。当指令的 _rm_ 字段取值为 111 时，表示选择 `frm` 中存储的动态舍入模式。当执行依赖舍入模式的浮点指令时，如果使用了保留的舍入模式，其行为是未定义的，包括静态保留舍入模式（101-110）和动态保留舍入模式（101-111）。某些指令（例如宽度扩展转换指令）虽然具有 _rm_ 字段，但其数学计算实际上不受舍入模式影响。软件应当将这些指令的 _rm_ 字段设置为 RNE (000)，但硬件实现必须按通常方式处理 _rm_ 字段（特别是在解码合法编码与保留编码时）。

[[rm]]
.舍入模式编码
[%autowidth,float="center",align="center",cols="^,^,<",options="header"]
|===
|舍入模式 |助记符 |含义
|000 |RNE |最接近偶数舍入（Round to Nearest, ties to Even）
|001 |RTZ |向零舍入（Round towards Zero）
|010 |RDN |向下舍入（Round Down，朝 latexmath:[$-\infty$] 方向）
|011 |RUP |向上舍入（Round Up，朝 latexmath:[$+\infty$] 方向）
|100 |RMM |最接近最大幅值舍入（Round to Nearest, ties to Max Magnitude）
|101 | |保留供未来使用（_Reserved for future use._）
|110 | |保留供未来使用（_Reserved for future use._）
|111 |DYN |在指令的 _rm_ 字段中，表示选择动态舍入模式；在舍入模式寄存器（`frm`）中，该值是保留的。
|===

[NOTE]
====
C99 语言标准实际上要求提供一个动态舍入模式寄存器。在典型的实现中，对动态舍入模式 CSR 状态的写入会使流水线串行化。静态舍入模式通常用于实现特殊的算术运算，这些运算往往需要频繁切换不同的舍入模式。

已批准版本的 F 规范要求当指令使用了保留的动态舍入模式时，必须引发非法指令异常。这一要求已被弱化为保留（reserved），使其行为与静态舍入模式指令的处理方式一致。当遇到保留的编码时，引发非法指令异常仍然是合法的行为，因此与已批准规范兼容的实现也兼容该弱化版本的规范。
====

累积异常标志（Accrued Exception Flags）表示自该字段上次被软件重置以来，任意浮点算术指令发生的异常情况，如<<bitdef>>所示。基本的 RISC-V ISA 不支持在设置浮点异常标志时触发陷阱。
(((floating-point, exception flag)))

[[bitdef]]
.累积异常标志编码
[%autowidth,float="center",align="center",cols="^,<",options="header",]
|===
| 标志助记符 | 标志含义
| NV | 非法操作（Invalid Operation）
| DZ | 被零除（Divide by Zero）
| OF | 溢出（Overflow）
| UF | 下溢（Underflow）
| NX | 不精确（Inexact）
|===

[NOTE]
====
按照标准的允许范围，我们在 F 扩展中不支持浮点异常的陷阱，而是要求由软件显式检查异常标志。我们曾考虑添加由浮点累积异常标志直接控制的分支指令，但最终选择省略这些指令，以保持 ISA 的简洁性。
====

=== NaN 生成和传播

除非另有说明，如果浮点运算的结果是 NaN，则该 NaN 为规范 NaN（canonical NaN）。规范 NaN 具有正号，并且所有尾数位（significand bits）均为 0，除最高位（又称 quiet bit）外。对于单精度浮点数，规范 NaN 对应的位模式为 0x7fc00000。
(((NaN, generation)))
(((NaN, propagation)))

[TIP]
====
我们曾考虑按照标准的建议传播 NaN 负载（NaN payloads），但这一决定会增加硬件成本。此外，由于该功能在标准中是可选的，因此它无法用于可移植代码。

实现者可以自由地提供一种非标准扩展，在非标准操作模式下启用 NaN 负载传播方案。然而，上述 规范 NaN 方案 必须始终得到支持，并且应作为默认模式。
====
'''
[NOTE]
====
我们要求实现返回标准规定的默认值，以应对异常情况，而无需用户级软件进行任何进一步的干预（与 Alpha ISA 浮点陷阱屏障不同）。我们相信，完全的硬件处理异常情况将变得更加普遍，因此希望避免复杂化用户级 ISA 以优化其他方法。实现始终可以陷入机器模式软件处理程序，以提供异常默认值。

我们要求实现在发生异常情况时，返回标准规定的默认值，而无需用户级软件进行额外干预（不同于 Alpha ISA 的浮点陷阱屏障）。我们认为，完全由硬件处理异常情况将变得越来越普遍，因此我们希望避免为了优化其他方案而使用户级 ISA 变得更加复杂。实现仍然可以触发陷阱到机器模式，由软件处理程序提供异常情况下的默认值。
====

=== 次正规数运算

对次正规数（subnormal numbers）的运算遵循 IEEE 754-2008 标准。
(((operations, subnormal)))

按照 IEEE 标准的术语，微小性（tininess） 在舍入后检测。
(((tininess, handling)))

[NOTE]
====
在舍入后检测微小性可以减少不必要的下溢（underflow）信号。
====

=== 单精度加载和存储指令

浮点加载和存储使用与整数基本 ISA 相同的基址+偏移寻址模式，基址地址存储在寄存器 _rs1_ 中，并使用 12 位有符号字节偏移量。FLW 指令将单精度浮点值从内存加载到浮点寄存器 _rd_ 中。FSW 指令将单精度浮点值从浮点寄存器 _rs2_ 存储到内存中。

include::images/wavedrom/sp-load-store-2.adoc[]
[[sp-ldst]]
// .单精度加载和存储指令

FLW 和 FSW 仅在有效地址自然对齐时才能保证原子性执行。

FLW 和 FSW 在传输数据时不会修改任何位，特别是会完整保留非规范 NaN（Non-Canonical NaN）的有效负载。

如<<ldst>>所述，执行环境决定未对齐的浮点加载和存储是透明处理，还是触发受限或致命的异常。

[[single-float-compute]]
=== 单精度浮点计算指令

具有一个或两个源操作数的浮点算术指令使用 R 型格式，并以 OP-FP 作为主操作码。FADD.S 和 FMUL.S 分别执行 _rs1_ 和 _rs2_ 之间的单精度浮点加法和乘法。FSUB.S 计算 _rs1_ 减去 _rs2_ 的单精度浮点减法。FDIV.S 计算 _rs1_ 除以 _rs2_ 的单精度浮点除法。FSQRT.S 计算 _rs1_ 的平方根。在每种情况下，计算结果都会写入 _rd_ 寄存器。

2 位浮点格式字段 _fmt_ 的编码如 <<fmt>> 所示。对于 F 扩展中的所有指令，该字段的值均设为 _S_ (00)。

[[fmt]]
.格式字段编码
[%autowidth,float="center",align="center",cols="^,^,<",options="header",]
|===
| fmt 字段 | 助记符 | 含义
| 00 | S | 32 位 单精度（Single-Precision）
| 01 | D | 64 位 双精度（Double-Precision）
| 10 | H | 16 位 半精度（Half-Precision）
| 11 | Q | 128 位 四精度（Quad-Precision）
|===

所有执行舍入的浮点运算都可以使用 _rm_ 字段来选择舍入模式，其编码如 <<rm>> 所示。

浮点最小数和最大数指令 FMIN.S 和 FMAX.S 分别将 _rs1_ 和 _rs2_ 中较小或较大的值写入 _rd_。仅针对这些指令，值 latexmath:[$-0.0$] 被认为小于值 latexmath:[$+0.0$]。如果两个输入都是 NaN，则结果为规范 NaN（Canonical NaN）。如果只有一个操作数是 NaN，则结果为非 NaN 的那个操作数。如果输入的是信号 NaN（Signaling NaN），即使计算结果不是 NaN，也会触发无效操作异常标志（Invalid Operation Exception Flag）。

[NOTE]
====
需要注意的是，在 F 扩展 2.2 版本中，FMIN.S 和 FMAX.S 指令被修改为实现 IEEE 754-201x 提议的 minimumNumber 和 maximumNumber 操作，而不再采用 IEEE 754-2008 标准中的 minNum 和 maxNum 操作。这些操作在处理信号 NaN（Signaling NaN）时的行为有所不同。
====

include::images/wavedrom/spfloat.adoc[]
[[spfloat]]
//.单精度浮点计算指令
(((floating point, fused multiply-add)))

浮点融合乘加（Fused Multiply-Add, FMA）指令采用了一种新的标准指令格式。R4 型指令指定三个源寄存器（_rs1_、_rs2_ 和 _rs3_）以及一个目标寄存器（_rd_）。这种格式仅用于浮点融合乘加指令。

FMADD.S 计算 _rs1_ 和 _rs2_ 的乘积，然后加上 _rs3_，并将最终结果写入 _rd_。计算公式： _(rs1latexmath:[$\times$]rs2)latexmath:[$\+$]rs3_。

FMSUB.S 计算 _rs1_ 和 _rs2_ 的乘积，然后减去 _rs3_，并将最终结果写入 _rd_。计算公式： _(rs1latexmath:[$\times$]rs2)latexmath:[$\-$]rs3_。

FNMSUB.S 计算 _rs1_ 和 _rs2_ 的乘积，取反后加上 _rs3_，并将最终结果写入 _rd_。计算公式： _-(rs1latexmath:[$\times$]rs2)latexmath:[$\+$]rs3_。

FNMADD.S 计算 _rs1_ 和 _rs2_ 的乘积，取反后减去 _rs3_，并将最终结果写入 _rd_。计算公式： _-(rs1latexmath:[$\times$]rs2)latexmath:[$\-$]rs3_。

[NOTE]
====  
FNMSUB 和 FNMADD 指令的命名方式可能会让人感到困惑，这与 MIPS-IV 架构中对应指令的命名方式有关。在 MIPS 指令集中，这些指令的定义是对求和结果取反，而 RISC-V 指令的定义则是对乘积取反，因此在当时 MIPS 的命名方式更具合理性。这两种定义在带符号零（signed-zero）结果的处理上存在不同之处。RISC-V 的定义采用了与 x86 和 ARM 的融合乘加（FMA）指令一致的行为，但不幸的是，RISC-V 的  FNMSUB 和 FNMADD 指令的命名方式与 x86 和 ARM 含义相反。
====

include::images/wavedrom/spfloat2.adoc[]
[[fnmaddsub]]
//.F[N]MADD/F[N]MSUB 指令

[NOTE]
====
融合乘加（FMA）指令占用了 32 位指令编码空间的很大一部分。曾考虑过一些替代方案，例如限制 FMA 仅使用动态舍入模式，但静态舍入模式在利用积不舍入的代码中仍然有用。另一种方案是使用 rd 作为 rs3，但这在某些常见序列中需要额外的移动指令。当前的设计仍然保留了 32 位编码空间中的大部分，同时避免了 FMA 指令的非正交性。
====

融合乘加指令在乘数为无穷大（latexmath:[$\infty$]）且被乘数为零时，必须设置无效操作异常标志，即使加数是静默 NaN（quiet NaN）。  

[NOTE]
====
IEEE 754-2008 标准允许，但不强制要求，在执行 latexmath:[$\infty \times 0 +$] 静默 NaN 这一运算时触发无效操作异常。
====

=== 单精度浮点转换和移动指令

浮点数与整数之间的转换指令在 OP-FP 主操作码空间中进行编码。FCVT.W.S 或 FCVT.L.S 将浮点寄存器 _rs1_ 中的浮点数分别转换为有符号 32 位或 64 位整数，并存入整数寄存器 _rd_。FCVT.S.W 或 FCVT.S.L 将整数寄存器 _rs1_ 中的 32 位或 64 位有符号整数分别转换为浮点寄存器 _rd_ 中的浮点数。FCVT.WU.S、FCVT.LU.S、FCVT.S.WU 和 FCVT.S.LU 用于无符号整数值的转换。对于 XLENlatexmath:[$>32$] 的情况，FCVT.W[U].S 会对 32 位结果进行符号扩展，以匹配目标寄存器的位宽。FCVT.L[U].S 和 FCVT.S.L[U] 仅适用于 RV64 指令集。如果舍入后的结果无法用目标格式表示，则会将其截断到最接近的值，并设置无效操作异常标志。<<int_conv>> 表示 FCVT._int_.S 指令的有效输入范围，以及对无效输入的处理方式。
(((floating-point, conversion)))

所有浮点数到整数以及整数到浮点数的转换指令都根据 _rm_ 字段进行舍入。使用 FCVT.S.W _rd_, `x0` 可以将浮点寄存器初始化为浮点正零（+0.0），并且不会触发任何异常标志。

[[int_conv]]
.浮点数到整数转换的范围及无效输入的处理方式
[%autowidth,float="center",align="center",cols="<,>,>,>,>",options="header",]
|===
| |FCVT.W.S |FCVT.WU.S |FCVT.L.S |FCVT.LU.S
|最小有效输入（舍入后） |latexmath:[$-2^{31}$] |0
|latexmath:[$-2^{63}$] |0

|最大有效输入（舍入后） |latexmath:[$2^{31}-1$]
|latexmath:[$2^{32}-1$] |latexmath:[$2^{63}-1$] |latexmath:[$2^{64}-1$]

|超出范围的负输入的输出 |latexmath:[$-2^{31}$] |0
|latexmath:[$-2^{63}$] |0

|latexmath:[$-\infty$] 的输出 |latexmath:[$-2^{31}$] |0
|latexmath:[$-2^{63}$] |0

|超出范围的正输入的输出 |latexmath:[$2^{31}-1$]
|latexmath:[$2^{32}-1$] |latexmath:[$2^{63}-1$] |latexmath:[$2^{64}-1$]

|latexmath:[$+\infty$] 或 NaN 的输出 |latexmath:[$2^{31}-1$]
|latexmath:[$2^{32}-1$] |latexmath:[$2^{63}-1$] |latexmath:[$2^{64}-1$]
|===

所有浮点转换指令在舍入后的结果与操作数值不同且未设置无效操作异常标志时，会设置不精确（Inexact）异常标志。

include::images/wavedrom/spfloat-cn-cmp.adoc[]
[[fcvt]]
//.SP 浮点转换和移动

浮点到浮点的符号注入指令 FSGNJ.S、FSGNJN.S 和 FSGNJX.S 产生的结果从 _rs1_ 中获取除符号位以外的所有位。对于 FSGNJ，结果的符号位是 _rs2_ 的符号位；对于 FSGNJN，结果的符号位是 _rs2_ 符号位的相反位；对于 FSGNJX，符号位是 _rs1_ 和 _rs2_ 符号位的异或。符号注入指令不会设置浮点异常标志，也不会规范化 NaN。注意，FSGNJ.S _rx, ry, ry_ 将 _ry_ 移动到 _rx_（汇编伪指令 FMV.S _rx, ry_）；FSGNJN.S _rx, ry, ry_ 将 _ry_ 的相反数移动到 _rx_（汇编伪指令 FNEG.S _rx, ry_）；FSGNJX.S _rx, ry, ry_ 将 _ry_ 的绝对值移动到 _rx_（汇编伪指令 FABS.S _rx, ry_）。

include::images/wavedrom/spfloat-sign-inj.adoc[]
[[inj]]

[NOTE]
====  
符号注入指令提供了浮点 MV、ABS 和 NEG 操作，并支持其他一些操作，包括 IEEE copySign 操作和超越数学函数库中的符号操作。虽然 MV、ABS 和 NEG 只需要一个寄存器操作数，而 FSGNJ 指令需要两个操作数，但大多数微架构不太可能添加优化，以便从减少寄存器读取次数中受益，因为这些指令相对不常用。即使如此，微架构可以通过检测 FSGNJ 指令的两个源寄存器是否相同，来简化操作，仅读取一个副本。  
====  

提供了将位模式在浮点寄存器和整数寄存器之间移动的指令。FMV.X.W 将浮点寄存器 _rs1_ 中的单精度值（按照 IEEE 754-2008 编码）移动到整数寄存器 _rd_ 的低 32 位。传输过程中的位不会修改，特别是非规范 NaN 的有效负载会被保留。对于 RV64，目标寄存器的高 32 位填充为浮点数符号位的副本。  

FMV.W.X 将按照 IEEE 754-2008 标准编码的单精度值，从整数寄存器 _rs1_ 的低 32 位移动到浮点寄存器 _rd_。传输过程中的位不会修改，特别是非规范 NaN 的有效负载会被保留。

[NOTE]
====
FMV.W.X 和 FMV.X.W 指令之前被称为 FMV.S.X 和 FMV.X.S。使用 W 更符合它们作为一种指令的语义，即移动 32 位数据而不对其进行解释。随着 NaN装箱（NaN-boxing） 定义的清晰，这一点变得更加明确。为了避免影响现有代码，工具将同时支持 W 版和 S 版指令。
====

include::images/wavedrom/spfloat-mv.adoc[]
[[spfloat-mv]]
//.SP 浮点移动

[TIP]
====
基础浮点 ISA 的定义允许实现采用浮点格式的内部重新编码，以便在寄存器中简化次正规值的处理，并可能减少功能单元的延迟。为此，F 扩展避免在浮点寄存器中表示整数值，而是通过定义转换和比较操作，使其直接读写整数寄存器文件。这也减少了许多常见情况下整数寄存器和浮点寄存器之间显式移动数据的需求，从而降低指令数量，并减少混合格式代码序列的关键路径。
====

=== 单精度浮点比较指令

浮点比较指令（FEQ.S、FLT.S、FLE.S）在浮点寄存器之间执行指定的比较（latexmath:[$\mbox{\em rs1} = \mbox{\em rs2}$], latexmath:[$\mbox{\em rs1} < \mbox{\em rs2}$], latexmath:[$\mbox{\em rs1} \leq \mbox{\em rs2}$]），如果条件成立，则向整数寄存器 _rd_ 写入 1，否则写入 0。

FLT.S 和 FLE.S 执行 IEEE 754-2008 标准所称的 _信号_ 比较（signaling comparison），即如果任一输入为 NaN，则设置无效操作异常标志。FEQ.S 执行 _静默_ 比较（quiet comparison），仅当任一输入为信号 NaN 时才会设置无效操作异常标志。对于这三条指令，如果任一操作数为 NaN，则结果为 0。

include::images/wavedrom/spfloat-comp.adoc[]
[[spfloat-comp]]
//.SP 浮点比较

[NOTE]
====
F 扩展提供了 latexmath:[$\leq$] 比较，而基础 ISA 提供的是 latexmath:[$\geq$] 分支比较。由于 latexmath:[$\leq$] 可以由 latexmath:[$\geq$] 合成，反之亦然，这种不一致性不会影响性能，但它仍然是 ISA 设计中一个令人遗憾的不协调之处。
====

=== 单精度浮点分类指令

FCLASS.S 指令检查浮点寄存器 _rs1_ 中的值，并将一个 10 位掩码写入整数寄存器 _rd_，该掩码指示浮点数的类别。掩码的格式如 <<fclass>> 所述。如果属性为真，则 _rd_ 中相应的位将被设置，否则将被清除。_rd_ 中的所有其他位都被清除。注意，_rd_ 中将恰好设置一个位。FCLASS.S 不会设置浮点异常标志。
FCLASS.S 指令检查浮点寄存器 _rs1_ 中的值，并向整数寄存器 _rd_ 写入一个 10 位掩码，该掩码指示浮点数的类别。掩码的格式在 <<fclass>> 中描述。如果某个属性成立，则 _rd_ 中对应的位会被置 1，否则清零。_rd_ 中的所有其他位都会被清零。需要注意的是，_rd_ 中恰好只有一个位会被置 1，FCLASS.S 不会设置浮点异常标志。
(((floating-point, classification)))

include::images/wavedrom/spfloat-classify.adoc[]
[[spfloat-classify]]
//.SP 浮点分类

[[fclass]]
.FCLASS 指令结果的格式
[%autowidth,float="center",align="center",cols="^,<",options="header",]
|===
|_rd_ 位 |含义
|0 |_rs1_ 是 latexmath:[$-\infty$].
|1 |_rs1_ 是负正规数.
|2 |_rs1_ 是负次正规数.
|3 |_rs1_ 是 latexmath:[$-0$].
|4 |_rs1_ 是 latexmath:[$+0$].
|5 |_rs1_ 是正次正规数.
|6 |_rs1_ 是正正规数.
|7 |_rs1_ 是 latexmath:[$+\infty$].
|8 |_rs1_ 是信号 NaN.
|9 |_rs1_ 是静默 NaN.
|===
