:stem: latexmath

[[single-float]]
== "F" 扩展用于单精度浮点，版本 2.2

本章描述了标准的单精度浮点指令集扩展，称为 "F"，并添加了符合 IEEE 754-2008 算术标准的单精度浮点计算指令 cite:[ieee754-2008]。F 扩展依赖于 "Zicsr" 扩展以访问控制和状态寄存器。

=== F 寄存器状态

F 扩展添加了 32 个浮点寄存器，`f0-f31`，每个 32 位宽，以及一个浮点控制和状态寄存器 `fcsr`，其中包含浮点单元的操作模式和异常状态。此附加状态如 <<fprs>> 所示。我们使用术语 FLEN 来描述 RISC-V ISA 中浮点寄存器的宽度，对于 F 单精度浮点扩展，FLEN=32。大多数浮点指令在浮点寄存器堆中的值上操作。浮点加载和存储指令在寄存器和内存之间传输浮点值。还提供了在整数寄存器堆之间传输值的指令。

[TIP]
====
我们考虑过一个统一的寄存器堆，同时用于整数和浮点值，因为这简化了软件寄存器分配和调用约定，并减少了总用户状态。然而，分离的组织增加了在给定指令宽度下可访问的寄存器总数，简化了宽超标量发射时需要提供的寄存器端口，支持解耦的浮点单元架构，并简化了内部浮点编码技术的使用。编译器支持和调用约定对于分离寄存器堆架构是很好理解的，并且使用浮点寄存器堆状态上的脏位可以减少上下文切换的开销。
====

[[fprs]]
.RISC-V 标准 F 扩展单精度浮点状态
[cols="<,^,>",options="header",width="50%",align="center",grid="rows"]
|===
| [.small]#FLEN-1#| >| [.small]#0#
3+^| [.small]#f0#
3+^| [.small]#f1#
3+^| [.small]#f2#
3+^| [.small]#f3#
3+^| [.small]#f4#
3+^| [.small]#f5#
3+^| [.small]#f6#
3+^| [.small]#f7#
3+^| [.small]#f8#
3+^| [.small]#f9#
3+^| [.small]#f10#
3+^| [.small]#f11#
3+^| [.small]#f12#
3+^| [.small]#f13#
3+^| [.small]#f14#
3+^| [.small]#f15#
3+^| [.small]#f16#
3+^| [.small]#f17#
3+^| [.small]#f18#
3+^| [.small]#f19#
3+^| [.small]#f20#
3+^| [.small]#f21#
3+^| [.small]#f22#
3+^| [.small]#f23#
3+^| [.small]#f24#
3+^| [.small]#f25#
3+^| [.small]#f26#
3+^| [.small]#f27#
3+^| [.small]#f28#
3+^| [.small]#f29#
3+^| [.small]#f30#
3+^| [.small]#f31#
3+^| [.small]#FLEN#
| [.small]#31#| >| [.small]#0#
3+^|  [.small]#fcsr#
3+^| [.small]#32#
|===

=== 浮点控制和状态寄存器

浮点控制和状态寄存器 `fcsr` 是一个 RISC-V 控制和状态寄存器 (CSR)。它是一个 32 位读/写寄存器，用于选择浮点算术操作的动态舍入模式，并保存累积的异常标志，如 <<fcsr>> 所示。

[[fcsr, Floating-Point Control and Status Register]]
.浮点控制和状态寄存器
include::images/wavedrom/float-csr.adoc[]

可以使用 FRCSR 和 FSCSR 指令读取和写入 `fcsr` 寄存器，这些是基于底层 CSR 访问指令的汇编伪指令。FRCSR 通过将 `fcsr` 复制到整数寄存器 _rd_ 来读取 `fcsr`。FSCSR 通过将原始值复制到整数寄存器 _rd_，然后将从整数寄存器 _rs1_ 获得的新值写入 `fcsr` 来交换 `fcsr` 中的值。

`fcsr` 中的字段也可以通过不同的 CSR 地址单独访问，并且这些访问有被单独定义的汇编伪指令。FRRM 指令读取舍入模式字段 `frm` (`fcsr` 位 7--5) 并将其复制到整数寄存器 _rd_ 的最低有效三位，其余所有位为零。FSRM 通过将原始值复制到整数寄存器 _rd_，然后将从整数寄存器 _rs1_ 的最低有效三位获得的新值写入 `frm` 来交换 `frm` 中的值。FRFLAGS 和 FSFLAGS 类似地定义用于累积异常标志字段 `fflags` (`fcsr` 位 4--0)。

`fcsr` 的 31 位到 8 位保留用于其他标准扩展。如果这些扩展不存在，实现应忽略对这些位的写入，并在读取时提供零值。标准软件应保留这些位的内容。

浮点操作使用指令中编码的静态舍入模式，或保存在 `frm` 中的动态舍入模式。舍入模式的编码如 <<rm>> 所示。指令的 _rm_ 字段中的值 111 选择保存在 `frm` 中的动态舍入模式。当使用保留的舍入模式执行时，依赖于舍入模式的浮点指令的行为是保留的，包括静态保留舍入模式 (101-110) 和动态保留舍入模式 (101-111)。一些指令，包括宽化转换，具有 _rm_ 字段，但在数学上不受舍入模式影响；软件应将其 _rm_ 字段设置为 RNE (000)，但实现必须像往常一样处理 _rm_ 字段（特别是在解码合法与保留编码方面）。

[[rm]]
.舍入模式编码
[%autowidth,float="center",align="center",cols="^,^,<",options="header"]
|===
|舍入模式 |助记符 |含义
|000 |RNE |舍入到最接近，偶数平分
|001 |RTZ |向零舍入
|010 |RDN |向下舍入（向 latexmath:[$-\infty$]）
|011 |RUP |向上舍入（向 latexmath:[$+\infty$]）
|100 |RMM |舍入到最接近，最大幅度平分
|101 | |_保留供将来使用._
|110 | |_保留供将来使用._
|111 |DYN |在指令的 _rm_ 字段中，选择动态舍入模式；在舍入模式寄存器中，_保留_。
|===

[NOTE]
====
C99 语言标准强制要求提供一个动态舍入模式寄存器。在典型的实现中，对动态舍入模式 CSR 状态的写入将使流水线序列化。静态舍入模式用于实现需要频繁在不同舍入模式之间切换的专用算术操作。

F 规范的正式版本要求在执行具有保留动态舍入模式的指令时引发非法指令异常。这一要求已被弱化为保留，以与静态舍入模式指令的行为相匹配。当遇到保留编码时，引发非法指令异常仍然是有效的行为，因此与正式规范兼容的实现也与弱化规范兼容。
====

累积异常标志指示自字段上次由软件重置以来在任何浮点算术指令上出现的异常情况，如 <<bitdef>> 所示。基本的 RISC-V ISA 不支持在设置浮点异常标志时生成陷阱。
(((floating-point, exception flag)))

[[bitdef]]
.累积异常标志编码
[%autowidth,float="center",align="center",cols="^,<",options="header",]
|===
|标志助记符 |标志含义
|NV |无效操作
|DZ |除以零
|OF |溢出
|UF |下溢
|NX |不精确
|===

[NOTE]
====
如标准所允许，我们在 F 扩展中不支持浮点异常的陷阱，而是要求在软件中显式检查标志。我们考虑过添加直接由浮点累积异常标志内容控制的分支，但最终选择省略这些指令以保持 ISA 的简单性。
====

=== NaN 生成和传播

除非另有说明，否则如果浮点操作的结果是 NaN，则它是规范 NaN。规范 NaN 具有正号，所有有效位都清除，除了 MSB，即安静位。对于单精度浮点，这对应于数值 `0x7fc00000`。
(((NaN, generation)))
(((NaN, propagation)))

[TIP]
====
我们考虑了按照标准推荐传播 NaN 负载，但这一决定会增加硬件成本。此外，由于此功能在标准中是可选的，因此不能在可移植代码中使用。

实现者可以自由提供 NaN 负载传播方案，作为由非标准操作模式启用的非标准扩展。然而，上述规范 NaN 方案必须始终得到支持，并且应作为默认模式。
====
'''
[NOTE]
====
我们要求实现返回标准规定的默认值，以应对异常情况，而无需用户级软件进行任何进一步的干预（与 Alpha ISA 浮点陷阱屏障不同）。我们相信，完全的硬件处理异常情况将变得更加普遍，因此希望避免复杂化用户级 ISA 以优化其他方法。实现始终可以陷入机器模式软件处理程序，以提供异常默认值。
====

=== 次正规算术

次正规数的操作按照 IEEE 754-2008 标准处理。
(((operations, subnormal)))

按照 IEEE 标准，微小性(tininess)在舍入后检测。
(((tininess, handling)))

[NOTE]
====
在舍入后检测微小性会导致更少的虚假下溢信号。
====

=== 单精度加载和存储指令

浮点加载和存储使用与整数基本 ISA 相同的基址+偏移寻址模式，基址在寄存器 _rs1_ 中，12 位有符号字节偏移。FLW 指令将单精度浮点值从内存加载到浮点寄存器 _rd_ 中。FSW 将单精度值从浮点寄存器 _rs2_ 存储到内存中。

include::images/wavedrom/sp-load-store-2.adoc[]
[[sp-ldst]]
//.SP 加载和存储

只有在有效地址自然对齐时，FLW 和 FSW 才能保证原子执行。

FLW 和 FSW 不会修改正在传输的位；特别是，非规范 NaN 的有效负载会被保留。

如 <<ldst>> 中所述，执行环境定义了是否无形地处理未对齐的浮点加载和存储，或者引发包含或致命的陷阱。

[[single-float-compute]]
=== 单精度浮点计算指令

具有一个或两个源操作数的浮点算术指令使用 OP-FP 主操作码的 R 型格式。FADD.S 和 FMUL.S 分别执行 _rs1_ 和 _rs2_ 之间的单精度浮点加法和乘法。FSUB.S 执行 _rs1_ 减去 _rs2_ 的单精度浮点减法。FDIV.S 执行 _rs1_ 除以 _rs2_ 的单精度浮点除法。FSQRT.S 计算 _rs1_ 的平方根。在每种情况下，结果都写入 _rd_。

浮点格式字段 _fmt_ 的 2 位编码如 <<fmt>> 所示。对于 F 扩展中的所有指令，它被设置为 _S_ (00)。

[[fmt]]
.格式字段编码
[%autowidth,float="center",align="center",cols="^,^,<",options="header",]
|===
|_fmt_ 字段 |助记符 |含义
|00 |S |32 位单精度
|01 |D |64 位双精度
|10 |H |16 位半精度
|11 |Q |128 位四精度
|===

所有执行舍入的浮点操作都可以使用 _rm_ 字段选择舍入模式，编码如 <<rm>> 所示。

浮点最小数和最大数指令 FMIN.S 和 FMAX.S 分别将 _rs1_ 和 _rs2_ 中较小或较大的值写入 _rd_。仅对于这些指令，值 latexmath:[$-0.0$] 被认为小于值 latexmath:[$+0.0$]。如果两个输入都是 NaN，则结果是规范 NaN。如果只有一个操作数是 NaN，则结果是非 NaN 操作数。信号 NaN 输入会设置无效操作异常标志，即使结果不是 NaN。

[NOTE]
====
请注意，在 F 扩展的 2.2 版本中，FMIN.S 和 FMAX.S 指令被修改为实现提议的 IEEE 754-201x minimumNumber 和 maximumNumber 操作，而不是 IEEE 754-2008 minNum 和 maxNum 操作。这些操作在处理信号 NaN 时有所不同。
====

include::images/wavedrom/spfloat.adoc[]
[[spfloat]]
//.单精度浮点计算指令
(((floating point, fused multiply-add)))

浮点融合乘加指令需要一种新的标准指令格式。R4 型指令指定三个源寄存器 (_rs1_, _rs2_ 和 _rs3_) 和一个目标寄存器 (_rd_)。此格式仅用于浮点融合乘加指令。

FMADD.S 将 _rs1_ 和 _rs2_ 中的值相乘，加上 _rs3_ 中的值，并将最终结果写入 _rd_。FMADD.S 计算 _(rs1latexmath:[$\times$]rs2)latexmath:[$\+$]rs3_。

FMSUB.S 将 _rs1_ 和 _rs2_ 中的值相乘，减去 _rs3_ 中的值，并将最终结果写入 _rd_。FMSUB.S 计算 _(rs1latexmath:[$\times$]rs2)latexmath:[$\-$]rs3_。

FNMSUB.S 将 _rs1_ 和 _rs2_ 中的值相乘，对得到的积取反后，加上 _rs3_ 中的值，并将最终结果写入 _rd_。FNMSUB.S 计算 _-(rs1latexmath:[$\times$]rs2)latexmath:[$\+$]rs3_。

FNMADD.S 将 _rs1_ 和 _rs2_ 中的值相乘，对得到的积取反后，减去 _rs3_ 中的值，并将最终结果写入 _rd_。FNMADD.S 计算 _-(rs1latexmath:[$\times$]rs2)latexmath:[$\-$]rs3_。

[NOTE]
====
FNMSUB 和 FNMADD 指令的命名是反直觉的，这是由于 MIPS-IV 中相应指令的命名。MIPS 指令被定义为对和取反，而不是像 RISC-V 指令那样对积取反，因此当时的命名方案更为合理。这两个定义在有符号零结果方面有所不同。RISC-V 定义匹配 x86 和 ARM 的融合乘加指令的行为，但不幸的是，RISC-V 的 FNMSUB 和 FNMADD 指令名称与 x86 和 ARM 相反。
====

include::images/wavedrom/spfloat2.adoc[]
[[fnmaddsub]]
//.F[N]MADD/F[N]MSUB 指令

[NOTE]
====
融合乘加 (FMA) 指令占用了很大一部分 32 位指令编码空间。考虑的一些替代方案是限制 FMA 仅使用动态舍入模式，但静态舍入模式在利用缺乏积舍入的代码中很有用。另一种替代方案是使用 rd 提供 rs3，但这在某些常见序列中需要额外的移动指令。当前设计仍然保留了大部分 32 位编码空间，同时避免了 FMA 的非正交性。
====

融合乘加指令必须在乘数为 latexmath:[$\infty$] 和零时设置无效操作异常标志，即使加数是安静 NaN。

[NOTE]
====
IEEE 754-2008 标准允许但不要求在操作 latexmath:[$\infty\times 0\ +$]安静 NaN 时引发无效异常。
====

=== 单精度浮点转换和移动指令

浮点到整数和整数到浮点的转换指令在 OP-FP 主操作码空间中编码。FCVT.W.S 或 FCVT.L.S 将浮点寄存器 _rs1_ 中的浮点数分别转换为整数寄存器 _rd_ 中的有符号 32 位或 64 位整数。FCVT.S.W 或 FCVT.S.L 将整数寄存器 _rs1_ 中的 32 位或 64 位有符号整数分别转换为浮点寄存器 _rd_ 中的浮点数。FCVT.WU.S、FCVT.LU.S、FCVT.S.WU 和 FCVT.S.LU 变体转换为或从无符号整数值转换。对于 XLENlatexmath:[$>32$]，FCVT.W[U].S 将 32 位结果符号扩展到目标寄存器宽度。FCVT.L[U].S 和 FCVT.S.L[U] 是 RV64 专用指令。如果舍入结果在目标格式中不可表示，则将其剪裁到最近的值并设置无效标志。<<int_conv>> 给出了 FCVT._int_.S 的有效输入范围及其对无效输入的行为。
(((floating-point, conversion)))

所有浮点到整数和整数到浮点的转换指令都根据 _rm_ 字段进行舍入。可以使用 FCVT.S.W _rd_, `x0` 将浮点寄存器初始化为浮点正零，这将永远不会设置任何异常标志。

[[int_conv]]
.浮点到整数转换的域及其对无效输入的行为
[%autowidth,float="center",align="center",cols="<,>,>,>,>",options="header",]
|===
| |FCVT.W.S |FCVT.WU.S |FCVT.L.S |FCVT.LU.S
|舍入后最小有效输入 |latexmath:[$-2^{31}$] |0
|latexmath:[$-2^{63}$] |0

|舍入后最大有效输入 |latexmath:[$2^{31}-1$]
|latexmath:[$2^{32}-1$] |latexmath:[$2^{63}-1$] |latexmath:[$2^{64}-1$]

|超出范围的负输入的输出 |latexmath:[$-2^{31}$] |0
|latexmath:[$-2^{63}$] |0

|latexmath:[$-\infty$] 的输出 |latexmath:[$-2^{31}$] |0
|latexmath:[$-2^{63}$] |0

|超出范围的正输入的输出 |latexmath:[$2^{31}-1$]
|latexmath:[$2^{32}-1$] |latexmath:[$2^{63}-1$] |latexmath:[$2^{64}-1$]

|latexmath:[$+\infty$] 或 NaN 的输出 |latexmath:[$2^{31}-1$]
|latexmath:[$2^{32}-1$] |latexmath:[$2^{63}-1$] |latexmath:[$2^{64}-1$]
|===

所有浮点转换指令如果舍入结果与操作数值不同且未设置无效异常标志，则设置不精确异常标志。

include::images/wavedrom/spfloat-cn-cmp.adoc[]
[[fcvt]]
//.SP 浮点转换和移动

浮点到浮点的符号注入指令 FSGNJ.S、FSGNJN.S 和 FSGNJX.S 产生的结果从 _rs1_ 中获取除符号位以外的所有位。对于 FSGNJ，结果的符号位是 _rs2_ 的符号位；对于 FSGNJN，结果的符号位是 _rs2_ 符号位的相反位；对于 FSGNJX，符号位是 _rs1_ 和 _rs2_ 符号位的异或。符号注入指令不会设置浮点异常标志，也不会规范化 NaN。注意，FSGNJ.S _rx, ry, ry_ 将 _ry_ 移动到 _rx_（汇编伪指令 FMV.S _rx, ry_）；FSGNJN.S _rx, ry, ry_ 将 _ry_ 的相反数移动到 _rx_（汇编伪指令 FNEG.S _rx, ry_）；FSGNJX.S _rx, ry, ry_ 将 _ry_ 的绝对值移动到 _rx_（汇编伪指令 FABS.S _rx, ry_）。

include::images/wavedrom/spfloat-sign-inj.adoc[]
[[inj]]

[NOTE]
====
符号注入指令提供浮点 MV、ABS 和 NEG，以及支持一些其他操作，包括 IEEE copySign 操作和超越数学函数库中的符号操作。尽管 MV、ABS 和 NEG 只需要一个寄存器操作数，而 FSGNJ 指令需要两个，但大多数微架构不太可能添加优化以从这些相对不频繁的指令中受益。即使在这种情况下，微架构也可以简单地检测 FSGNJ 指令的两个源寄存器是否相同，并且只读取一个副本。
====

提供了在浮点寄存器和整数寄存器之间移动位模式的指令。FMV.X.W 将浮点寄存器 _rs1_ 中以 IEEE 754-2008 编码表示的单精度值移动到整数寄存器 _rd_ 的低 32 位。传输中的位不会被修改，特别是非规范 NaN 的有效负载会被保留。对于 RV64，目标寄存器的高 32 位填充为浮点数符号位的副本。

FMV.W.X 将整数寄存器 _rs1_ 的低 32 位中以 IEEE 754-2008 标准编码表示的单精度值移动到浮点寄存器 _rd_。传输中的位不会被修改，特别是非规范 NaN 的有效负载会被保留。

[NOTE]
====
FMV.W.X 和 FMV.X.W 指令以前分别称为 FMV.S.X 和 FMV.X.S。使用 W 更符合它们的语义，因为它们是移动 32 位而不解释它们的指令。在定义 NaN-boxing 后，这一点变得更加清晰。为了避免干扰现有代码，工具将同时支持 W 和 S 版本。
====

include::images/wavedrom/spfloat-mv.adoc[]
[[spfloat-mv]]
//.SP 浮点移动

[TIP]
====
基本浮点 ISA 的定义允许实现采用浮点格式在寄存器中的内部重新编码，以简化处理次正规值并可能减少功能单元延迟。为此，F 扩展避免在浮点寄存器中表示整数值，而是定义了直接读写整数寄存器文件的转换和比较操作。这也消除了许多显式在整数和浮点寄存器之间移动的常见情况，减少了常见混合格式代码序列的指令数和关键路径。
====

=== 单精度浮点比较指令

浮点比较指令（FEQ.S、FLT.S、FLE.S）在浮点寄存器之间执行指定的比较（latexmath:[$\mbox{\em rs1} = \mbox{\em rs2}$]，latexmath:[$\mbox{\em rs1} < \mbox{\em rs2}$]，latexmath:[$\mbox{\em rs1} \leq \mbox{\em rs2}$]），如果条件成立，则将 1 写入整数寄存器 _rd_，否则写入 0。

FLT.S 和 FLE.S 执行 IEEE 754-2008 标准所称的 _信号_ 比较：即，如果任一输入为 NaN，则设置无效操作异常标志。FEQ.S 执行 _安静_ 比较：仅当任一输入为信号 NaN 时才设置无效操作异常标志。对于这三个指令，如果任一操作数为 NaN，则结果为 0。

include::images/wavedrom/spfloat-comp.adoc[]
[[spfloat-comp]]
//.SP 浮点比较

[NOTE]
====
F 扩展提供 latexmath:[$\leq$] 比较，而基本 ISA 提供 latexmath:[$\geq$] 分支比较。因为 latexmath:[$\leq$] 可以由 latexmath:[$\geq$] 合成，反之亦然，这种不一致性没有性能影响，但它仍然是 ISA 中一个不幸的不一致之处。
====

=== 单精度浮点分类指令

FCLASS.S 指令检查浮点寄存器 _rs1_ 中的值，并将一个 10 位掩码写入整数寄存器 _rd_，该掩码指示浮点数的类别。掩码的格式如 <<fclass>> 所述。如果属性为真，则 _rd_ 中相应的位将被设置，否则将被清除。_rd_ 中的所有其他位都被清除。注意，_rd_ 中将恰好设置一个位。FCLASS.S 不会设置浮点异常标志。
(((floating-point, classification)))

include::images/wavedrom/spfloat-classify.adoc[]
[[spfloat-classify]]
//.SP 浮点分类

[[fclass]]
.FCLASS 指令结果的格式
[%autowidth,float="center",align="center",cols="^,<",options="header",]
|===
|_rd_ 位 |含义
|0 |_rs1_ 是 latexmath:[$-\infty$].
|1 |_rs1_ 是负正规数.
|2 |_rs1_ 是负次正规数.
|3 |_rs1_ 是 latexmath:[$-0$].
|4 |_rs1_ 是 latexmath:[$+0$].
|5 |_rs1_ 是正次正规数.
|6 |_rs1_ 是正正规数.
|7 |_rs1_ 是 latexmath:[$+\infty$].
|8 |_rs1_ 是信号 NaN.
|9 |_rs1_ 是安静 NaN.
|===
