[[history]]
== 历史与致谢

=== “为什么开发新的 ISA？”——来自伯克利小组的理由

我们开发 RISC-V 是为了满足我们在研究和教育中的需求，我们小组特别关注研究理念的实际硬件实现（自本规范的第一版以来，我们已经完成了十一种不同的 RISC-V 芯片制造），并为学生提供实际的实现以在课堂上探索（RISC-V 处理器 RTL 设计已在伯克利的多个本科和研究生课程中使用）。在我们当前的研究中，我们特别关注由于传统晶体管缩放的终结而导致的向专业化和异构加速器的转变。我们希望有一个高度灵活和可扩展的基础 ISA 来构建我们的研究工作。

我们经常被问到的一个问题是“为什么开发新的 ISA？”使用现有商业 ISA 的最大明显好处是可以利用广泛支持的软件生态系统，包括开发工具和移植的应用程序，这可以在研究和教学中发挥作用。其他好处包括大量文档和教程示例的存在。然而，我们使用商业指令集进行研究和教学的经验表明，这些好处在实践中较小，并且不足以抵消其缺点：

* *商业 ISA 是专有的。* 除了 SPARC V8 是一个开放的 IEEE 标准 cite:[sparcieee1994] 外，大多数商业 ISA 的所有者都严格保护其知识产权，并不欢迎自由可用的竞争性实现。这对仅使用软件模拟器的学术研究和教学来说问题较小，但对希望共享实际 RTL 实现的小组来说是一个主要问题。对于不希望信任少数商业 ISA 实现来源但被禁止创建自己的洁净室实现的实体来说，这也是一个主要问题。我们不能保证所有 RISC-V 实现都不会侵犯第三方专利，但我们可以保证我们不会试图起诉 RISC-V 实现者。
* *商业 ISA 仅在某些市场领域流行。* 在撰写本文时，最明显的例子是 ARM 架构在服务器领域支持不佳，而 Intel x86 架构（或几乎所有其他架构）在移动领域支持不佳，尽管 Intel 和 ARM 都试图进入对方的市场领域。另一个例子是 ARC 和 Tensilica，它们提供可扩展的内核，但专注于嵌入式领域。这种市场细分削弱了支持特定商业 ISA 的好处，因为在实践中，软件生态系统仅存在于某些领域，而必须为其他领域构建。
* *商业 ISA 迭起兴衰。* 以前的研究基础设施是围绕不再流行（SPARC，MIPS）或甚至不再生产（Alpha）的商业 ISA 构建的。这些失去了活跃的软件生态系统的好处，并且围绕 ISA 和支持工具的知识产权问题干扰了相关第三方继续支持 ISA 的能力。一个开放的 ISA 也可能失去流行，但任何相关方都可以继续使用和开发生态系统。
* *流行的商业 ISA 很复杂。* 主流商业 ISA（x86 和 ARM）在硬件中实现以支持常见软件堆栈和操作系统的程度上都非常复杂。更糟糕的是，几乎所有的复杂性都是由于糟糕或至少过时的 ISA 设计决策，而不是那些真正提高效率的功能。
* *仅有商业 ISA 不足以启动应用程序。* 即使我们花费精力实现一个商业 ISA，这也不足以运行现有的该 ISA 应用程序。大多数应用程序需要完整的 ABI（应用程序二进制接口）才能运行，而不仅仅是用户级 ISA。大多数 ABI 依赖于库，而库又依赖于操作系统支持。要运行现有的操作系统，需要实现操作系统期望的监督级 ISA 和设备接口。这些通常比用户级 ISA 规定得少得多且实现起来复杂得多。
* *流行的商业 ISA 不是为可扩展性设计的。* 主流商业 ISA 并不是特别为可扩展性设计的，因此随着指令集的增长，它们增加了相当大的指令编码复杂性。像 Tensilica（被 Cadence 收购）和 ARC（被 Synopsys 收购）这样的公司已经围绕可扩展性构建了 ISA 和工具链，但它们专注于嵌入式应用程序而不是通用计算系统。
* *修改后的商业 ISA 是一个新的 ISA。* 我们的主要目标之一是支持架构研究，包括主要的 ISA 扩展。即使是小的扩展也会削弱使用标准 ISA 的好处，因为编译器必须修改，应用程序必须从源代码重新构建以使用扩展。引入新架构状态的较大扩展还需要对操作系统进行修改。最终，修改后的商业 ISA 成为一个新的 ISA，但带来了基础 ISA 的所有遗留问题。

我们的立场是，ISA 可能是计算系统中最重要的接口，没有理由认为这样一个重要的接口应该是专有的。主流商业 ISA 基于 30 多年前已经广为人知的指令集概念。软件开发人员应该能够针对开放标准硬件目标，商业处理器设计人员应该在实现质量上竞争。

我们远不是第一个考虑适合硬件实现的开放 ISA 设计的人。我们还考虑了其他现有的开放 ISA 设计，其中最接近我们目标的是 OpenRISC 架构 cite:[openriscarch]。由于几个技术原因，我们决定不采用 OpenRISC ISA：

* OpenRISC 有条件码和分支延迟槽，这使得高性能实现变得复杂。
* OpenRISC 使用固定的 32 位编码和 16 位立即数，这排除了更密集的指令编码并限制了 ISA 后续扩展的空间。
* OpenRISC 不支持 2008 年修订的 IEEE 754 浮点标准。
* 当我们开始时，OpenRISC 64 位设计尚未完成。

从头开始设计，我们可以设计一个满足我们所有目标的 ISA，尽管当然，这比我们最初计划的要花费更多的精力。我们现在已经投入了大量精力来建立 RISC-V ISA 基础设施，包括文档、编译器工具链、操作系统移植、参考 ISA 模拟器、FPGA 实现、高效 ASIC 实现、架构测试套件和教学材料。自本手册的最后一版以来，RISC-V ISA 在学术界和工业界得到了广泛应用，我们创建了非营利性 RISC-V 基金会来保护和推广该标准。RISC-V 基金会网站 https://riscv.org 包含有关基金会成员和使用 RISC-V 的各种开源项目的最新信息。

=== ISA 手册 1.0 版的历史

RISC-V ISA 和指令集手册建立在几个早期项目的基础上。监督级机器的几个方面和手册的整体格式可以追溯到 1992 年在 UC Berkeley 和 ICSI 开始的 T0（Torrent-0）矢量微处理器项目。T0 是基于 MIPS-II ISA 的矢量处理器，Krste Asanović 是主要架构师和 RTL 设计师，Brian Kingsbury 和 Bertrand Irrisou 是主要的 VLSI 实现者。ICSI 的 David Johnson 是 T0 ISA 设计的主要贡献者，特别是监督模式，以及手册文本。John Hauser 也对 T0 ISA 设计提供了大量反馈。

2000 年在 MIT 开始的 Scale（低能耗软件控制架构）项目建立在 T0 项目基础设施之上，改进了监督级接口，并通过取消分支延迟槽远离 MIPS 标量 ISA。Ronny Krashinsky 和 Christopher Batten 是 MIT Scale 矢量线程处理器的主要架构师，而 Mark Hampton 将基于 GCC 的编译器基础设施和工具移植到 Scale。

T0 MIPS 标量处理器规范（MIPS-6371）的一个轻微编辑版本在 2002 年秋季学期的新版本 MIT 6.371 VLSI 系统导论课程中用于教学，Chris Terman 和 Krste Asanović 是讲师。Chris Terman 为课程贡献了大部分实验材料（没有助教！）。6.371 课程演变为 2005 年春季由 Arvind 和 Krste Asanović 教授的试验课程 6.884 复杂数字设计课程，并成为常规春季课程 6.375。一个基于 Scale MIPS 的标量 ISA 的简化版本，名为 SMIPS，在 6.884/6.375 中使用。Christopher Batten 是这些课程的早期助教，并围绕 SMIPS ISA 开发了大量文档和实验材料。助教 Yunsup Lee 将这些 SMIPS 实验材料适应并增强，用于 2009 年秋季由 John Wawrzynek、Krste Asanović 和 John Lazzaro 教授的 UC Berkeley CS250 VLSI 系统设计课程。

Maven（可塑矢量线程引擎阵列）项目是第二代矢量线程架构。其设计由 Christopher Batten 在 2007 年夏季作为 UC Berkeley 的交换学者时领导。来自日立的访问工业研究员 Hidetaka Aoki 对早期 Maven ISA 和微架构设计提供了大量反馈。Maven 基础设施基于 Scale 基础设施，但 Maven ISA 进一步远离 Scale 中定义的 MIPS ISA 变体，具有统一的浮点和整数寄存器文件。Maven 旨在支持替代数据并行加速器的实验。Yunsup Lee 是各种 Maven 矢量单元的主要实现者，而 Rimas Avižienis 是各种 Maven 标量单元的主要实现者。Yunsup Lee 和 Christopher Batten 将 GCC 移植到新的 Maven ISA。Christopher Celio 提供了 Maven 的传统矢量指令集（“Flood”）变体的初始定义。

基于所有这些先前项目的经验，RISC-V ISA 定义于 2010 年夏季开始，主要设计者是 Andrew Waterman、Yunsup Lee、Krste Asanović 和 David Patterson。RISC-V 32 位指令子集的初始版本在 2010 年秋季的 UC Berkeley CS250 VLSI 系统设计课程中使用，Yunsup Lee 是助教。RISC-V 是对早期 MIPS 启发设计的彻底突破。John Hauser 对浮点 ISA 定义做出了贡献，包括符号注入指令和允许浮点值内部重新编码的寄存器编码方案。

=== ISA 手册 2.0 版的历史

已经完成了多个 RISC-V 处理器的实现，包括几次硅片制造，如 <<silicon, 制造的 RISC-V 测试芯片表>> 所示。

[[silicon]]
[%autowidth,float="center",align="center",cols="^,^,^,^",options="header",]
|===
|名称 |流片日期 |工艺 |ISA
|Raven-1 |2011 年 5 月 29 日 |ST 28nm FDSOI |RV64G1_Xhwacha1
|EOS14 |2012 年 4 月 1 日 |IBM 45nm SOI |RV64G1p1_Xhwacha2
|EOS16 |2012 年 8 月 17 日 |IBM 45nm SOI |RV64G1p1_Xhwacha2
|Raven-2 |2012 年 8 月 22 日 |ST 28nm FDSOI |RV64G1p1_Xhwacha2
|EOS18 |2013 年 2 月 6 日 |IBM 45nm SOI |RV64G1p1_Xhwacha2
|EOS20 |2013 年 7 月 3 日 |IBM 45nm SOI |RV64G1p99_Xhwacha2
|Raven-3 |2013 年 9 月 26 日 |ST 28nm SOI |RV64G1p99_Xhwacha2
|EOS22 |2014 年 3 月 7 日 |IBM 45nm SOI |RV64G1p9999_Xhwacha3
|===

首批制造的 RISC-V 处理器是用 Verilog 编写的，并于 2011 年在 ST 的预生产 FDSOI 技术中制造为 Raven-1 测试芯片。由 Yunsup Lee 和 Andrew Waterman 开发了两个内核，在 Krste Asanović 的指导下共同制造：1）一个具有错误检测触发器的 RV64 标量内核，2）一个附带 64 位浮点矢量单元的 RV64 内核。第一个微架构非正式地称为“TrainWreck”，因为完成设计的时间很短且设计库不成熟。

随后，Andrew Waterman、Rimas Avižienis 和 Yunsup Lee 在 Krste Asanović 的指导下开发了一个干净的顺序解耦 RV64 内核微架构，并继续铁路主题，代号为“Rocket”，以纪念 George Stephenson 成功的蒸汽机车设计。Rocket 是用 Chisel 编写的，这是一种在 UC Berkeley 开发的新硬件设计语言。Rocket 中使用的 IEEE 浮点单元由 John Hauser、Andrew Waterman 和 Brian Richards 开发。Rocket 之后得到了进一步的改进和发展，并在 FDSOI 中制造了两次（Raven-2，Raven-3），在 IBM SOI 技术中制造了五次（EOS14，EOS16，EOS18，EOS20，EOS22）用于光子学项目。正在进行的工作是使 Rocket 设计作为参数化 RISC-V 处理器生成器可用。

EOS14-EOS22 芯片包括早期版本的 Hwacha，一个 64 位 IEEE 浮点矢量单元，由 Yunsup Lee、Andrew Waterman、Huy Vo、Albert Ou、Quan Nguyen 和 Stephen Twigg 开发，Krste Asanović 指导。EOS16-EOS22 芯片包括由 Henry Cook 和 Andrew Waterman 开发的双核缓存一致性协议，Krste Asanović 指导。EOS14 硅片已成功运行在 1.25 GHz。EOS16 硅片由于 IBM 垫库中的一个错误而受影响。EOS18 和 EOS20 已成功运行在 1.35 GHz。

Raven 测试芯片的贡献者包括 Yunsup Lee、Andrew Waterman、Rimas Avižienis、Brian Zimmer、Jaehwa Kwak、Ruzica Jevtić、Milovan Blagojević、Alberto Puggelli、Steven Bailey、Ben Keller、Pi-Feng Chiu、Brian Richards、Borivoje Nikolić 和 Krste Asanović。

EOS 测试芯片的贡献者包括 Yunsup Lee、Rimas Avižienis、Andrew Waterman、Henry Cook、Huy Vo、Daiwei Li、Chen Sun、Albert Ou、Quan Nguyen、Stephen Twigg、Vladimir Stojanović 和 Krste Asanović。

Andrew Waterman 和 Yunsup Lee 开发了 C++ ISA 模拟器“Spike”，作为开发中的黄金模型，并以庆祝美国跨大陆铁路完工的金钉命名。Spike 已作为 BSD 开源项目提供。

Andrew Waterman 完成了一篇硕士论文，初步设计了 RISC-V 压缩指令集 cite:[waterman-ms]。

已经完成了多个 RISC-V 的 FPGA 实现，主要作为 Par Lab 项目研究静修会的集成演示的一部分。最大的 FPGA 设计有 3 个缓存一致的 RV64IMA 处理器运行研究操作系统。FPGA 实现的贡献者包括 Andrew Waterman、Yunsup Lee、Rimas Avižienis 和 Krste Asanović。

RISC-V 处理器已在 UC Berkeley 的多个课程中使用。Rocket 在 2011 年秋季的 CS250 课程中用作课程项目的基础，Brian Zimmer 是助教。在 2012 年春季的本科 CS152 课程中，Christopher Celio 使用 Chisel 编写了一套教育 RV32 处理器，名为“Sodor”，以“托马斯和朋友们”所在的岛屿命名。该套件包括一个微码内核、一个未流水线内核和 2、3 和 5 级流水线内核，并以 BSD 许可证公开提供。该套件随后进行了更新，并在 2013 年春季的 CS152 课程中再次使用，Yunsup Lee 是助教，2014 年春季的 CS152 课程中，Eric Love 是助教。Christopher Celio 还开发了一个称为 BOOM（Berkeley Out-of-Order Machine）的乱序 RV64 设计，并提供了伴随的流水线可视化，用于 CS152 课程。CS152 课程还使用了由 Andrew Waterman 和 Henry Cook 开发的缓存一致版本的 Rocket 内核。

在 2013 年夏季，定义了 RoCC（Rocket Custom Coprocessor）接口，以简化向 Rocket 内核添加自定义加速器。Rocket 和 RoCC 接口在 2013 年秋季的 CS250 VLSI 课程中广泛使用，Jonathan Bachrach 教授，多个学生加速器项目基于 RoCC 接口构建。Hwacha 矢量单元已重新编写为 RoCC 协处理器。

两名伯克利本科生 Quan Nguyen 和 Albert Ou 在 2013 年春季成功将 Linux 移植到 RISC-V 上运行。

Colin Schmidt 在 2014 年 1 月成功完成了 RISC-V 2.0 的 LLVM 后端。

Bluespec 的 Darius Rad 在 2014 年 3 月为 GCC 移植贡献了软浮点 ABI 支持。

John Hauser 贡献了浮点分类指令的定义。

我们知道还有几个 RISC-V 内核实现，包括 Tommy Thorn 的一个 Verilog 实现和 Rishiyur Nikhil 的一个 Bluespec 实现。

=== 致谢

感谢 Christopher F. Batten、Preston Briggs、Christopher Celio、David Chisnall、Stefan Freudenberger、John Hauser、Ben Keller、Rishiyur Nikhil、Michael Taylor、Tommy Thorn 和 Robert Watson 对 ISA 2.0 版规范草案的评论。

=== ISA 手册 2.1 版的历史

自 2014 年 5 月推出冻结版 2.0 以来，RISC-V ISA 的采用速度非常快，活动太多，无法在这样一个简短的历史部分中记录。也许最重要的单一事件是 2015 年 8 月成立了非营利性 RISC-V 基金会。基金会现在将接管官方 RISC-V ISA 标准的管理，官方网站 `riscv.org` 是获取 RISC-V 标准新闻和更新的最佳地方。

=== 致谢

感谢 Scott Beamer、Allen J. Baum、Christopher Celio、David Chisnall、Paul Clayton、Palmer Dabbelt、Jan Gray、Michael Hamburg 和 John Hauser 对 2.0 版规范的评论。

=== ISA 手册 2.2 版的历史

=== 致谢

感谢 Jacob Bachmeyer、Alex Bradbury、David Horner、Stefan O’Rear 和 Joseph Myers 对 2.1 版规范的评论。

=== ISA 手册 2.3 版的历史

RISC-V 的采用速度继续迅猛发展。

John Hauser 和 Andrew Waterman 基于 Paolo Bonzini 的提案贡献了一个虚拟机 ISA 扩展。

Daniel Lustig、Arvind、Krste Asanović、Shaked Flur、Paul Loewenstein、Yatin Manerkar、Luc Maranget、Margaret Martonosi、Vijayanand Nagarajan、Rishiyur Nikhil、Jonas Oberhauser、Christopher Pulte、Jose Renau、Peter Sewell、Susmit Sarkar、Caroline Trippel、Muralidaran Vijayaraghavan、Andrew Waterman、Derek Williams、Andrew Wright 和 Sizhuo Zhang 贡献了内存一致性模型。

=== 资金支持

RISC-V 架构和实现的开发部分由以下赞助商资助。

* *Par Lab:* 研究由 Microsoft（奖项编号 024263）和 Intel（奖项编号 024894）资助，并由 U.C. Discovery（奖项编号 DIG07-10227）提供匹配资金。额外支持来自 Par Lab 合作伙伴 Nokia、NVIDIA、Oracle 和 Samsung。
* *Project Isis:* DoE 奖项 DE-SC0003624。
* *ASPIRE Lab:* DARPA PERFECT 计划，奖项 HR0011-12-2-0016。DARPA POEM 计划奖项 HR0011-11-C-0100。未来架构研究中心（C-FAR），由半导体研究公司资助的 STARnet 中心。额外支持来自 ASPIRE 工业赞助商 Intel 和 ASPIRE 合作伙伴 Google、Hewlett Packard Enterprise、Huawei、Nokia、NVIDIA、Oracle 和 Samsung。

本文内容不一定反映美国政府的立场或政策，不应推断出任何官方认可。
