[[mstandard]]
== “M” 扩展：用于整数乘法和除法，版本 2.0

本章描述了标准的整数乘法和除法指令扩展，名为“M”扩展，包含用于对两个整数寄存器中保存的值进行乘法或除法运算的指令。

[TIP]
====
我们将整数乘法和除法从基础架构中分离出来，以简化轻量级实现，或适用于那些整数乘法和除法操作较为罕见或更适合由附加加速器处理的应用。
====

=== 乘法操作（Multiplication Operations）

include::images/wavedrom/m-st-ext-for-int-mult.adoc[]
[[m-st-ext-for-int-mult]]
//.乘法操作指令
(((MUL, MULH)))
(((MUL, MULHU)))
(((MUL, MULHSU)))

MUL 执行 _rs1_ 乘以 _rs2_ 的 XLEN 位×XLEN 位乘法，并将低 XLEN 位放入目标寄存器。MULH、MULHU 和 MULHSU 执行相同的乘法，但返回完整 2×XLEN 位乘积的高 XLEN 位，分别用于有符号×有符号、无符号×无符号和 _rs1_×无符号 _rs2_ 乘法。如果需要同一乘积的高位和低位，则推荐的代码序列是：MULH[[S]U] _rdh, rs1, rs2_; MUL _rdl, rs1, rs2_（源寄存器说明符必须相同顺序，且 _rdh_ 不能与 _rs1_ 或 _rs2_ 相同）。微架构可以将这些融合为单个乘法操作，而不是执行两个独立的乘法。

[NOTE]
====
MULHSU 用于多字有符号乘法，将一个乘数的最高有效字（包含符号位）与一个乘数的低有效字（无符号）相乘。
====

MULW 是一个 RV64 指令，它将源寄存器的低 32 位相乘，并将结果的低 32 位符号扩展到目标寄存器。

[NOTE]
====
在 RV64 中，MUL 可用于获取 64 位乘积的高 32 位，但有符号参数必须是正确的 32 位有符号值，而无符号参数的高 32 位必须清零。如果参数不确定是否已符号或零扩展，可以将两个参数都左移 32 位，然后使用 MULH[[S]U]。
====

=== 除法操作（Division Operations）

include::images/wavedrom/division-op.adoc[]
[[division-op]]
//.除法操作指令
(((MUL, DIV)))
(((MUL, DIVU)))

DIV 和 DIVU 执行 _rs1_ 除以 _rs2_ 的 XLEN 位有符号和无符号整数除法，向零舍入。REM 和 REMU 提供相应除法操作的余数。对于 REM，非零结果的符号等于被除数的符号。

[NOTE]
====
对于有符号和无符号除法，除溢出情况外，均满足
latexmath:[$\textrm{dividend} = \textrm{divisor} \times \textrm{quotient} + \textrm{remainder}$]。
====

如果需要同一除法的商和余数，则推荐的代码序列是：DIV[U] _rdq, rs1, rs2_; REM[U] _rdr, rs1, rs2_（需要保证 _rdq_ 不能与 _rs1_ 或 _rs2_ 相同）。在这一序列下，微架构可以将这些融合为单个除法操作，而不是执行两个独立的除法。

DIVW 和 DIVUW 是 RV64 指令，它们将 _rs1_ 的低 32 位除以 _rs2_ 的低 32 位，分别将它们视为有符号和无符号整数，并将 32 位商放入 _rd_，符号扩展到 64 位。REMW 和 REMUW 是 RV64 指令，分别提供相应的有符号和无符号余数操作。REMW 和 REMUW 总是将 32 位结果符号扩展到 64 位，包括在除以零时。
(((MUL, div by zero)))

除以零和除法溢出的语义总结在 <<divby0>> 中。除以零的商所有位都设置为 1，除以零的余数等于被除数。有符号除法溢出仅在最小负整数除以 latexmath:[$-1$] 时发生。有符号除法溢出的商等于被除数，余数为零。无符号除法溢出不会发生。

[[divby0]]
.除以零和除法溢出的语义。L 是操作的位宽：DIV[U] 和 REM[U] 为 XLEN，或 DIV[U]W 和 REM[U]W 为 32。
[cols="<2,^,^,^,^,^,^",options="header",]
|===
|条件 |被除数 |除数 |DIVU[W] |REMU[W] |DIV[W] |REM[W]

|除以零 +
溢出（仅有符号） |latexmath:[$x$] +
latexmath:[$-2^{L-1}$] |0 +
latexmath:[$-1$] |latexmath:[$2^{L}-1$] +
 - |latexmath:[$x$] +
 - |latexmath:[$-1$] +
 latexmath:[$-2^{L-1}$] +
  |latexmath:[$x$] +
  0
|===

//|Overflow (signed only) |latexmath:[$-2^{L-1}$] |latexmath:[$-1$] |– |– |latexmath:[$-2^{L-1}$] |0
//|===

[TIP]
====
我们曾考虑在整数除以零时引发异常，这些异常在大多数执行环境中会触发陷阱。然而，这将是标准 ISA 中唯一的算术陷阱（浮点异常通过设置标志并写入默认值来处理，但不会触发陷阱），并且这会要求语言实现者与执行环境的陷阱处理程序进行交互。进一步来说，当语言标准要求除以零异常必须立即导致控制流变化时，只需在每个除法操作中添加一个分支指令，该指令可插入在除法操作后，并且通常预期不会被采取，从而对运行时的开销影响极小。

为了简化除法器电路，无论是无符号除法还是有符号除法，都会返回所有位都设置为 1 的值。所有 1 的值既是无符号除法返回的自然值，表示最大的无符号数，也是简单无符号除法器实现的自然结果。有符号除法通常使用无符号除法电路实现，指定相同的溢出结果从而简化了硬件设计。
====

=== “Zmmul” 扩展：版本 1.0

Zmmul 扩展实现了 M 扩展的乘法子集。它添加了 <<乘法操作（Multiplication Operations）>> 中定义的所有指令，即：MUL、MULH、MULHU、MULHSU 和（仅适用于 RV64）MULW。编码与相应的 M 扩展指令相同。M 包含 Zmmul。
(((MUL, Zmmul)))

[NOTE]
====
*Zmmul* 扩展使需要乘法操作但不需要除法的低成本实现成为可能。对于许多微控制器应用，除法操作不够频繁，不足以证明除法器硬件的成本是合理的。相比之下，乘法操作更频繁，使得乘法器硬件的成本更合理。简单的 FPGA 软核特别受益于消除除法但保留乘法，因为许多 FPGA 提供硬连线乘法器，但需要在软逻辑中实现除法器。
====

