[[naming]]
== ISA 扩展命名约定

本章描述了 RISC-V ISA 扩展的命名方案，用于简洁地描述硬件实现中存在的指令集，或应用程序二进制接口（ABI）使用的指令集。
[NOTE]
====
RISC-V ISA 设计支持多种实验性指令集扩展的实现。我们发现，系统化的命名方案能有效简化软件工具与文档的管理。
====
=== 大小写敏感性

ISA 命名字符串不区分大小写。

=== 基本整数 ISA

RISC-V ISA 字符串以 RV32I、RV32E、RV64I、RV64E 或 RV128I 开头，表示基本整数 ISA 支持的地址空间大小（以位为单位）。

=== 指令集扩展名称

标准 ISA 扩展名称由单个字母组成。例如，基础整数扩展的前四个标准扩展为：“M”表示整数乘法与除法，“A”表示原子内存指令，“F”表示单精度浮点指令，“D”表示双精度浮点指令。任何 RISC-V 指令集变体可通过将基本整数前缀与其扩展名称连接，简洁地表示，如“RV64IMAFD”。

此外，“G”缩写代表“IMAFDZicsr_Zifencei”基础及扩展，代表我们的标准通用 ISA。

RISC-V ISA 的标准扩展使用其他保留字母，例如“Q”表示四倍精度浮点，“C”表示 16 位压缩指令格式。

某些扩展依赖于其他扩展的存在，例如“D”依赖于“F”，“F”依赖于“Zicsr”。这些依赖关系在 ISA 名称中已隐含：例如，RV32IF 等价于 RV32IFZicsr，RV32ID 等价于 RV32IFD 和 RV32IFDZicsr。

=== 版本号

考虑到指令集可能会随时间变化或扩展，我们在扩展名称后面添加了版本号。版本号由主版本号和次版本号组成，二者通过“p”分隔。若次版本号为“0”，则“p0”可以省略。主版本号的变化意味着不再向后兼容，而次版本号的变化则要求保持向后兼容。例如，本手册第 1.0 版中定义的初始 64 位标准 ISA 完整表示为“RV64I1p0M1p0A1p0F1p0D1p0”，简化后为“RV64I1M1A1F1D1”。

我们从第二版起引入了版本编号方案，并将标准扩展的默认版本设为当时的版本。例如，“RV32I”即代表“RV32I2”。

=== 下划线

为提升可读性并避免歧义，ISA 扩展可以通过下划线“_”分隔，例如“RV32I2_M2_A2”。

由于“P”扩展（表示打包 SIMD）可能与版本号中的小数点混淆，因此如果“P”紧跟在数字后面，必须加上下划线。例如，“rv32i2p2”表示 RV32I 的 2.2 版，而“rv32i2_p2”表示 RV32I 2.0 版以及 P 扩展 2.0 版。

=== 其他标准扩展名称

标准扩展的命名方式还可以使用“Z”后跟字母名称，并附上可选的版本号。例如，“Zifencei”代表指令获取屏障扩展（详见 <<zifencei>>）；“Zifencei2”和“Zifencei2p0”均为其 2.0 版。

“Z”后的首字母通常表示最相关的扩展类别（如 IMAFDQCVH）。例如，“Zfa”扩展表示附加浮点指令，其中字母“f”表示与“F”标准扩展相关。若命名多个“Z”扩展，应按类别排序，且在每个类别内按字母顺序排列，如“Zicsr_Zifencei_Zam”。

所有多字母扩展，包括带有“Z”前缀的扩展，必须用下划线与其他扩展分隔，例如“RV32IMACZicsr_Zifencei”。

=== 监督级指令集扩展

扩展监督级虚拟内存架构的标准扩展以“Sv”为前缀，后接字母名称和可选的版本号，或者仅接无版本号的数字名称。扩展监督级架构的其他标准扩展则以“Ss”为前缀，后接字母名称和可选版本号。这些扩展的详细信息在第二卷中有所定义。

标准监督级扩展应按顺序列在标准非特权扩展之后。如果有多个监督级扩展，应按字母顺序排列。

=== 虚拟机级指令集扩展

扩展虚拟机级架构的标准扩展以字母“Sh”开头。如果有多个虚拟机级扩展，它们应按字母顺序排列。

NOTE: 许多虚拟机级架构扩展更适合作为监督级扩展定义，按照上一节描述的方式处理。仅少数不涉及监督可见效果的虚拟机级扩展才使用“Sh”前缀。

=== 机器级指令集扩展

标准机器级指令集扩展以字母“Sm”为前缀。

标准机器级扩展应位于标准低特权扩展之后，多个机器级扩展应按字母顺序排列。

=== 非标准扩展名称

非标准扩展以字母“X”开头，后跟扩展名称和可选版本号。例如，“Xhwacha”表示 Hwacha 向量获取扩展，“Xhwacha2”和“Xhwacha2p0”则表示同一扩展的 2.0 版本。

所有非标准扩展应排在标准扩展之后，并与其他多字母扩展用下划线分隔。例如，带有 Argle 和 Bargle 非标准扩展的 ISA 可命名为 "RV64IZifencei_Xargle_Xbargle"。

多个非标准扩展应按字母顺序排列。

=== 子集命名约定

<<isanametable>> 总结了标准化的扩展名称，并定义了这些名称在字符串中的规范顺序。表格从上到下列出的顺序，表示名称字符串中的顺序。例如，"RV32IMACV" 是合法的，而 "RV32IMAVC" 则不合法。
[[isanametable]]
.标准 ISA 扩展名称。
[%autowidth,float="center",align="center",cols="<,^,^",options="header",]
|===
|子集 |名称 |隐含

|基本 ISA | |

|整数 |I |

|简化整数 |E |

3+|*标准非特权扩展*

|整数乘法和除法 |M |Zmmul

|原子操作 |A |

|单精度浮点 |F |Zicsr

|双精度浮点 |D |F

|通用 |G |IMAFDZicsr_Zifencei

|四倍精度浮点 |Q |D

|16 位压缩指令 |C |

|B 扩展 |B |

|打包 SIMD 扩展 |P |

|向量扩展 |V |D

|虚拟机扩展 |H |

|控制状态寄存器访问 |Zicsr |

|指令获取屏障 |Zifencei |

|总存储排序 |Ztso |

3+|*标准监督级扩展*

|监督级扩展 "def" |Ssdef |

3+|*标准机器级扩展*

|机器级扩展 "jkl" |Smjkl |

3+|*非标准扩展*

|非标准扩展 "mno" |Xmno |
|===
