[[naming]]
== ISA 扩展命名约定

本章描述了 RISC-V ISA 扩展的命名方案，用于简洁地描述硬件实现中存在的指令集，或应用程序二进制接口（ABI）使用的指令集。
[NOTE]
====
RISC-V ISA 设计支持各种实验性指令集扩展的广泛实现。我们发现，有组织的命名方案简化了软件工具和文档。
====
=== 大小写敏感性

ISA 命名字符串不区分大小写。

=== 基本整数 ISA

RISC-V ISA 字符串以 RV32I、RV32E、RV64I、RV64E 或 RV128I 开头，表示基本整数 ISA 支持的地址空间大小（以位为单位）。

=== 指令集扩展名称

标准 ISA 扩展的名称由一个字母组成。例如，整数基础的前四个标准扩展是："M" 表示整数乘法和除法，"A" 表示原子内存指令，"F" 表示单精度浮点指令，"D" 表示双精度浮点指令。任何 RISC-V 指令集变体都可以通过将基本整数前缀与包含的扩展名称连接起来简洁地描述，例如 "RV64IMAFD"。

我们还定义了一个缩写 "G" 来表示 "IMAFDZicsr_Zifencei" 基础和扩展，因为这代表了我们的标准通用 ISA。

RISC-V ISA 的标准扩展使用其他保留字母，例如 "Q" 表示四倍精度浮点，或 "C" 表示 16 位压缩指令格式。

某些 ISA 扩展依赖于其他扩展的存在，例如 "D" 依赖于 "F"，"F" 依赖于 "Zicsr"。这些依赖关系可以在 ISA 名称中隐含：例如，RV32IF 等同于 RV32IFZicsr，RV32ID 等同于 RV32IFD 和 RV32IFDZicsr。

=== 版本号

考虑到指令集可能会随着时间的推移而扩展或更改，我们在扩展名称后面编码了扩展版本号。版本号分为主版本号和次版本号，用 "p" 分隔。如果次版本号为 "0"，则可以从版本字符串中省略 "p0"。主版本号的更改意味着向后兼容性的丧失，而仅次版本号的更改必须向后兼容。例如，本手册 1.0 版中定义的初始 64 位标准 ISA 可以完整地写为 "RV64I1p0M1p0A1p0F1p0D1p0"，更简洁地写为 "RV64I1M1A1F1D1"。

我们在第二版中引入了版本编号方案。因此，我们将标准扩展的默认版本定义为当时存在的版本，例如 "RV32I" 等同于 "RV32I2"。

=== 下划线

可以使用下划线 "_" 分隔 ISA 扩展以提高可读性和提供消歧，例如 "RV32I2_M2_A2"。

由于 "P" 扩展（表示打包 SIMD）可能与版本号中的小数点混淆，因此如果它跟在数字后面，必须在前面加下划线。例如，"rv32i2p2" 表示 RV32I 的 2.2 版，而 "rv32i2_p2" 表示 RV32I 的 2.0 版和 P 扩展的 2.0 版。

=== 其他标准扩展名称

标准扩展也可以使用单个 "Z" 后跟字母名称和可选的版本号来命名。例如，"Zifencei" 命名为 <<zifencei>> 中描述的指令获取屏障扩展；"Zifencei2" 和 "Zifencei2p0" 命名为相同的 2.0 版。

"Z" 后的第一个字母通常表示最相关的字母扩展类别 IMAFDQCVH。例如，"Zfa" 扩展表示附加浮点指令，其中字母 "f" 表示该扩展与 "F" 标准扩展相关。如果命名多个 "Z" 扩展，它们应首先按类别排序，然后在类别内按字母顺序排序，例如 "Zicsr_Zifencei_Zam"。

所有多字母扩展，包括带有 "Z" 前缀的扩展，必须与其他多字母扩展用下划线分隔，例如 "RV32IMACZicsr_Zifencei"。

=== 监督级指令集扩展

扩展监督级虚拟内存架构的标准扩展以字母 "Sv" 为前缀，后跟字母名称和可选的版本号，或后跟无版本号的数字名称。扩展监督级架构的其他标准扩展以字母 "Ss" 为前缀，后跟字母名称和可选的版本号。这些扩展在第二卷中定义。

标准监督级扩展应列在标准非特权扩展之后。如果列出多个监督级扩展，它们应按字母顺序排序。

=== 虚拟机级指令集扩展

扩展虚拟机级架构的标准扩展以字母 "Sh" 为前缀。如果列出多个虚拟机级扩展，它们应按字母顺序排序。

NOTE: 许多虚拟机级架构的扩展更自然地定义为监督级扩展，按照上一节描述的方案。对于没有监督可见效果的少数虚拟机级扩展，使用 "Sh" 前缀。

=== 机器级指令集扩展

标准机器级指令集扩展以字母 "Sm" 为前缀。

标准机器级扩展应列在标准低特权扩展之后。如果列出多个机器级扩展，它们应按字母顺序排序。

=== 非标准扩展名称

非标准扩展使用单个 "X" 后跟字母名称和可选的版本号命名。例如，"Xhwacha" 命名为 Hwacha 向量获取 ISA 扩展；"Xhwacha2" 和 "Xhwacha2p0" 命名为相同的 2.0 版。

非标准扩展必须列在所有标准扩展之后，并且像其他多字母扩展一样，必须与其他多字母扩展用下划线分隔。例如，带有非标准扩展 Argle 和 Bargle 的 ISA 可以命名为 "RV64IZifencei_Xargle_Xbargle"。

如果列出多个非标准扩展，它们应按字母顺序排序。

=== 子集命名约定

<<isanametable>> 总结了标准化的扩展名称。表格还定义了扩展名称在名称字符串中必须出现的规范顺序，表格中的从上到下表示名称字符串中的从前到后，例如 RV32IMACV 是合法的，而 RV32IMAVC 则不合法。

[[isanametable]]
.标准 ISA 扩展名称。
[%autowidth,float="center",align="center",cols="<,^,^",options="header",]
|===
|子集 |名称 |隐含

|基本 ISA | |

|整数 |I |

|简化整数 |E |

3+|*标准非特权扩展*

|整数乘法和除法 |M |Zmmul

|原子操作 |A |

|单精度浮点 |F |Zicsr

|双精度浮点 |D |F

|通用 |G |IMAFDZicsr_Zifencei

|四倍精度浮点 |Q |D

|16 位压缩指令 |C |

|B 扩展 |B |

|打包 SIMD 扩展 |P |

|向量扩展 |V |D

|虚拟机扩展 |H |

|控制和状态寄存器访问 |Zicsr |

|指令获取屏障 |Zifencei |

|总存储排序 |Ztso |

3+|*标准监督级扩展*

|监督级扩展 "def" |Ssdef |

3+|*标准机器级扩展*

|机器级扩展 "jkl" |Smjkl |

3+|*非标准扩展*

|非标准扩展 "mno" |Xmno |
|===
