== "Q" 扩展: 四精度浮点，版本 2.2

本章节描述了符合 IEEE 754-2008 算术标准的 128 位四精度二进制浮点指令的 Q 标准扩展。四精度二进制浮点指令集扩展被命名为 "Q"；它依赖于双精度浮点扩展 D。浮点寄存器现在被扩展为可以存储单精度、双精度或四精度浮点值（FLEN=128）。<<nanboxing>> 中描述的 NaN 装箱方案现在递归扩展，允许将单精度值嵌套在双精度值中的 NaN 装箱内，而双精度值又嵌套在四精度值中的 NaN 装箱内。

=== 四精度加载和存储指令

新增了 128 位版本的 LOAD-FP 和 STORE-FP 指令，使用新的 funct3 宽度字段值进行编码。

include::images/wavedrom/quad-ls.adoc[]
[[quad-ls]]
//.四精度加载和存储

只有在有效地址自然对齐且 XLEN=128 时，FLQ 和 FSQ 才能保证原子性执行。

FLQ 和 FSQ 不会修改被传输的位；特别地，非标准 NaN 的有效载荷会被保留。

=== 四精度计算指令

大多数指令的格式字段中新增了一种支持的新格式，如 <<fpextfmt>> 所示。

[[fpextfmt]]
.格式字段编码.
[%autowidth,float="center",align="center",cols="^,^,<",options="header",]
|===
|_fmt_ 字段 |助记符 |含义
|00 |S |32 位单精度
|01 |D |64 位双精度
|10 |H |16 位半精度
|11 |Q |128 位四精度
|===

四精度浮点数计算指令的定义与其双精度对应指令类似，但它们操作的是四精度操作数，并生成四精度结果。

include::images/wavedrom/quad-compute.adoc[]
[[quad-compute]]
//.四精度计算

=== 四精度转换与移动指令

新增了浮点数到整数和整数到浮点数的转换指令。这些指令的定义与双精度到整数和整数到双精度转换指令类似。FCVT.W.Q 或 FCVT.L.Q 分别将四精度浮点数转换为有符号 32 位或 64 位整数。FCVT.Q.W 或 FCVT.Q.L 分别将 32 位或 64 位有符号整数转换为四精度浮点数。FCVT.WU.Q、FCVT.LU.Q、FCVT.Q.WU 和 FCVT.Q.LU 变体用于在无符号整数值之间进行转换。FCVT.L[U].Q 和 FCVT.Q.L[U] 是 RV64 专用指令。请注意，FCVT.Q.L[U] 总是产生精确结果，不受舍入模式的影响。

include::images/wavedrom/quad-cnvrt-mv.adoc[]
[[quad-cnvrt-mv]]
//.四精度转换和移动

新增了浮点数到浮点数的转换指令。这些指令的定义与双精度浮点数到浮点数转换指令类似。FCVT.S.Q 或 FCVT.Q.S 分别将四精度浮点数转换为单精度浮点数，或将单精度浮点数转换为四精度浮点数。FCVT.D.Q 或 FCVT.Q.D 分别将四精度浮点数转换为双精度浮点数，或将双精度浮点数转换为四精度浮点数。

include::images/wavedrom/quad-cnvt-interchange.adoc[]
[[quad-convrt-interchange]]
//.四精度转换与移动可以互换使用

浮点数到浮点数的符号注入指令 FSGNJ.Q、FSGNJN.Q 和 FSGNJX.Q 的定义方式与双精度符号注入指令类似。

include::images/wavedrom/quad-cnvrt-intch-xqqx.adoc[]
[[quad-cnvrt-intch-xqqx]]
//.四精度转换与移动可以互换使用 XQ-QX

RV32 和 RV64 中均未提供 FMV.X.Q 和 FMV.Q.X 指令，因此必须通过内存将四精度位模式传输到整数寄存器中。

[NOTE]
====
RV128 将在 Q 扩展中支持 FMV.X.Q 和 FMV.Q.X.
====

=== 四精度浮点数比较指令

四精度浮点数比较指令的定义与其双精度对应指令类似，但它们操作的是四精度操作数。

include::images/wavedrom/quad-float-compare.adoc[]
[[quad-float-compare]]
//.四精度浮点数比较

=== 四精度浮点数分类指令

四精度浮点数分类指令 FCLASS.Q 的定义方式与其双精度对应指令类似，但它们操作的是四精度操作数。

include::images/wavedrom/quad-float-clssfy.adoc[]
[[quad-float-clssfy]]
//.四精度浮点数分类