[[rv32-64g]]
== RV32/64G 指令集列表

RISC-V 项目的一个目标是将其用作稳定的软件开发目标。为此，我们定义了一个基础 ISA（RV32I 或 RV64I）加上选定的标准扩展（IMAFD、Zicsr、Zifencei）作为“通用”ISA，并使用缩写 G 表示 IMAFDZicsr_Zifencei 指令集扩展的组合。本章展示了 RV32G 和 RV64G 的操作码映射和指令集列表。

[[opcodemap]]
[%autowidth.stretch,float="center",align="center",cols=  ">.^4m,  ^.^4m,    ^.^4m,      ^.^4m,    ^.^4m,  ^.^4m,      ^.^4m,           ^.^6m, ^.^4h"]
|===
|inst[4:2] .2+|000 .2+|001   .2+|010     .2+|011   .2+|100 .2+|101     .2+|110          .2+|111 (>32b)
|inst[6:5]
|00           |LOAD   |LOAD-FP  |_custom-0_ |MISC-MEM |OP-IMM |AUIPC      |OP-IMM-32       |48b
|01           |STORE  |STORE-FP |_custom-1_ |AMO      |OP     |LUI        |OP-32           |64b
|10           |MADD   |MSUB     |NMSUB      |NMADD    |OP-FP  |OP-V       |_custom-2/rv128_|48b
|11           |BRANCH |JALR     |_reserved_ |JAL      |SYSTEM |OP-VE      |_custom-3/rv128_|&#8805;80b
|===

<<opcodemap>> 显示了 RVG 的主要操作码映射。为了支持超过 32 位的指令，RVG 至少保留了主要操作码的最低三位。标记为 _reserved_ 的操作码应避免用于自定义指令集扩展，因为它们可能会被未来的标准扩展使用。标记为 _custom-0_ 和 _custom-1_ 的主要操作码将被未来的标准扩展避免，建议用于基础 32 位指令格式内的自定义指令集扩展。标记为 _custom-2/rv128_ 和 _custom-3/rv128_ 的操作码虽然被保留供未来 RV128 使用，但其他的标准扩展会避开使用。因此，在 RV32 和 RV64 中，它们仍然可以用于自定义指令集扩展。

我们认为 RV32G 和 RV64G 提供了简单且完整的指令集，适用于广泛的通用计算。此外也可以添加定义在 <<compressed>> 中的压缩指令集（形成 RV32GC 和 RV64GC），以提升性能与能效，减小代码大小，尽管会增加一些硬件复杂性。

当我们超越 IMAFDC 进入进一步的指令集扩展时，新增的指令往往更具领域特定性，仅对有限类别的应用程序提供好处，例如多媒体或安全。与大多数商业 ISA 不同，RISC-V ISA 设计明确区分了基础 ISA 和广泛适用的标准扩展与这些更专业的附加项。<<extending>> 详细讨论了向 RISC-V ISA 添加扩展的方法。

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |   0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R 型
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I 型
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S 型
 4+^|imm[12\|10:5]  2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:1\|11] 2+^|opcode  <|B 型
10+^|imm[31:12]                                    2+^|rd           2+^|opcode  <|U 型
10+^|imm[20\|10:1\|11\|19:12]                      2+^|rd           2+^|opcode  <|J 型
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32I 基础指令集*
10+^|imm[31:12]                                    2+^|rd           2+^|0110111 <|LUI
10+^|imm[31:12]                                    2+^|rd           2+^|0010111 <|AUIPC
10+^|imm[20\|10:1\|11\|19:12]                      2+^|rd           2+^|1101111 <|JAL
 6+^|imm[11:0]                2+^|rs1   2+^|000    2+^|rd           2+^|1100111 <|JALR
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|000    2+^|imm[4:1\|11] 2+^|1100011 <|BEQ
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|001    2+^|imm[4:1\|11] 2+^|1100011 <|BNE
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|100    2+^|imm[4:1\|11] 2+^|1100011 <|BLT
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|101    2+^|imm[4:1\|11] 2+^|1100011 <|BGE
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|110    2+^|imm[4:1\|11] 2+^|1100011 <|BLTU
 4+^|imm[12\|10:5]  2+^|rs2   2+^|rs1   2+^|111    2+^|imm[4:1\|11] 2+^|1100011 <|BGEU
 6+^|imm[11:0]                2+^|rs1   2+^|000    2+^|rd           2+^|0000011 <|LB
 6+^|imm[11:0]                2+^|rs1   2+^|001    2+^|rd           2+^|0000011 <|LH
 6+^|imm[11:0]                2+^|rs1   2+^|010    2+^|rd           2+^|0000011 <|LW
 6+^|imm[11:0]                2+^|rs1   2+^|100    2+^|rd           2+^|0000011 <|LBU
 6+^|imm[11:0]                2+^|rs1   2+^|101    2+^|rd           2+^|0000011 <|LHU
 4+^|imm[11:5]      2+^|rs2   2+^|rs1   2+^|000    2+^|imm[4:0]     2+^|0100011 <|SB
 4+^|imm[11:5]      2+^|rs2   2+^|rs1   2+^|001    2+^|imm[4:0]     2+^|0100011 <|SH
 4+^|imm[11:5]      2+^|rs2   2+^|rs1   2+^|010    2+^|imm[4:0]     2+^|0100011 <|SW
 6+^|imm[11:0]                2+^|rs1   2+^|000    2+^|rd           2+^|0010011 <|ADDI
 6+^|imm[11:0]                2+^|rs1   2+^|010    2+^|rd           2+^|0010011 <|SLTI
 6+^|imm[11:0]                2+^|rs1   2+^|011    2+^|rd           2+^|0010011 <|SLTIU
 6+^|imm[11:0]                2+^|rs1   2+^|100    2+^|rd           2+^|0010011 <|XORI
 6+^|imm[11:0]                2+^|rs1   2+^|110    2+^|rd           2+^|0010011 <|ORI
 6+^|imm[11:0]                2+^|rs1   2+^|111    2+^|rd           2+^|0010011 <|ANDI
 4+^|0000000        2+^|shamt 2+^|rs1   2+^|001    2+^|rd           2+^|0010011 <|SLLI
 4+^|0000000        2+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0010011 <|SRLI
 4+^|0100000        2+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0010011 <|SRAI
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0110011 <|ADD
 4+^|0100000        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0110011 <|SUB
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|001    2+^|rd           2+^|0110011 <|SLL
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|010    2+^|rd           2+^|0110011 <|SLT
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0110011 <|SLTU
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|100    2+^|rd           2+^|0110011 <|XOR
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0110011 <|SRL
 4+^|0100000        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0110011 <|SRA
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|110    2+^|rd           2+^|0110011 <|OR
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|111    2+^|rd           2+^|0110011 <|AND
 3+^|fm   2+^|pred  1+^|succ  2+^|rs1   2+^|000    2+^|rd           2+^|0001111 <|FENCE
 3+^|1000 2+^|0011  1+^|0011  2+^|00000 2+^|000    2+^|00000        2+^|0001111 <|FENCE.TSO
 3+^|0000 2+^|0001  1+^|0000  2+^|00000 2+^|000    2+^|00000        2+^|0001111 <|PAUSE
 6+^|000000000000             2+^|00000 2+^|000    2+^|00000        2+^|1110011 <|ECALL
 6+^|000000000001             2+^|00000 2+^|000    2+^|00000        2+^|1110011 <|EBREAK
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R 型
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I 型
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S 型
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64I 基础指令集（除 RV32I 外）*
 6+^|imm[11:0]                2+^|rs1   2+^|110    2+^|rd           2+^|0000011 <|LWU
 6+^|imm[11:0]                2+^|rs1   2+^|011    2+^|rd           2+^|0000011 <|LD
 4+^|imm[11:5]      2+^|rs2   2+^|rs1   2+^|011    2+^|imm[4:0]     2+^|0100011 <|SD
 3+^|000000         3+^|shamt 2+^|rs1   2+^|001    2+^|rd           2+^|0010011 <|SLLI
 3+^|000000         3+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0010011 <|SRLI
 3+^|010000         3+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0010011 <|SRAI
 6+^|imm[11:0]                2+^|rs1   2+^|000    2+^|rd           2+^|0011011 <|ADDIW
 4+^|0000000        2+^|shamt 2+^|rs1   2+^|001    2+^|rd           2+^|0011011 <|SLLIW
 4+^|0000000        2+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0011011 <|SRLIW
 4+^|0100000        2+^|shamt 2+^|rs1   2+^|101    2+^|rd           2+^|0011011 <|SRAIW
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0111011 <|ADDW
 4+^|0100000        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0111011 <|SUBW
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|001    2+^|rd           2+^|0111011 <|SLLW
 4+^|0000000        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0111011 <|SRLW
 4+^|0100000        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0111011 <|SRAW
|===
[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32/RV64 _Zifencei_ 标准扩展*
 6+^|imm[11:0]                2+^|rs1   2+^|001    2+^|rd           2+^|0001111 <|FENCE.I
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32/RV64 _Zicsr_ 标准扩展*
 6+^|csr                      2+^|rs1   2+^|001    2+^|rd           2+^|1110011 <|CSRRW
 6+^|csr                      2+^|rs1   2+^|010    2+^|rd           2+^|1110011 <|CSRRS
 6+^|csr                      2+^|rs1   2+^|011    2+^|rd           2+^|1110011 <|CSRRC
 6+^|csr                      2+^|uimm  2+^|101    2+^|rd           2+^|1110011 <|CSRRWI
 6+^|csr                      2+^|uimm  2+^|110    2+^|rd           2+^|1110011 <|CSRRSI
 6+^|csr                      2+^|uimm  2+^|111    2+^|rd           2+^|1110011 <|CSRRCI
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32M 标准扩展*
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0110011 <|MUL
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|001    2+^|rd           2+^|0110011 <|MULH
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|010    2+^|rd           2+^|0110011 <|MULHSU
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|011    2+^|rd           2+^|0110011 <|MULHU
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|100    2+^|rd           2+^|0110011 <|DIV
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0110011 <|DIVU
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|110    2+^|rd           2+^|0110011 <|REM
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|111    2+^|rd           2+^|0110011 <|REMU
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64M 标准扩展（除 RV32M 外）*
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|000    2+^|rd           2+^|0111011 <|MULW
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|100    2+^|rd           2+^|0111011 <|DIVW
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|101    2+^|rd           2+^|0111011 <|DIVUW
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|110    2+^|rd           2+^|0111011 <|REMW
 4+^|0000001        2+^|rs2   2+^|rs1   2+^|111    2+^|rd           2+^|0111011 <|REMUW
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R 型
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32A 标准扩展*
 2+^|00010 ^|aq ^|rl 2+^|00000 2+^|rs1  2+^|010    2+^|rd           2+^|0101111 <|LR.W
 2+^|00011 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|SC.W
 2+^|00001 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOSWAP.W
 2+^|00000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOADD.W
 2+^|00100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOXOR.W
 2+^|01100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOAND.W
 2+^|01000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOOR.W
 2+^|10000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOMIN.W
 2+^|10100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOMAX.W
 2+^|11000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOMINU.W
 2+^|11100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|010    2+^|rd           2+^|0101111 <|AMOMAXU.W
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64A 标准扩展 (除 RV32A 外)*
 2+^|00010 ^|aq ^|rl 2+^|00000 2+^|rs1  2+^|011    2+^|rd           2+^|0101111 <|LR.D
 2+^|00011 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|SC.D
 2+^|00001 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOSWAP.D
 2+^|00000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOADD.D
 2+^|00100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOXOR.D
 2+^|01100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOAND.D
 2+^|01000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOOR.D
 2+^|10000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOMIN.D
 2+^|10100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOMAX.D
 2+^|11000 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOMINU.D
 2+^|11100 ^|aq ^|rl 2+^|rs2  2+^|rs1   2+^|011    2+^|rd           2+^|0101111 <|AMOMAXU.D
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R 型
 2+^|rs3 2+^|funct2 2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R4 型
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I 型
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S 型
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32F 标准扩展*
 6+^|imm[11:0]               2+^|rs1    2+^|010    2+^|rd           2+^|0000111 <|FLW
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|010    2+^|imm[4:0]     2+^|0100111 <|FSW
 2+^|rs3 2+^|00     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000011 <|FMADD.S
 2+^|rs3 2+^|00     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000111 <|FMSUB.S
 2+^|rs3 2+^|00     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001011 <|FNMSUB.S
 2+^|rs3 2+^|00     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001111 <|FNMADD.S
 4+^|0000000        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FADD.S
 4+^|0000100        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FSUB.S
 4+^|0001000        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FMUL.S
 4+^|0001100        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FDIV.S
 4+^|0101100        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FSQRT.S
 4+^|0010000        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FSGNJ.S
 4+^|0010000        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FSGNJN.S
 4+^|0010000        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FSGNJX.S
 4+^|0010100        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FMIN.S
 4+^|0010100        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FMAX.S
 4+^|1100000        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.W.S
 4+^|1100000        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.WU.S
 4+^|1110000        2+^|00000 2+^|rs1   2+^|000    2+^|rd           2+^|1010011 <|FMV.X.W
 4+^|1010000        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FEQ.S
 4+^|1010000        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FLT.S
 4+^|1010000        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FLE.S
 4+^|1110000        2+^|00000 2+^|rs1   2+^|001    2+^|rd           2+^|1010011 <|FCLASS.S
 4+^|1101000        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.W
 4+^|1101000        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.WU
 4+^|1111000        2+^|00000 2+^|rs1   2+^|000    2+^|rd           2+^|1010011 <|FMV.W.X
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64F 标准扩展 (除 RV32F 外)*
 4+^|1100000        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.L.S
 4+^|1100000        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.LU.S
 4+^|1101000        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.L
 4+^|1101000        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.LU
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===    
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R 型
 2+^|rs3 2+^|funct2 2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R4 型
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I 型
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S 型
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32D 标准扩展*
 6+^|imm[11:0]               2+^|rs1    2+^|011    2+^|rd           2+^|0000111 <|FLD
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|011    2+^|imm[4:0]     2+^|0100111 <|FSD
 2+^|rs3 2+^|01     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000011 <|FMADD.D
 2+^|rs3 2+^|01     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000111 <|FMSUB.D
 2+^|rs3 2+^|01     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001011 <|FNMSUB.D
 2+^|rs3 2+^|01     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001111 <|FNMADD.D
 4+^|0000001        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FADD.D
 4+^|0000101        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FSUB.D
 4+^|0001001        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FMUL.D
 4+^|0001101        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FDIV.D
 4+^|0101101        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FSQRT.D
 4+^|0010001        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FSGNJ.D
 4+^|0010001        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FSGNJN.D
 4+^|0010001        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FSGNJX.D
 4+^|0010101        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FMIN.D
 4+^|0010101        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FMAX.D
 4+^|0100000        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.D
 4+^|0100001        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.S
 4+^|1010001        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FEQ.D
 4+^|1010001        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FLT.D
 4+^|1010001        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FLE.D
 4+^|1110001        2+^|00000 2+^|rs1   2+^|001    2+^|rd           2+^|1010011 <|FCLASS.D
 4+^|1100001        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.W.D
 4+^|1100001        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.WU.D
 4+^|1101001        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.W
 4+^|1101001        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.WU
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64D 标准扩展 (除 RV32D 外)*
 4+^|1100001        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.L.D
 4+^|1100001        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.LU.D
 4+^|1110001        2+^|00000 2+^|rs1   2+^|000    2+^|rd           2+^|1010011 <|FMV.X.D
 4+^|1101001        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.L
 4+^|1101001        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.LU
 4+^|1111001        2+^|00000 2+^|rs1   2+^|000    2+^|rd           2+^|1010011 <|FMV.D.X
15+^|
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R 型
 2+^|rs3 2+^|funct2 2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R4 型
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I 型
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S 型
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R 型
 2+^|rs3 2+^|funct2 2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R4 型
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I 型
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S 型
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV32Q 标准扩展*
 4+^|imm[11:0]      2+^|     2+^|rs1    2+^|100    2+^|rd           2+^|0000111 <|FLQ
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|100    2+^|imm[4:0]     2+^|0100111 <|FSQ
 2+^|rs3 2+^|11     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000011 <|FMADD.Q
 2+^|rs3 2+^|11     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1000111 <|FMSUB.Q
 2+^|rs3 2+^|11     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001011 <|FNMSUB.Q
 2+^|rs3 2+^|11     2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1001111 <|FNMADD.Q
 4+^|0000011        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FADD.Q
 4+^|0000111        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FSUB.Q
 4+^|0001011        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FMUL.Q
 4+^|0001111        2+^|rs2  2+^|rs1    2+^|rm     2+^|rd           2+^|1010011 <|FDIV.Q
 4+^|0101111        2+^|00000  2+^|rs1  2+^|rm     2+^|rd           2+^|1010011 <|FSQRT.Q
 4+^|0010011        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FSGNJ.Q
 4+^|0010011        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FSGNJN.Q
 4+^|0010011        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FSGNJX.Q
 4+^|0010111        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FMIN.Q
 4+^|0010111        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FMAX.Q
 4+^|0100000        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.S.Q
 4+^|0100011        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.S
 4+^|0100001        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.D.Q
 4+^|0100011        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.D
 4+^|1010011        2+^|rs2  2+^|rs1    2+^|010    2+^|rd           2+^|1010011 <|FEQ.Q
 4+^|1010011        2+^|rs2  2+^|rs1    2+^|001    2+^|rd           2+^|1010011 <|FLT.Q
 4+^|1010011        2+^|rs2  2+^|rs1    2+^|000    2+^|rd           2+^|1010011 <|FLE.Q
 4+^|1110011        2+^|00000 2+^|rs1   2+^|001    2+^|rd           2+^|1010011 <|FCLASS.Q
 4+^|1100011        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.W.Q
 4+^|1100011        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.WU.Q
 4+^|1101011        2+^|00000 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.W
 4+^|1101011        2+^|00001 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.WU
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*RV64Q 标准扩展 (除 RV32Q 外)*
 4+^|1100011        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.L.Q
 4+^|1100011        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.LU.Q
 4+^|1101011        2+^|00010 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.L
 4+^|1101011        2+^|00011 2+^|rs1   2+^|rm     2+^|rd           2+^|1010011 <|FCVT.Q.LU
|===

<<<

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|
    |31 |27 |26  |25    |24 |  20|19  |  15| 14  |  12|11      |      7|6   |     0|
 4+^|funct7          2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R 型
 2+^|rs3 2+^|funct2 2+^|rs2  2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|R4 型
 6+^|imm[11:0]               2+^|rs1    2+^|funct3 2+^|rd           2+^|opcode  <|I 型
 4+^|imm[11:5]      2+^|rs2  2+^|rs1    2+^|funct3 2+^|imm[4:0]     2+^|opcode  <|S 型
|===

[%autowidth.stretch,float="center",align="center",cols="^m,^m,^m,^m,^m,^m,^m,<m",options="header"]
|===
8+|RV32Zfh 标准扩展
3+|imm[11:0] |rs1 |001 |rd |0000111 |FLH
2+|imm[11:5] |rs2 |rs1 |001 |imm[4:0] |0100111 |FSH
|rs3 |10     |rs2 |rs1 |rm |rd |1000011 |FMADD.H
|rs3 |10     |rs2 |rs1 |rm |rd |1000111 |FMSUB.H
|rs3 |10     |rs2 |rs1 |rm |rd |1001011 |FNMSUB.H
|rs3 |10     |rs2 |rs1 |rm |rd |1001111 |FNMADD.H
2+|0000010 |rs2  |rs1 |rm |rd |1010011 |FADD.H
2+|0000110 |rs2  |rs1 |rm |rd |1010011 |FSUB.H
2+|0001010 |rs2  |rs1 |rm |rd |1010011 |FMUL.H
2+|0001110 |rs2  |rs1 |rm |rd |1010011 |FDIV.H
2+|0101110 |00000 |rs1 |rm |rd |1010011 |FSQRT.H
2+|0010010 |rs2  |rs1 |000 |rd |1010011 |FSGNJ.H
2+|0010010 |rs2  |rs1 |001 |rd |1010011 |FSGNJN.H
2+|0010010 |rs2  |rs1 |010 |rd |1010011 |FSGNJX.H
2+|0010110 |rs2  |rs1 |000 |rd |1010011 |FMIN.H
2+|0010110 |rs2  |rs1 |001 |rd |1010011 |FMAX.H
2+|0100000 |00010 |rs1 |rm |rd |1010011 |FCVT.S.H
2+|0100010 |00000 |rs1 |rm |rd |1010011 |FCVT.H.S
2+|0100001 |00010 |rs1 |rm |rd |1010011 |FCVT.D.H
2+|0100010 |00001 |rs1 |rm |rd |1010011 |FCVT.H.D
2+|0100011 |00010 |rs1 |rm |rd |1010011 |FCVT.Q.H
2+|0100010 |00011 |rs1 |rm |rd |1010011 |FCVT.H.Q
2+|1010010 |rs2  |rs1 |010 |rd |1010011 |FEQ.H
2+|1010010 |rs2  |rs1 |001 |rd |1010011 |FLT.H
2+|1010010 |rs2  |rs1 |000 |rd |1010011 |FLE.H
2+|1110010 |00000 |rs1 |001 |rd |1010011 |FCLASS.H
2+|1100010 |00000 |rs1 |rm |rd |1010011 |FCVT.W.H
2+|1100010 |00001 |rs1 |rm |rd |1010011 |FCVT.WU.H
2+|1110010 |00000 |rs1 |000 |rd |1010011 |FMV.X.H
2+|1101010 |00000 |rs1 |rm |rd |1010011 |FCVT.H.W
2+|1101010 |00001 |rs1 |rm |rd |1010011 |FCVT.H.WU
2+|1111010 |00000 |rs1 |000 |rd |1010011 |FMV.H.X
|===

[%autowidth.stretch,float="center",align="center",cols="^m,^m,^m,^m,^m,^m,^m,<m",options="header"]
|===
8+|RV64Zfh 标准扩展 (除 RV32Zfh 外)
2+|1100010 |00010 |rs1 |rm |rd |1010011 |FCVT.L.H
2+|1100010 |00011 |rs1 |rm |rd |1010011 |FCVT.LU.H
2+|1101010 |00010 |rs1 |rm |rd |1010011 |FCVT.H.L
2+|1101010 |00011 |rs1 |rm |rd |1010011 |FCVT.H.LU
|===

[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|Zawrs 标准扩展

6+^|000000001101 2+^|00000 2+^|000 2+^|00000 2+^|1110011 <|WRS.NTO
6+^|000000011101 2+^|00000 2+^|000 2+^|00000 2+^|1110011 <|WRS.STO
|===


<<rvgcsrnames>> 列出了当前已分配 CSR 地址的 CSR。计时器、计数器和浮点 CSR 是本规范中定义的唯一 CSR。

[[rvgcsrnames]]
.RISC-V 控制和状态寄存器（CSR）地址映射。
[%autowidth,float="center",align="center",cols="<m,<,<m,<",options="header"]
|===
|Number|Privilege|Name|Description
4+^|浮点控制和状态寄存器
|0x001|读写|fflags|浮点累积异常标志。
|0x002|读写|frm|浮点动态舍入模式。
|0x003|读写|fcsr|浮点控制和状态寄存器 (frm + fflags)。
4+^|计数器和定时器
|0xC00|只读|cycle|用于 RDCYCLE 指令的周期计数器。
|0xC01|只读|time|用于 RDTIME 指令的定时器。
|0xC02|只读|instret|用于 RDINSTRET 指令的已执行指令计数器。
|0xC80|只读|cycleh|cycle 的高 32 位，仅 RV32I。
|0xC81|只读|timeh|time 的高 32 位，仅 RV32I。
|0xC82|只读|instreth|instret 的高 32 位，仅 RV32I。
|===
