[[rv64]]
== RV64I 基础整数指令集，版本 2.1

本章描述了 RV64I 基础整数指令集，它基于 <<rv32>> 中描述的 RV32I 变体构建。
本章仅介绍与 RV32I 的区别，因此应结合前一章一起阅读。

=== 寄存器状态

RV64I 将整数寄存器和支持的用户地址空间扩展到 64 位（<<gprs>> 中的 XLEN=64）。

=== 整数计算指令

大多数整数计算指令对 XLEN 位值进行操作。
提供了额外的指令变体来操作 RV64I 中的 32 位值，这些指令以操作码的 'W' 后缀表示。这些 "*W" 指令忽略输入的高 32 位，并始终生成 32 位有符号值，将其符号扩展到 64 位，即 XLEN-1 到 31 位相等。

[NOTE]
====
编译器和调用约定保持一个不变性，即所有 32 位值都以符号扩展格式保存在 64 位寄存器中。
即使是 32 位无符号整数也将第 31 位扩展到第 63 到 32 位。
因此，无符号和有符号 32 位整数之间的转换是无操作的，从有符号 32 位整数到有符号 64 位整数的转换也是如此。在此不变性下，现有的 64 位宽 SLTU 和无符号分支比较仍然可以正确操作无符号 32 位整数。同样，现有的 64 位宽逻辑操作对 32 位符号扩展整数保持符号扩展属性。需要一些新指令（ADD[I]W/SUBW/SxxW）来确保 32 位值的合理性能。
====

==== 整数寄存器-立即数指令

include::images/wavedrom/rv64i-base-int.adoc[]
[[rv64i-base-int]]
//.RV64I 寄存器-立即数指令

ADDIW 是一个 RV64I 指令，它将符号扩展的 12 位立即数加到寄存器 _rs1_ 并在 _rd_ 中生成 32 位结果的正确符号扩展。溢出被忽略，结果是符号扩展到 64 位的低 32 位结果。注意，ADDIW _rd, rs1, 0_ 将寄存器 _rs1_ 的低 32 位的符号扩展写入寄存器 _rd_（汇编伪指令 SEXT.W）。

include::images/wavedrom/rv64i-slli.adoc[]
[[rv64i-slli]]
//.RV64I 寄存器-立即数（描述 ADDIW）指令

常量移位被编码为 I 型格式的特化，使用与 RV32I 相同的指令操作码。要移位的操作数在 _rs1_ 中，移位量编码在 RV64I 的 I-立即数字段的低 6 位中。右移类型编码在第 30 位。SLLI 是逻辑左移（零被移入低位）；SRLI 是逻辑右移（零被移入高位）；SRAI 是算术右移（原符号位被复制到空出的高位）。
(((RV64I, SLLI)))
(((RV64I, SRKIW)))
(((RV64I, SRLIW)))
(((RV64I, RV64I-only)))

include::images/wavedrom/rv64i-slliw.adoc[]
[[rv64i-slliw]]

SLLIW、SRLIW 和 SRAIW 是 RV64I 专用指令，定义类似，但对 32 位值进行操作，并将其 32 位结果符号扩展到 64 位。SLLIW、SRLIW 和 SRAIW 编码中 _imm[5] &#8800; 0_ 是保留的。

[NOTE]
====
以前，_imm[5] &#8800; 0_ 的 SLLIW、SRLIW 和 SRAIW 被定义为引发非法指令异常，而现在它们被标记为保留。这是一个向后兼容的更改。
====

include::images/wavedrom/rv64_lui-auipc.adoc[]
[[rv64_lui-auipc]]
//.RV64I 寄存器-立即数（描述）指令

LUI（加载上立即数）使用与 RV32I 相同的操作码。LUI 将 32 位 U-立即数放入寄存器 _rd_，最低 12 位填充为零。32 位结果符号扩展到 64 位。
(((RV64I, LUI)))

AUIPC（将上立即数加到 `pc`）使用与 RV32I 相同的操作码。AUIPC 用于构建 `pc` 相对地址，并使用 U 型格式。AUIPC 从 U-立即数形成 32 位偏移量，最低 12 位填充为零，符号扩展结果到 64 位，将其加到 AUIPC 指令的地址，然后将结果放入寄存器 _rd_。

[NOTE]
====
注意，通过在 RV64I 中将 LUI 与 LD、AUIPC 与 JALR 等配对形成的地址偏移集是
[latexmath:[${-}2^{31}{-}2^{11}$], latexmath:[$2^{31}{-}2^{11}{-}1$]]。
====

==== 整数寄存器-寄存器操作

include::images/wavedrom/rv64i_int-reg-reg.adoc[]
[[int_reg-reg]]
//.RV64I 整数寄存器-寄存器指令

ADDW 和 SUBW 是 RV64I 专用指令，定义类似于 ADD 和 SUB，但对 32 位值进行操作并生成有符号 32 位结果。溢出被忽略，结果的低 32 位符号扩展到 64 位并写入目标寄存器。
(((RV64I-only, ADDW)))
(((RV64I-only, SUBW)))

SLL、SRL 和 SRA 对寄存器 _rs1_ 中的值按寄存器 _rs2_ 中的移位量执行逻辑左移、逻辑右移和算术右移。在 RV64I 中，仅考虑 _rs2_ 的低 6 位作为移位量。

SLLW、SRLW 和 SRAW 是 RV64I 专用指令，定义类似，但对 32 位值进行操作，并将其 32 位结果符号扩展到 64 位。移位量由 _rs2[4:0]_ 给出。
(((RV64I-only, SLLW)))
(((RV64I-only, SRLW)))
(((RV64I-only, SRAW)))

=== 加载和存储指令

RV64I 将地址空间扩展到 64 位。执行环境将定义地址空间的哪些部分是合法访问的。

include::images/wavedrom/load_store.adoc[]
[[load_store]]
//.加载和存储指令

LD 指令从内存加载 64 位值到寄存器 _rd_，适用于 RV64I。
(((RV64I, LD)))

LW 指令从内存加载 32 位值，并将其符号扩展到 64 位，然后存储在寄存器 _rd_ 中，适用于 RV64I。另一方面，LWU 指令将内存中的 32 位值零扩展，适用于 RV64I。LH 和 LHU 类似地定义为 16 位值，LB 和 LBU 类似地定义为 8 位值。SD、SW、SH 和 SB 指令分别将寄存器 _rs2_ 的低位 64 位、32 位、16 位和 8 位值存储到内存中。

[[rv64i-hints]]
=== HINT 指令

RV32I 中的所有微架构 HINT 指令（见 <<rv32>>）在 RV64I 中也是 HINT 指令。
RV64I 中的额外计算指令扩展了标准和自定义 HINT 编码空间。
(((RV64I, HINT)))

<<rv64i-h>> 列出了所有 RV64I HINT 代码点。91% 的 HINT 空间保留用于标准 HINT，但目前没有定义。其余的 HINT 空间指定用于自定义 HINT；在此子空间中将永远不会定义标准 HINT。

[[rv64i-h]]
.RV64I HINT 指令。
[float="center",align="center",cols="<,<,^,<", options="header", grid="all"]
|===
|指令 |约束 |代码点 |用途
|LUI |_rd_=_x0_ |latexmath:[$2^{20}$] .9+.^|_指定用于未来标准用途_

|AUIPC |_rd_=_x0_ |latexmath:[$2^{20}$]

|ADDI |_rd_=_x0_，且 _rs1_≠_x0_ 或 _imm_≠0  |latexmath:[$2^{17}-1$]

|ANDI |_rd_=_x0_ |latexmath:[$2^{17}$]

|ORI |_rd_=_x0_ |latexmath:[$2^{17}$]

|XORI |_rd_=_x0_ |latexmath:[$2^{17}$]

|ADDIW |_rd_=_x0_ |latexmath:[$2^{17}$]

|ADD |_rd_=_x0_，_rs1_≠_x0_ |latexmath:[$2^{10}-32$]

|ADD |_rd_=_x0_，_rs1_=_x0_，_rs2_≠_x2_-_x5_| 28

|ADD |_rd_=_x0_，_rs1_=_x0_，_rs2_=_x2_-_x5_| 4 | (_rs2_=_x2_) NTL.P1 +
 (_rs2_=_x3_) NTL.PALL +
 (_rs2_=_x4_) NTL.S1 +
 (_rs2_=_x5_) NTL.ALL

|SUB |_rd_=_x0_ |latexmath:[$2^{10}$] .16+.^| _指定用于未来标准用途_

|AND |_rd_=_x0_ |latexmath:[$2^{10}$]

|OR |_rd_=_x0_ |latexmath:[$2^{10}$]

|XOR |_rd_=_x0_ |latexmath:[$2^{10}$]

|SLL |_rd_=_x0_ |latexmath:[$2^{10}$]

|SRL |_rd_=_x0_ |latexmath:[$2^{10}$]

|SRA |_rd_=_x0_ |latexmath:[$2^{10}$]

|ADDW |_rd_=_x0_ |latexmath:[$2^{10}$]

|SUBW |_rd_=_x0_ |latexmath:[$2^{10}$]

|SLLW |_rd_=_x0_ |latexmath:[$2^{10}$]

|SRLW |_rd_=_x0_ |latexmath:[$2^{10}$]

|SRAW |_rd_=_x0_ |latexmath:[$2^{10}$]

|FENCE |_rd_=_x0_，_rs1_≠_x0_，_fm_=0，且 _pred_=0 或 _succ_=0 |latexmath:[$2^{10}-63$]

|FENCE |_rd_≠_x0_，_rs1_=_x0_，_fm_=0，且 _pred_=0 或 _succ_=0  |latexmath:[$2^{10}-63$]

|FENCE |_rd_=_rs1_=_x0_，_fm_=0，_pred_=0，_succ_≠0 |15

|FENCE |_pred_=0 或 _succ_=0，_pred_≠W，_succ_ =0  | 15

|FENCE |_rd_=_rs1_=_x0_，_fm_=0，_pred_=W，_succ_=0 |1 | PAUSE

|SLTI |_rd_=_x0_ |latexmath:[$2^{17}$] .10+.^|_指定用于自定义用途_

|SLTIU |_rd_=_x0_ |latexmath:[$2^{17}$]

|SLLI |_rd_=_x0_ |latexmath:[$2^{11}$]

|SRLI |_rd_=_x0_ |latexmath:[$2^{11}$]

|SRAI |_rd_=_x0_ |latexmath:[$2^{11}$]

|SLLIW |_rd_=_x0_ |latexmath:[$2^{10}$]

|SRLIW |_rd_=_x0_ |latexmath:[$2^{10}$]

|SRAIW |_rd_=_x0_ |latexmath:[$2^{10}$]

|SLT |_rd_=_x0_ |latexmath:[$2^{10}$]

|SLTU |_rd_=_x0_ |latexmath:[$2^{10}$]
|===
