[[sec:zfinx]]
== "Zfinx", "Zdinx", "Zhinx", "Zhinxmin" 整数寄存器中的浮点扩展，版本 1.0

本章定义了 "Zfinx" 扩展（发音为 "z-f-in-x"），该扩展提供了类似于标准单精度浮点指令 F 扩展的指令，但这些指令在 `x` 寄存器上操作，而不是 `f` 寄存器。本章还定义了 "Zdinx"、"Zhinx" 和 "Zhinxmin" 扩展，这些扩展为其他浮点精度提供了类似的指令。

[NOTE]
====
F 扩展使用单独的 `f` 寄存器进行浮点计算，以减少寄存器压力并简化宽超标量的寄存器文件端口的提供。然而，增加的架构状态增加了最小实现成本。通过消除 `f` 寄存器，Zfinx 扩展大大降低了支持浮点指令集的简单 RISC-V 实现的成本。Zfinx 还减少了上下文切换成本。

通常，假设存在 F 扩展的软件与假设存在 Zfinx 扩展的软件不兼容，反之亦然。
====

Zfinx 扩展添加了 F 扩展添加的所有指令，_除了_ 传输指令 FLW、FSW、FMV.W.X、FMV.X.W、C.FLW[SP] 和 C.FSW[SP]。

[NOTE]
====
Zfinx 软件使用整数加载和存储将浮点值从内存传输到内存。寄存器之间的传输使用整数算术或浮点符号注入指令。
====
这些 F 扩展指令的 Zfinx 变体具有相同的语义，除了每当这样的指令访问 `f` 寄存器时，它改为访问具有相同编号的 `x` 寄存器。

Zfinx 扩展依赖于 "Zicsr" 扩展来访问控制和状态寄存器。

=== 处理较窄的值

宽度为 _w_ 小于 XLEN 位的浮点操作数占据 `x` 寄存器的位 _w_-1:0。对 _w_ 位操作数的浮点操作忽略操作数位 XLEN-1: _w_。

生成 _w_ 小于 XLEN 位结果的浮点操作将位 XLEN-1: _w_ 填充为位 _w_-1（符号位）的副本。

[NOTE]
====
`f` 寄存器中使用的 NaN 框方案旨在有效支持重新编码的浮点格式。由于相同的寄存器同时保存浮点和整数操作数，重新编码对于 Zfinx 来说不太实用。因此，NaN 框的需求减少了。

在 RV64 `x` 寄存器中保存 32 位浮点数时进行符号扩展与现有的 RV64 调用约定兼容，这些约定在 `x` 寄存器中传递 32 位浮点值时将位 63-32 留空。为了使架构更加规则，我们将此模式扩展到 RV32 和 RV64 中的 16 位浮点数。
====
=== Zdinx

Zdinx 扩展提供了类似的双精度浮点指令。Zdinx 扩展需要 Zfinx 扩展。

Zdinx 扩展添加了 D 扩展添加的所有指令，_除了_ 传输指令 FLD、FSD、FMV.D.X、FMV.X.D、C.FLD[SP] 和 C.FSD[SP]。

这些 D 扩展指令的 Zdinx 变体具有相同的语义，除了每当这样的指令访问 `f` 寄存器时，它改为访问具有相同编号的 `x` 寄存器。

=== 处理较宽的值

RV32Zdinx 中的双精度操作数保存在对齐的 `x` 寄存器对中，即寄存器编号必须为偶数。双宽浮点操作数使用未对齐（奇数编号）寄存器是 _保留_ 的。

无论字节序如何，编号较低的寄存器保存低位，编号较高的寄存器保存高位：例如，RV32Zdinx 中的双精度操作数的位 31:0 可能保存在寄存器 `x14` 中，该操作数的位 63:32 保存在 `x15` 中。

当双宽浮点结果写入 `x0` 时，整个写入无效：例如，对于 RV32Zdinx，将双精度结果写入 `x0` 不会导致 `x1` 被写入。

当 `x0` 用作双宽浮点操作数时，整个操作数为零——即 `x1` 不被访问。

[NOTE]
====
不提供成对加载和存储指令，因此在 RV32Zdinx 中将双精度操作数从内存传输到内存需要两个加载或存储。然而，寄存器移动只需要一个 FSGNJ.D 指令。
====
=== Zhinx

Zhinx 扩展提供了类似的半精度浮点指令。Zhinx 扩展需要 Zfinx 扩展。

Zhinx 扩展添加了 Zfh 扩展添加的所有指令，_除了_ 传输指令 FLH、FSH、FMV.H.X 和 FMV.X.H。

这些 Zfh 扩展指令的 Zhinx 变体具有相同的语义，除了每当这样的指令访问 `f` 寄存器时，它改为访问具有相同编号的 `x` 寄存器。

=== Zhinxmin

Zhinxmin 扩展提供了对在 `x` 寄存器上操作的 16 位半精度浮点指令的最小支持。Zhinxmin 扩展需要 Zfinx 扩展。

Zhinxmin 扩展包括 Zhinx 扩展中的以下指令：FCVT.S.H 和 FCVT.H.S。如果存在 Zdinx 扩展，还包括 FCVT.D.H 和 FCVT.H.D 指令。
[NOTE]
====
将来，可以类似于 RV32Zdinx 定义 RV64Zqinx 四精度扩展。也可以定义 RV32Zqinx 扩展，但需要四寄存器组。
====
=== 特权架构的影响

在第 II 卷中定义的标准特权架构中，如果实现了 Zfinx 扩展，则 `mstatus` 字段 FS 硬连线为 0，并且 FS 不再影响浮点指令或 `fcsr` 访问的陷阱行为。

当实现 Zfinx 扩展时，`misa` 位 F、D 和 Q 硬连线为 0。
[NOTE]
====
将来可能会使用发现机制来探测 Zfinx、Zhinx 和 Zdinx 扩展的存在。
====
