[[sec:zfinx]]
== “Zfinx”“Zdinx”“Zhinx”“Zhinxmin”扩展：整数寄存器中的浮点，版本 1.0

本章定义了“Zfinx”扩展（发音为 “z-f-in-x”）。该扩展提供了一系列指令，其功能与标准单精度浮点 F 扩展中的指令类似，但操作对象为通用整数寄存器 x，而非浮点寄存器 f。本章还定义了“Zdinx”、“Zhinx”和“Zhinxmin”扩展，它们为其他浮点精度提供了类似的指令支持。

[NOTE]
====
F 扩展采用独立的 f 寄存器进行浮点运算，旨在减轻寄存器压力，并简化对宽超标量处理器提供寄存器堆端口的设计。然而，引入的额外架构会增加最低实现成本。Zfinx 扩展通过移除 f 寄存器，显著降低了支持浮点指令集的简单 RISC-V 实现的成本，同时也减少了上下文切换的开销。

一般而言，假定 F 扩展存在的软件与假定 Zfinx 扩展存在的软件互不兼容。
====

Zfinx 扩展添加了 F 扩展添加的所有指令，除了传输指令 FLW、FSW、FMV.W.X、FMV.X.W、C.FLW[SP] 和 C.FSW[SP]。

[NOTE]
====
Zfinx 软件使用整数加载和存储将浮点值从内存传输到内存或从内存传输到寄存器。寄存器之间的传输使用整数算术操作或浮点符号注入指令。
====
这些 F 扩展指令的 Zfinx 变体具有相同的语义，只是当该指令本应访问 f 寄存器时，它改为访问具有相同编号的 x 寄存器。

Zfinx 扩展依赖于 "Zicsr" 扩展来访问控制状态寄存器。

=== 窄位数值的处理

对于位宽为 w 且小于 XLEN 的浮点操作数，其值将占据 x 寄存器的第 0 到 w-1 位。针对 w 位操作数进行的浮点运算，将忽略操作数在 XLEN-1 到 w 位的数值。

产生 w 位（w < XLEN）浮点结果的操作，会将结果的符号位（即第 w-1 位）复制填充到 x 寄存器的 XLEN-1 到 w 位。

[NOTE]
====
`f` 寄存器中采用的 NaN-装箱方案（NaN-boxing）旨在高效支持重编码浮点格式。然而，由于 Zfinx 扩展的寄存器需要同时存储浮点数和整数，重新编码对于 Zfinx 而言实用性降低，因此 NaN-装箱的需求也随之减弱。

在 RV64 架构中，将 32 位浮点数存储于 `x` 寄存器时进行符号扩展，这与现有的 RV64 调用约定相符——当通过 `x` 寄存器传递 32 位浮点值时，调用约定明确指出寄存器的第 32-63 位为未定义状态。为了保持架构设计的一致性，我们将此模式推广至 RV32 和 RV64 架构中的 16 位浮点数。
====
=== Zdinx

Zdinx 扩展提供了类似的双精度浮点指令。Zdinx 依赖于 Zfinx 扩展。

Zdinx 扩展添加了 D 扩展添加的所有指令，除了传输指令 FLD、FSD、FMV.D.X、FMV.X.D、C.FLD[SP] 和 C.FSD[SP]。

这些 D 扩展指令的 Zdinx 变体具有相同的语义，除了每当这样的指令访问 `f` 寄存器时，它改为访问具有相同编号的 `x` 寄存器。

=== 宽位数值的处理

在 RV32Zdinx 扩展中，双精度操作数需存储于对齐的 `x` 寄存器对中，即寄存器编号必须为偶数。使用未对齐的（奇数编号）寄存器存储双精度浮点操作数的行为是保留的。

无论采用何种字节序，寄存器编号较小的寄存器存储低位数据，编号较大的寄存器存储高位数据。例如，在 RV32Zdinx 中，双精度操作数的 0-31 位可能存储在 x14 寄存器中，而 32-63 位则存储在 x15 寄存器中。

当双精度浮点结果写入 `x0` 寄存器时，整个写入操作将无效。例如，在 RV32Zdinx 架构下，将双精度结果写入 `x0` 不会影响 `x1` 寄存器的内容。

当 `x0` 寄存器被用作双精度浮点操作数时，其值将被视为零，且指令执行过程中不会访问 `x1` 寄存器。

[NOTE]
====
扩展规范中未提供成对加载/存储指令。因此，在 RV32Zdinx 扩展中，从内存加载或向内存存储双精度操作数，需要执行两次独立的加载或存储操作。 然而，寄存器之间的数据移动仅需一条 FSGNJ.D 指令即可完成。
====
=== Zhinx

Zhinx 扩展提供了与之类似的半精度浮点指令集，且 Zhinx 扩展依赖于 Zfinx 扩展。

Zhinx 扩展添加了 Zfh 扩展添加的所有指令，除了传输指令 FLH、FSH、FMV.H.X 和 FMV.X.H。

Zfh 扩展指令的 Zhinx 版本，在指令语义上与 Zfh 扩展保持一致，不同之处仅在于，当指令原本需要访问 `f` 寄存器时，Zhinx 版本会转而访问相同编号的 `x` 寄存器。

=== Zhinxmin

Zhinxmin 扩展旨在为在 `x` 寄存器上进行的 16 位半精度浮点运算提供最基本的支持。Zhinxmin 扩展依赖于 Zfinx 扩展。

Zhinxmin 扩展仅包含 Zhinx 扩展中的 FCVT.S.H 和 FCVT.H.S 指令。 如果系统中同时存在 Zdinx 扩展，则 Zhinxmin 扩展还会额外包含 FCVT.D.H 和 FCVT.H.D 指令。
[NOTE]
====
未来，可以参照 RV32Zdinx 扩展的模式，定义 RV64Zqinx 四精度扩展。此外，亦可考虑定义 RV32Zqinx 扩展，但这将需要采用四倍字寄存器组合来存储四精度浮点数。
====
=== 特权架构的影响

在卷 II 定义的标准特权架构中，若实现了 Zfinx 扩展，则 `mstatus` 寄存器的 FS 字段将被硬连接为 0。此时，FS 字段将不再对浮点指令或 `fcsr` 访问的陷阱行为产生影响。

当 Zfinx 扩展被实现后，`misa` 寄存器中的 F、D 和 Q 位也将被硬连接置 0。
[NOTE]
====
未来或将引入某种探测机制，用于检测 Zfinx、Zhinx 和 Zdinx 扩展是否存在于系统中。
====
