[[Zicond]]
== "Zicond"扩展： 整数条件操作，版本 1.0.0

[[intro]]
=== 介绍
Zicond 扩展定义了一种简单的符合 RISC-V 设计理念的解决方案，用于支持条件算术和条件选择/移动操作。这一方案提供了许多好处和高度的灵活性。
这些指令遵循 R 型指令的格式，具有 3 个操作数（即 2 个源操作数和 1 个目标操作数）。
使用这些指令，可以实现无分支序列（通常是两条指令的序列），无需指令融合、在解码架构指令时的特殊规定或其他微架构规定。

与竞争指令集架构相比，RISC-V 的一个缺点是缺乏支持无分支代码生成的条件操作：这包括条件算术、条件选择和条件移动操作。
RISC-V 的设计原则（例如，缺乏支持 3 个源寄存器和一个输出寄存器的指令格式）使得引入竞争指令的直接等效指令变得不太可能。

然而，低成本的条件指令是一项理想的功能，因为它们可以在广泛的场景下替换分支（无论分支是否不可预测或可预测），以减少 BTB 和分支预测器的容量和别名压力，并允许更长的基本块（供硬件和编译器使用）。

=== Zicond 规范

“条件”操作扩展定义了一种简单的符合 RISC-V 设计理念的解决方案，用于支持条件算术和条件选择/移动操作。这一方案提供了许多好处和高度的灵活性。
这些指令遵循 R 型指令的格式，具有 3 个操作数（即 2 个源操作数和 1 个目标操作数）。
使用这些指令，可以实现无分支序列（通常是两条指令的序列），无需指令融合、在解码架构指令时的特殊规定或其他微架构规定。

以下指令组成了 Zicond 扩展：

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|助记符
|指令

|&#10003;
|&#10003;
|czero.eqz _rd_, _rs1_, _rs2_
|<<#insns-czero-eqz>>

|&#10003;
|&#10003;
|czero.nez _rd_, _rs1_, _rs2_
|<<#insns-czero-nez>>

|===

[NOTE]
====
架构评论：由于缺乏立即数或额外的寄存器操作数进行比较，定义额外的比较（除了等于零和不等于零之外）没有好处。
====

基于这两条指令，支持以下*条件算术*操作的合成指令（即短指令序列）：

* 条件加法，如果为零
* 条件加法，如果非零
* 条件减法，如果为零
* 条件减法，如果非零
* 条件按位与，如果为零
* 条件按位与，如果非零
* 条件按位或，如果为零
* 条件按位或，如果非零
* 条件按位异或，如果为零
* 条件按位异或，如果非零

此外，还支持以下*条件选择*指令：

* 条件选择，如果为零
* 条件选择，如果非零

更复杂的条件，例如与立即数、寄存器、单个位测试、范围比较等的比较，可以通过将这些新指令与现有指令组合来实现。

=== 指令（按字母顺序）

[#insns-czero-eqz,reftext="条件零，如果条件等于零"]
==== czero.eqz

简述::
如果条件 _rs2_ 等于零，则将零移动到寄存器 _rd_，否则将 _rs1_ 移动到 _rd_。

助记符::
czero.eqz _rd_, _rs1_, _rs2_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x5, attr: ['CZERO.EQZ']},
    { bits:  5, name: 'rs1', attr: ['value'] },
    { bits:  5, name: 'rs2', attr: ['condition'] },
    { bits:  7, name: 0x7, attr: ['CZERO'] },
]}
....

描述::
如果 _rs2_ 包含值零，则此指令将值零写入 _rd_。否则，此指令将 _rs1_ 的内容复制到 _rd_。

此指令在语法上存在 _rs1_ 和 _rs2_ 到 _rd_ 之间的依赖关系。
此外，如果实现了 Zkt 扩展，则此指令的时序与 _rs1_ 和 _rs2_ 中的数据值无关。

SAIL 代码::
[source,sail]
--
  let condition = X(rs2);
  result : xlenbits = if (condition == zeros()) then zeros()
                                                else X(rs1);
  X(rd) = result;
--

<<<

[#insns-czero-nez,reftext="条件零，如果条件不等于零"]
==== czero.nez

简述::
如果条件 _rs2_ 不等于零，则将零移动到寄存器 _rd_，否则将 _rs1_ 移动到 _rd_。

助记符::
czero.nez _rd_, _rs1_, _rs2_

编码::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x7, attr: ['CZERO.NEZ']},
    { bits:  5, name: 'rs1', attr: ['value'] },
    { bits:  5, name: 'rs2', attr: ['condition'] },
    { bits:  7, name: 0x7, attr: ['CZERO'] },
]}
....

描述::
如果 _rs2_ 包含非零值，则此指令将值零写入 _rd_。否则，此指令将 _rs1_ 的内容复制到 _rd_。

此指令在语法上存在 _rs1_ 和 _rs2_ 到 _rd_ 之间的依赖关系。
此外，如果实现了 Zkt 扩展，则此指令的时间与 _rs1_ 和 _rs2_ 中的数据值无关。

SAIL 代码::
[source,sail]
--
  let condition = X(rs2);
  result : xlenbits = if (condition != zeros()) then zeros()
                                                else X(rs1);
  X(rd) = result;
--

=== 使用示例

此扩展中的指令可用于构建执行条件算术、条件按位逻辑和条件选择操作的序列。

==== 指令序列

[%header,cols="4,.^3l,^2"]
|===
|操作
|指令序列
|长度

|*为零条件加法* +
`rd = (rc == 0) ? (rs1 + rs2) : rs1`
|czero.nez  rd, rs2, rc
add        rd, rs1, rd
.8+.^|2 条指令

|*非零条件加法* +
`rd = (rc != 0) ? (rs1 + rs2) : rs1`
|czero.eqz  rd, rs2, rc
add        rd, rs1, rd

|*为零条件减法* +
`rd = (rc == 0) ? (rs1 - rs2) : rs1`
|czero.nez  rd, rs2, rc
sub        rd, rs1, rd

|*非零条件减法* +
`rd = (rc != 0) ? (rs1 - rs2) : rs1`
|czero.eqz  rd, rs2, rc
sub        rd, rs1, rd

|*为零条件按位或* +
`rd = (rc == 0) ? (rs1 \| rs2) : rs1`
|czero.nez  rd, rs2, rc
or         rd, rs1, rd

|*非零条件按位或* +
`rd = (rc != 0) ? (rs1 \| rs2) : rs1`
|czero.eqz  rd, rs2, rc
or         rd, rs1, rd

|*为零条件按位异或* +
`rd = (rc == 0) ? (rs1 ^ rs2) : rs1`
|czero.nez  rd, rs2, rc
xor        rd, rs1, rd

|*非零条件按位异或* +
`rd = (rc != 0) ? (rs1 ^ rs2) : rs1`
|czero.eqz  rd, rs2, rc
xor        rd, rs1, rd

|*为零条件按位与* +
`rd = (rc == 0) ? (rs1 & rs2) : rs1`
|and        rd, rs1, rs2
czero.eqz  rtmp, rs1, rc
or         rd, rd, rtmp
.4+.^|3 条指令 +
（需要 1 个临时寄存器）

|*非零条件按位与* +
`rd = (rc != 0) ? (rs1 & rs2) : rs1`
|and        rd, rs1, rs2
czero.nez  rtmp, rs1, rc
or         rd, rd, rtmp

|*为零条件选择* +
`rd = (rc == 0) ? rs1 : rs2`
|czero.nez  rd, rs1, rc
czero.eqz  rtmp, rs2, rc
or         rd, rd, rtmp

|*非零条件选择* +
`rd = (rc != 0) ? rs1 : rs2`
|czero.eqz  rd, rs1, rc
czero.nez  rtmp, rs2, rc
or         rd, rd, rtmp

|===
