[[zihintpause]]
== “Zihintpause”扩展：PAUSE 提示指令，版本 2.0

PAUSE 指令是一条硬件提示指令（HINT），用于表明当前硬件线程的指令执行速度应被临时降低或暂停。其影响的持续时间必须有界，且可能为零。
(((PAUSE, HINT)))
(((HINT, PAUSE)))

[NOTE]
====
软件可以利用 PAUSE 指令来降低执行自旋等待循环时的功耗。在多线程处理器核上，当执行 PAUSE 指令时，硬件线程或许会暂时将执行资源让渡给其他硬件线程。通常建议在自旋等待循环的代码中包含 PAUSE 指令。
(((PAUSE, energy consumption)))

未来的扩展可能会添加类似于 x86 架构的 MONITOR/MWAIT 指令，这些指令提供了更高效的机制，用于等待对特定内存位置的写入。然而，这些指令并不会替代 PAUSE 指令。PAUSE 指令更适用于轮询非内存事件、轮询多个事件，或者当软件无法准确得知其正在轮询何种事件时。

PAUSE 指令的效果持续时间在不同实现之间以及同一实现内部可能存在显著差异。在典型实现中，该持续时间应远小于上下文切换所需的时间，大致与片上缓存未命中延迟或无缓存访问主存的延迟相当。
(((PAUSE, duration)))

一系列连续执行的 PAUSE 指令可以产生累积的延迟效果，总延迟时间与 PAUSE 指令的数量大致成正比。然而，在可移植代码的自旋等待循环中，在重新评估循环条件之前务必仅使用一条 PAUSE 指令；否则在某些实现中，硬件线程可能会非必要地停滞过长时间，从而导致系统性能下降。
====

PAUSE 指令采用 FENCE 指令的编码格式，并定义其字段为： _pred_=`W`、_succ_=`0`、_fm_=`0`、_rd_=`x0` 以及 _rs1_=`x0`。

//include::images/wavedrom/zihintpause-hint.adoc[]
//[zihintpause-hint]
//.Zihintpause fence instructions

[NOTE]
====
PAUSE 指令之所以被编码为 FENCE 操作码中的一种提示，是因为部分实现可能会刻意使得 PAUSE 指令停顿，直至所有未完成的内存事务处理完毕。然而，鉴于其后续指令集为空，PAUSE 指令并不强制规定任何特定的内存访问顺序。因此，它的确只是一个硬件提示。
(((PAUSE, encoding)))

与其他的 FENCE 指令相同，PAUSE 指令也不能在 LR/SC 序列中使用，否则将破坏持续进展。
(((PAUSE, LR/RC sequences)))

由于其后继集为空，PAUSE 指令可以任意选择前驱指令集 W 。与 PAUSE 指令类似的其他提示指令可能会使用其他前驱集进行编码。
====
