[[zihintpause]]
== “Zihintpause” 扩展 - PAUSE 提示指令，版本 2.0

PAUSE 指令是一个提示（HINT），它表示当前硬件线程的指令退休速率应该暂时减慢或暂停。其影响的持续时间必须有界，且可能为零。
(((PAUSE, HINT)))
(((HINT, PAUSE)))

[NOTE]
====
软件可以使用 PAUSE 指令来减少执行自旋等待（spin-wait）代码序列时的能耗。在多线程核心上，执行 PAUSE 指令时，硬件线程可能会暂时将执行资源让给其它硬件线程。建议在自旋等待循环的代码序列中通常包含 PAUSE 指令。
(((PAUSE, energy consumption)))

未来的扩展可能会添加类似于 x86 的 MONITOR/MWAIT 指令，这些指令提供了更高效的机制来等待特定内存位置的写操作。然而，这些指令并不会取代 PAUSE 指令。PAUSE 更适合用于轮询非内存事件、轮询多个事件，或当软件无法精确知道它正在轮询什么事件时。

PAUSE 指令的效果持续时间在不同的实现中可能有显著差异。在典型的实现中，这段时间通常应该远小于执行上下文切换的时间，可能大致与片上缓存缺失延迟或无缓存访问主内存的延迟相当。
(((PAUSE, duration)))

一系列 PAUSE 指令可以用来创建一个累积的延迟，这个延迟大致与 PAUSE 指令的数量成正比。然而，在便携式代码中的自旋等待循环中，通常应该只使用一个 PAUSE 指令，然后重新评估循环条件，否则在某些实现上，硬件线程可能会比最优时更长时间地停滞，导致系统性能下降。
====

PAUSE 被编码为一个 FENCE 指令，其中 _pred_=`W`、_succ_=`0`、_fm_=`0`、_rd_=`x0` 以及 _rs1_=`x0`。

//include::images/wavedrom/zihintpause-hint.adoc[]
//[zihintpause-hint]
//.Zihintpause fence instructions

[NOTE]
====
PAUSE 被编码为 FENCE 操作码中的一个提示，因为一些实现预计会故意延迟 PAUSE 指令，直到所有待处理的内存事务完成。然而，由于后继集为空，PAUSE 并不强制要求任何特定的内存排序——因此，它确实只是一个提示。
(((PAUSE, encoding)))

与其它 FENCE 指令一样，PAUSE 不能在 LR/SC 序列中使用，否则会违背前进保证（forward-progress guarantee）。
(((PAUSE, LR/RC sequences)))

由于后继集为空，因此选择一个前驱集为 W 是任意的。与 PAUSE 类似的其它提示可能会用其它前驱集进行编码。
====