[[zimop]]
== “Zimop”扩展：可能操作（May-Be-Operations），版本 1.0

本章定义了 "Zimop" 扩展，它引入了可能操作（MOPs）的概念。MOPs 最初被定义为简单地将零写入 `x[rd]`，但设计为可以通过后续扩展重新定义，以执行其他操作。
Zimop 扩展为 40 个 MOP 定义了编码空间。

[NOTE]
====
有时在定义指令集扩展时，希望其指令在未实现扩展时不会引发非法指令异常，而是不会执行任何有用的操作（除了写入 `x[rd]`）。
例如，具有控制流完整性检查的程序可以在没有相应扩展的实现上正确执行，前提是检查被忽略。将这些检查实现为 MOPs 允许相同的程序在有或没有相应扩展的实现上运行。

虽然在某些方面类似于 HINTs，但 MOPs 不能编码为 HINTs，因为与 HINTs 不同，MOPs 允许改变架构状态。

由于 MOPs 可能会被后续扩展重新定义，标准软件不应执行 MOP，除非它是故意针对已重新定义该 MOP 的扩展。
====

Zimop 扩展定义了 32 个名为 MOP.R.__n__ 的 MOP 指令，其中 __n__ 是 0 到 31 之间的整数（包括 0 和 31）。
除非被其他扩展重新定义，否则这些指令只是将 0 写入 `x[rd]`。它们的编码允许未来的扩展将它们定义为读取 `x[rs1]` 并且写入 `x[rd]`。

include::images/wavedrom/mop-r.adoc[]
[[mop-r]]

Zimop 扩展还定义了 8 个名为 MOP.RR.__n__ 的 MOP 指令，其中 __n__ 是 0 到 7 之间的整数（包括 0 和 7）。
除非被其他扩展重新定义，否则这些指令只是将 0 写入 `x[rd]`。它们的编码允许未来的扩展将它们定义为读取 `x[rs1]` 和 `x[rs2]` 并且写入 `x[rd]`。

include::images/wavedrom/mop-rr.adoc[]
[[mop-rr]]

NOTE: MOP.R.__n__ 的推荐汇编语法是 MOP.R.__n__ rd, rs1，任何 `x` 寄存器说明符对任一参数都是有效的。类似地，MOP.RR.__n__ 的推荐语法是 MOP.RR.__n__ rd, rs1, rs2。
重新定义 MOP 的扩展可以定义替代的汇编助记符。

NOTE: 这些 MOP 被编码在 SYSTEM 主操作码中，部分原因是预计它们的行为将由特权 CSR 状态调节。

NOTE: 这些 MOP 被定义为将零写入 `x[rd]`，而不是不执行任何操作，从而简化指令解码，并允许通过分支测试零值来测试功能的存在。

Zimop 扩展中定义的 MOP 不携带从 `x[rs1]` 或 `x[rs2]` 到 `x[rd]` 的语法依赖性，尽管重新定义该 MOP 的扩展可能会添加此类要求。

NOTE: 不携带语法依赖性使得简单的实现可以不读取 `x[rs1]` 和 `x[rs2]`。

=== “Zcmop”扩展：压缩可能操作，版本 1.0

本节定义了 "Zcmop" 扩展，它定义了八个 16 位 MOP 指令，名为 C.MOP.__n__，其中 __n__ 是 1 到 15 之间的奇数（包括 1 和 15）。C.MOP.__n__ 被编码在对应于 C.LUI x__n__, 0 的保留编码空间中，如 <<tab:c-mop>> 所示。
与 Zimop 扩展中定义的 MOP 不同，C.MOP.__n__ 指令被定义为不写入任何寄存器。
它们的编码允许未来的扩展将它们定义为读取寄存器 `x[__n__]`。

Zcmop 扩展需要 Zca 扩展。

include::images/wavedrom/c-mop.adoc[]
[[c-mop]]

NOTE: 很难寻找合适的 16 位编码空间来编码该组指令。而选择此空间是因为它已经在 `rd`/`rs1` 字段方面具有不寻常的行为——当字段包含 `x2` 时，它编码 `c.addi16sp`——因此对于大多数用途来说价值较低。

[[tab:c-mop]]
.C.MOP.__n__ 指令编码。

|===
|助记符 | 编码           | 可重新定义为读取寄存器

|C.MOP.1  | `0110000010000001` | `x1`
|C.MOP.3  | `0110000110000001` | `x3`
|C.MOP.5  | `0110001010000001` | `x5`
|C.MOP.7  | `0110001110000001` | `x7`
|C.MOP.9  | `0110010010000001` | `x9`
|C.MOP.11 | `0110010110000001` | `x11`
|C.MOP.13 | `0110011010000001` | `x13`
|C.MOP.15 | `0110011110000001` | `x15`
|===

NOTE: C.MOP.__n__ 的推荐汇编语法为无参数的简单形式 C.MOP.__n__。可能访问的寄存器隐含为 `x__n__`。

NOTE: 预期每个 Zcmop 指令等效于某个 Zimop 指令，但扩展（如果有）的选择留给重新定义 MOP 的扩展。
NOTE: 不写入值的 Zcmop 指令可以扩展为写入 `x0`。
