[[ztso]]
== “Ztso”扩展：总存储排序扩展，版本 1.0

本章定义了用于 RISC-V 总存储序（RVTSO）内存一致性模型的 “Ztso” 扩展。RVTSO 被定义为 RVWMO 模型的增量式扩展，RVWMO 的具体定义见 <<rvwmo>> 章节。
[NOTE]
====
Ztso 扩展旨在促进最初为 x86 或 SPARC 架构编写的代码的移植，这两种架构都默认采用 TSO 内存模型。此外，对于那些本质上就具备 RVTSO 特性，并希望向软件层面暴露这一特性的硬件实现，本扩展也提供了支持。
====
RVTSO 对 RVWMO 进行了以下调整：

* 所有加载操作的行为，都如同带有 acquire-RCpc 注释。
* 所有存储操作的行为，都如同带有 release-RCpc 注释。
* 所有原子内存操作（AMO）的行为，都如同同时带有 acquire-RCsc 和 release-RCsc 注释。

[NOTE]
====
这些规则使得除 <<overlapping-ordering, 4-7>> 之外的所有 PPO 规则都变得冗余。同样，任何未同时设置 PW 和 SR 标志的非 I/O fences 指令也变得不再必要。最后，这些规则还意味着，任何内存操作都不会与原子内存操作 (AMO) 指令发生重排序，无论重排序方向如何。

与 RVWMO 类似，在 RVTSO 内存模型中，存储顺序的约束也由 PPO 规则 <<overlapping-ordering, 5-7>> 简洁而完整地定义。在这两种内存模型下，<<ax-load>> 规则都允许硬件线程将数据从自身的存储缓冲区转发到后续的（程序顺序上的）加载操作。这意味着，存储操作可以在对其他硬件线程可见之前，先在本地被转发。
====

此外，如果实现了 Ztso 扩展，V 扩展以及 Zve 系列扩展中的向量内存指令，在指令层面也将遵循 RVTSO 内存模型。但 Ztso 扩展并不会增强单条向量指令内部元素访问操作的顺序性。

尽管 Ztso 扩展本身并未在指令集架构（ISA）中引入任何新指令，但为 RVTSO 内存模型编写的代码，在未实现 Ztso 扩展的硬件平台上将无法正确执行。因此，建议仅在 Ztso 环境下运行的二进制文件，应通过某种二进制标志进行标识，以便那些未实现 Ztso 扩展的平台能够直接拒绝执行这些程序。
